
USE TFG;

--- 银行卡


DROP TABLE IF EXISTS TLT_USER_BANK;


CREATE TABLE TLT_USER_BANK (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    USER_ID bigint(20) NOT NULL COMMENT '用户数字ID',
    BANK_CODE varchar(16) NOT NULL COMMENT '银行代码，见银行信息表',
    BANK_NAME varchar(64) NOT NULL COMMENT '银行名称，见银行信息表',
    USERNAME varchar(16) NOT NULL DEFAULT '' COMMENT '银行开户名',
    ACCOUNT varchar(64) NOT NULL DEFAULT '' COMMENT '银行账号',
    MOBILE varchar(64) NOT NULL DEFAULT '' COMMENT '手机号',
    PASSWORD varchar(64)  COMMENT '密码(可有可无)',
    ENABLE tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否有效 1有效 0无效',
    PRIMARY KEY (ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户银行帐户信息';



------彩种管理-----------------------------------------
DROP TABLE IF EXISTS TLT_LTYPE;

CREATE TABLE TLT_LTYPE (
    LTYPE varchar(16) NOT NULL ,
    CN_NAME varchar(32) NOT NULL DEFAULT '' COMMENT '中文名称，如：数字型、乐透同区型等',
    EN_NAME varchar(32) NOT NULL DEFAULT '' COMMENT '英文名称',
    REMARK varchar(255) DEFAULT '' COMMENT '备注',
    PRIMARY KEY (LTYPE)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='彩种类型表';


DROP TABLE IF EXISTS TLT_TYPE;


CREATE TABLE TLT_PLAY_TYPE (
    PLAY_TYPE varchar(16) NOT NULL,
    LTYPE varchar(16) NOT NULL COMMENT '所属类型，TLT_LTYPE.LTYPE',
    CN_NAME varchar(32) NOT NULL DEFAULT '' COMMENT '中文名称',
    EN_NAME varchar(32) NOT NULL DEFAULT '' COMMENT '英文名称',
    CODE_LIST varchar(32) DEFAULT '0,1,2,3,4,5,6,7,8,9' COMMENT '号码形态之：彩票可选号码列表，用半角逗号分隔',
    CODE_LEN int(4) DEFAULT '0' COMMENT '号码形态之：号码总长度',
    SORT tinyint(4) NOT NULL DEFAULT '0' COMMENT '排序，一般显示用',
    ENABLE tinyint(1) NOT NULL DEFAULT '0' COMMENT '0停售 1销售中',
    REMARK varchar(255) DEFAULT NULL COMMENT '备注,描述',
    DELAY_TIME int(4) DEFAULT '0' COMMENT '延后时长，秒？？？？？？',
    CATCH_CODE_COUNT int(4) DEFAULT '0' COMMENT '抓号次数',
    CATCH_CODE_INTERVAL int(4) DEFAULT '0' COMMENT '抓号间隔时长，秒，抓号频率最低不得低于30秒，最高不得高于300秒',
    MIN_LEFT float(10 , 3 ) DEFAULT '0.000' COMMENT '最小剩余利润率',
    MIN_SPREAD float(10 , 3 ) DEFAULT '0.000' COMMENT '上下级最小返点差',
    ISSUE_NO_FMT varchar(16) DEFAULT 'yyyymmdd-nnn' COMMENT '期号格式,yyyymmdd-nnn',
    CLEAR_YMD varchar(8) DEFAULT 'Y,M,D' COMMENT '清零规则，Y年清零，M月清零，D日清零；以逗号分隔，有哪个字母就清零',
    LOTTERY_CYCLE varchar(16) DEFAULT '1,2,3,4,5,6,7' COMMENT '开奖周期,1星期一 2星期二 3星期三 4星期四 5星期五 6星期六 7星期日',
    CLOSE_STIME datetime DEFAULT NULL COMMENT '休市开始时间',
    CLOSE_ETIME datetime DEFAULT NULL COMMENT '休市结束时间',
    REBATE float(5 , 1 ) NOT NULL DEFAULT '0.0' COMMENT '默认返点',
    DELO_REBATE float(5 , 1 ) NOT NULL DEFAULT '0.0' COMMENT '默认不定位返点',
    PRIMARY KEY (PLAY_TYPE)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='彩种（又称游戏）信息表';

create index IDX_TLT_PLAY_TYPE_LTYPE on TLT_PLAY_TYPE
(
   LTYPE
);

-------开奖管理-----------------------------------------
DROP TABLE IF EXISTS TLT_ISSUETIME;

CREATE TABLE TLT_ISSUETIME (
  IT_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  LTYPE VARCHAR(32) NOT NULL COMMENT '所属彩种，对应TLT_TYPE.LTYPE_ID',
  SALE_STIME VARCHAR(20) DEFAULT NULL COMMENT '销售开始时间 YYYYMMDDHHmmss',
  SALE_ETIME VARCHAR(20) DEFAULT NULL COMMENT '销售截止时间 YYYYMMDDHHmmss',
  SALE_FI_ETIME VARCHAR(20) DEFAULT NULL COMMENT '第一期销售截止时间，FI即FIRST ISSUE',
  SALE_CYCLE INT(4) DEFAULT '0' COMMENT '销售周期，秒',
  WAIT_RL_DUR INT(4) DEFAULT '0' COMMENT '等待开奖时长，秒',
  CANCEL_DUR INT(4) DEFAULT '0' COMMENT '撤单限制时长，秒',
  INPUT_DUR INT(4) DEFAULT '0' COMMENT '录入时长，秒',
  SORT TINYINT(4) NOT NULL DEFAULT '0' COMMENT '排序，一般显示用',
  ENABLE TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0无效 1有效',
  KEY INDEX_LTYPE_ID (LTYPE_ID) USING BTREE,
  PRIMARY KEY (ID)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='奖期时间设置表，是批量生成期号的基础';


create index TFG_LOGIN_USER_IDX4 on TFG_LOGIN_USER
(
   EMAIL
);


DROP TABLE IF EXISTS TLT_ISSUE;
CREATE TABLE TLT_ISSUE (
  ISSUE_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  LTYPE VARCHAR(32) NOT NULL COMMENT '所属彩种，对应TLT_TYPE.LTYPE_ID',
  ISSUE_NO VARCHAR(32) NOT NULL DEFAULT '' COMMENT '期号',
  LOTTERY_NO VARCHAR(32) NOT NULL DEFAULT '' COMMENT '开奖号码',
  SALE_STIME DATETIME DEFAULT NULL COMMENT '实际销售开始时间',
  SALE_ETIME DATETIME DEFAULT NULL COMMENT '实际销售截止时间',
  CANCEL_LTIME DATETIME DEFAULT NULL COMMENT '最后撤单时间',
  CHECK_STATUS INT(2) DEFAULT '0' COMMENT '号码验证状态 0未开始 1已开始 2已验证',
  DEBIT_STATUS INT(2) DEFAULT '0' COMMENT '扣款状态 0未开始 1已开始 2已完成',
  REBATE_STATUS INT(2) DEFAULT '0' COMMENT '返点状态 0未开始 1已开始 2已完成',
  WIN_STATUS INT(2) DEFAULT '0' COMMENT '中奖状态 0未开始 1已开始 2已完成',
  SEND_STATUS INT(2) DEFAULT '0' COMMENT '派奖状态 0未开始 1已开始 2已完成',
  AUTOBET_STATUS INT(2) DEFAULT '0' COMMENT '追号状态 0未开始 1已开始 2已完成',
  LOCK_STATUS INT(2) DEFAULT '0' COMMENT '封锁状态 0未开始 1已开始 2已完成',
  
  CREATE_TIME DATETIME DEFAULT NULL COMMENT '生成时间',
  MODIFY_TIME DATETIME DEFAULT NULL COMMENT '修改时间',
  STATUS VARCHAR(1) DEFAULT '1' COMMENT '状态:(1)有效,(0)无效'

  PRIMARY KEY (ISSUE_ID)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='奖期表';





#-------投注管理-----------------------------------------
DROP TABLE IF EXISTS TLT_BET;

CREATE TABLE TLT_BET (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  BET_NO VARCHAR(32) NOT NULL COMMENT '投注编号，由后台生成',
  USER_ID BIGINT(20) NOT NULL COMMENT '投注用户ID',
  LTYPE BIGINT(20) NOT NULL COMMENT '所属游戏，对应TLT_TYPE.LTYPE_ID',
  LPG_ID BIGINT(20) NOT NULL COMMENT '所属玩法组，对应TLT_PLAYGROUP.ID',
  LP_ID BIGINT(20) NOT NULL COMMENT '所属玩法，对应TLT_PLAY.ID',
  BET_IP VARCHAR(20) DEFAULT '' COMMENT '投注IP',
  BET_ISSUE VARCHAR(16) NOT NULL COMMENT '投注期号',
  BET_TIME DATETIME NOT NULL COMMENT '投注时间',
  BET_NUM INT(11) NOT NULL COMMENT '投注注数',
  BET_DATA VARCHAR(128) NOT NULL COMMENT '投注号码,格式(1,2,3,4.4,3,2,1.5,7,8,9),每注之间用.分隔,每注中的号码用,分隔',
  BET_COINS FLOAT(10 , 4 ) NOT NULL DEFAULT '0.0000' COMMENT '投注金额',
  BONUS FLOAT(10 , 4 ) NOT NULL DEFAULT '0.0000' COMMENT '奖金',
  WIN_NO VARCHAR(128) COMMENT '开奖号码,格式(1,2,3,4)',
  MODE INT(2) NOT NULL DEFAULT '1' COMMENT '模式，1元 2角 3分 4厘',
  TIMES INT(11) NOT NULL DEFAULT '1' COMMENT '倍数',
  WIN_STATUS INT(2) NOT NULL DEFAULT '0' COMMENT '获奖状态 0未判断 1未中奖 2已中奖',
  STATUS INT(2) NOT NULL DEFAULT '0' COMMENT '状态 0正常 1撤单',
  AUTOBET_NO VARCHAR(32) DEFAULT '' COMMENT '追号编号，由后台生成',
  PRIMARY KEY (ID)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='投注表';



DROP TABLE IF EXISTS
TLT_BET_AUTO;

CREATE TABLE TLT_BET_AUTO (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  AUTOBET_NO VARCHAR(32) NOT NULL COMMENT '追号编号，由后台生成',
  USER_ID BIGINT(20) NOT NULL COMMENT '追号用户ID',
  LTYPE BIGINT(20) NOT NULL COMMENT '所属游戏，对应TLT_TYPE.LTYPE_ID',
  LPG_ID BIGINT(20) NOT NULL COMMENT '所属玩法组，对应TLT_PLAYGROUP.ID',
  LP_ID BIGINT(20) NOT NULL COMMENT '所属玩法，对应TLT_PLAY.ID',
  CREATE_TIME DATETIME NOT NULL COMMENT '追号时间',
  START_ISSUE VARCHAR(16) NOT NULL COMMENT '开始期号',
  ISSUE_NUM INT(11) NOT NULL DEFAULT '0' COMMENT '追号期数',
  COMPLETE_NUM INT(11) NOT NULL DEFAULT '0' COMMENT '完成期数',
  CANCEL_NUM INT(11) NOT NULL DEFAULT '0' COMMENT '取消期数',
  BET_NUM INT(11) NOT NULL DEFAULT '0' COMMENT '投注注数',
  BET_DATA VARCHAR(128) NOT NULL COMMENT '投注号码,格式(1,2,3,4.4,3,2,1.5,7,8,9),每注之间用.分隔,每注中的号码用,分隔',
  BET_COINS FLOAT(10 , 4 ) NOT NULL DEFAULT '0.0000' COMMENT '追号总金额',
  COMPLETE_COINS FLOAT(10 , 4 ) NOT NULL DEFAULT '0.0000' COMMENT '完成金额',
  CANCEL_COINS FLOAT(10 , 4 ) NOT NULL DEFAULT '0.0000' COMMENT '取消金额',
  MODE INT(2) NOT NULL DEFAULT '1' COMMENT '模式，1元 2角 3分 4厘',
  TIMES INT(11) NOT NULL DEFAULT '1' COMMENT '倍数',
  WIN_STOP INT(2) DEFAULT '0' COMMENT '是否中奖即停 0否 1是',
  STATUS INT(2) NOT NULL DEFAULT '0' COMMENT '追号状态 0进行中 1已完成 2已取消',
  BET_NO VARCHAR(32) DEFAULT NULL COMMENT '投注编号，由后台生成',
  PRIMARY KEY (ID)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='追号表';


DROP TABLE TLT_CORE_TICKET IF EXISTS;

CREATE TABLE TLT_CORE_TICKET
(
   LTYPE                VARCHAR(8) NOT NULL COMMENT '游戏代码',
   LNAME                VARCHAR(128) NOT NULL  COMMENT '投注玩法名称', 
   PLAYTYPE             VARCHAR(64) NOT NULL  COMMENT '投注玩法代号', 
   MERCHANTID           VARCHAR(64) NOT NULL COMMENT '商户编号',
   PERIOD               DECIMAL(24,0) NOT NULL COMMENT '期号',
   TICKNO               VARCHAR(64) NOT NULL COMMENT '票编码UUID',
   SERIALNUM            VARCHAR(64) COMMENT '彩票序列号,票编码-MD5(LTYPE+PLAYTYPE+MERCHANTID+USERID,UUID)',
   AMOUNT               NUMERIC(24,6) COMMENT '投注总金额',
   BOARDS               DECIMAL(4,0) NOT NULL COMMENT '总注数',
   CONTENT              VARCHAR(512) COMMENT '投注数据',
   MULTI                DECIMAL(3,0) NOT NULL COMMENT '投注倍数',

   CREATEDATE           DECIMAL(16,0) NOT NULL COMMENT '创建时间',
   VERSION              VARCHAR(16) COMMENT '版本号',
   PRINTTIME            DECIMAL(16,0) COMMENT '出票时间',
   WAGERSTATUS          DECIMAL(4,0) NOT NULL COMMENT '投注状态(1出票成功，2出票失败，3消票)',
   ISVALID              DECIMAL(1,0) DEFAULT 1 COMMENT '是否有效(0 无效状态,1有效状态)',
   NOTIFYSTATUS         NUMERIC(1,0) COMMENT '通知票状态(0 失败,1 成功)',
   REGION               VARCHAR(16) NOT NULL COMMENT '区域',
   IFNOTIFY             DECIMAL(1,0) COMMENT '是否已通知商户（暂时删掉）',
   FAILREASON           VARCHAR(64) COMMENT '失败原因',

   MERCHANTUSERID       VARCHAR(128) COMMENT '第三方用户ID',
   USERID               VARCHAR(128) COMMENT '本地用户编号',
   PRIMARY KEY (TICKNO)
);

CREATE INDEX INX_T_CORE_TO_LTYPE ON TGC_CORE_TICKET
(
   LTYPE
);

CREATE INDEX INX_T_CORE_TO_SERIALNUM ON TGC_CORE_TICKET
(
   SERIALNUM
);


CREATE INDEX INX_T_CORE_TO_USERID ON TGC_CORE_TICKET
(
   USERID
);


CREATE INDEX INX_T_CORE_TO_MERCHANTID ON TGC_CORE_TICKET
(
   MERCHANTID
);




