package onight.tfg.ordbgens.tlt.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="TLT_CORE_BET")
@AllArgsConstructor
@NoArgsConstructor
public class TLTCoreBet extends TLTCoreBetKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.TICK_NO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String tickNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.LTYPE
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String ltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.LNAME
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String lname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.PLAY_TYPE
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String playType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.MERCHANTID
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.SERIAL_NUM
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String serialNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.BET_AMOUNTS
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private BigDecimal betAmounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.BET_MULTI
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private Integer betMulti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.ISSUE_NO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String issueNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.BET_DATETIME
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private Date betDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.BET_DIV_CONTENT
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String betDivContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.BET_ORG_COUNTS
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private Integer betOrgCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.BET_ORG_CONTENT
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String betOrgContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.BET_IP
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String betIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.BET_MONEY_UNIT
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private Integer betMoneyUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.BONUS_MONEY_MODE
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private BigDecimal bonusMoneyMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.BONUS_RATE_MODE
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private BigDecimal bonusRateMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.VERSION
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.PRINT_TIME
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private Date printTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.BET_STATUS
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String betStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.NOTIFYSTATUS
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String notifystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.REGION
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.FAILREASON
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String failreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.MERCHANTUSERID
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String merchantuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.USER_ID
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.AUTOBET_NO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String autobetNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.IS_AUTO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String isAuto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.AUTO_REF_TICKNO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String autoRefTickno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.COST_FUND0
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private BigDecimal costFund0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.COST_FUND1
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private BigDecimal costFund1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.COST_FUND2
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private BigDecimal costFund2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.COST_FUND3
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private BigDecimal costFund3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.FUND_REF_ID
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String fundRefId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_BET.ISSUE_LOCK
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    private String issueLock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.TICK_NO
     *
     * @return the value of TLT_CORE_BET.TICK_NO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getTickNo() {
        return tickNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.TICK_NO
     *
     * @param tickNo the value for TLT_CORE_BET.TICK_NO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setTickNo(String tickNo) {
        this.tickNo = tickNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.LTYPE
     *
     * @return the value of TLT_CORE_BET.LTYPE
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getLtype() {
        return ltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.LTYPE
     *
     * @param ltype the value for TLT_CORE_BET.LTYPE
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setLtype(String ltype) {
        this.ltype = ltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.LNAME
     *
     * @return the value of TLT_CORE_BET.LNAME
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.LNAME
     *
     * @param lname the value for TLT_CORE_BET.LNAME
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setLname(String lname) {
        this.lname = lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.PLAY_TYPE
     *
     * @return the value of TLT_CORE_BET.PLAY_TYPE
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getPlayType() {
        return playType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.PLAY_TYPE
     *
     * @param playType the value for TLT_CORE_BET.PLAY_TYPE
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setPlayType(String playType) {
        this.playType = playType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.MERCHANTID
     *
     * @return the value of TLT_CORE_BET.MERCHANTID
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.MERCHANTID
     *
     * @param merchantid the value for TLT_CORE_BET.MERCHANTID
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.SERIAL_NUM
     *
     * @return the value of TLT_CORE_BET.SERIAL_NUM
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getSerialNum() {
        return serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.SERIAL_NUM
     *
     * @param serialNum the value for TLT_CORE_BET.SERIAL_NUM
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setSerialNum(String serialNum) {
        this.serialNum = serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.BET_AMOUNTS
     *
     * @return the value of TLT_CORE_BET.BET_AMOUNTS
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public BigDecimal getBetAmounts() {
        return betAmounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.BET_AMOUNTS
     *
     * @param betAmounts the value for TLT_CORE_BET.BET_AMOUNTS
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setBetAmounts(BigDecimal betAmounts) {
        this.betAmounts = betAmounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.BET_MULTI
     *
     * @return the value of TLT_CORE_BET.BET_MULTI
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public Integer getBetMulti() {
        return betMulti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.BET_MULTI
     *
     * @param betMulti the value for TLT_CORE_BET.BET_MULTI
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setBetMulti(Integer betMulti) {
        this.betMulti = betMulti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.ISSUE_NO
     *
     * @return the value of TLT_CORE_BET.ISSUE_NO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getIssueNo() {
        return issueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.ISSUE_NO
     *
     * @param issueNo the value for TLT_CORE_BET.ISSUE_NO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setIssueNo(String issueNo) {
        this.issueNo = issueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.BET_DATETIME
     *
     * @return the value of TLT_CORE_BET.BET_DATETIME
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public Date getBetDatetime() {
        return betDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.BET_DATETIME
     *
     * @param betDatetime the value for TLT_CORE_BET.BET_DATETIME
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setBetDatetime(Date betDatetime) {
        this.betDatetime = betDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.BET_DIV_CONTENT
     *
     * @return the value of TLT_CORE_BET.BET_DIV_CONTENT
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getBetDivContent() {
        return betDivContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.BET_DIV_CONTENT
     *
     * @param betDivContent the value for TLT_CORE_BET.BET_DIV_CONTENT
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setBetDivContent(String betDivContent) {
        this.betDivContent = betDivContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.BET_ORG_COUNTS
     *
     * @return the value of TLT_CORE_BET.BET_ORG_COUNTS
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public Integer getBetOrgCounts() {
        return betOrgCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.BET_ORG_COUNTS
     *
     * @param betOrgCounts the value for TLT_CORE_BET.BET_ORG_COUNTS
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setBetOrgCounts(Integer betOrgCounts) {
        this.betOrgCounts = betOrgCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.BET_ORG_CONTENT
     *
     * @return the value of TLT_CORE_BET.BET_ORG_CONTENT
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getBetOrgContent() {
        return betOrgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.BET_ORG_CONTENT
     *
     * @param betOrgContent the value for TLT_CORE_BET.BET_ORG_CONTENT
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setBetOrgContent(String betOrgContent) {
        this.betOrgContent = betOrgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.BET_IP
     *
     * @return the value of TLT_CORE_BET.BET_IP
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getBetIp() {
        return betIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.BET_IP
     *
     * @param betIp the value for TLT_CORE_BET.BET_IP
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setBetIp(String betIp) {
        this.betIp = betIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.BET_MONEY_UNIT
     *
     * @return the value of TLT_CORE_BET.BET_MONEY_UNIT
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public Integer getBetMoneyUnit() {
        return betMoneyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.BET_MONEY_UNIT
     *
     * @param betMoneyUnit the value for TLT_CORE_BET.BET_MONEY_UNIT
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setBetMoneyUnit(Integer betMoneyUnit) {
        this.betMoneyUnit = betMoneyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.BONUS_MONEY_MODE
     *
     * @return the value of TLT_CORE_BET.BONUS_MONEY_MODE
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public BigDecimal getBonusMoneyMode() {
        return bonusMoneyMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.BONUS_MONEY_MODE
     *
     * @param bonusMoneyMode the value for TLT_CORE_BET.BONUS_MONEY_MODE
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setBonusMoneyMode(BigDecimal bonusMoneyMode) {
        this.bonusMoneyMode = bonusMoneyMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.BONUS_RATE_MODE
     *
     * @return the value of TLT_CORE_BET.BONUS_RATE_MODE
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public BigDecimal getBonusRateMode() {
        return bonusRateMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.BONUS_RATE_MODE
     *
     * @param bonusRateMode the value for TLT_CORE_BET.BONUS_RATE_MODE
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setBonusRateMode(BigDecimal bonusRateMode) {
        this.bonusRateMode = bonusRateMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.VERSION
     *
     * @return the value of TLT_CORE_BET.VERSION
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.VERSION
     *
     * @param version the value for TLT_CORE_BET.VERSION
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.PRINT_TIME
     *
     * @return the value of TLT_CORE_BET.PRINT_TIME
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public Date getPrintTime() {
        return printTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.PRINT_TIME
     *
     * @param printTime the value for TLT_CORE_BET.PRINT_TIME
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setPrintTime(Date printTime) {
        this.printTime = printTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.BET_STATUS
     *
     * @return the value of TLT_CORE_BET.BET_STATUS
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getBetStatus() {
        return betStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.BET_STATUS
     *
     * @param betStatus the value for TLT_CORE_BET.BET_STATUS
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setBetStatus(String betStatus) {
        this.betStatus = betStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.NOTIFYSTATUS
     *
     * @return the value of TLT_CORE_BET.NOTIFYSTATUS
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getNotifystatus() {
        return notifystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.NOTIFYSTATUS
     *
     * @param notifystatus the value for TLT_CORE_BET.NOTIFYSTATUS
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setNotifystatus(String notifystatus) {
        this.notifystatus = notifystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.REGION
     *
     * @return the value of TLT_CORE_BET.REGION
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.REGION
     *
     * @param region the value for TLT_CORE_BET.REGION
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.FAILREASON
     *
     * @return the value of TLT_CORE_BET.FAILREASON
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getFailreason() {
        return failreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.FAILREASON
     *
     * @param failreason the value for TLT_CORE_BET.FAILREASON
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setFailreason(String failreason) {
        this.failreason = failreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.MERCHANTUSERID
     *
     * @return the value of TLT_CORE_BET.MERCHANTUSERID
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getMerchantuserid() {
        return merchantuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.MERCHANTUSERID
     *
     * @param merchantuserid the value for TLT_CORE_BET.MERCHANTUSERID
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setMerchantuserid(String merchantuserid) {
        this.merchantuserid = merchantuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.USER_ID
     *
     * @return the value of TLT_CORE_BET.USER_ID
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.USER_ID
     *
     * @param userId the value for TLT_CORE_BET.USER_ID
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.AUTOBET_NO
     *
     * @return the value of TLT_CORE_BET.AUTOBET_NO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getAutobetNo() {
        return autobetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.AUTOBET_NO
     *
     * @param autobetNo the value for TLT_CORE_BET.AUTOBET_NO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setAutobetNo(String autobetNo) {
        this.autobetNo = autobetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.IS_AUTO
     *
     * @return the value of TLT_CORE_BET.IS_AUTO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getIsAuto() {
        return isAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.IS_AUTO
     *
     * @param isAuto the value for TLT_CORE_BET.IS_AUTO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setIsAuto(String isAuto) {
        this.isAuto = isAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.AUTO_REF_TICKNO
     *
     * @return the value of TLT_CORE_BET.AUTO_REF_TICKNO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getAutoRefTickno() {
        return autoRefTickno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.AUTO_REF_TICKNO
     *
     * @param autoRefTickno the value for TLT_CORE_BET.AUTO_REF_TICKNO
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setAutoRefTickno(String autoRefTickno) {
        this.autoRefTickno = autoRefTickno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.COST_FUND0
     *
     * @return the value of TLT_CORE_BET.COST_FUND0
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public BigDecimal getCostFund0() {
        return costFund0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.COST_FUND0
     *
     * @param costFund0 the value for TLT_CORE_BET.COST_FUND0
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setCostFund0(BigDecimal costFund0) {
        this.costFund0 = costFund0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.COST_FUND1
     *
     * @return the value of TLT_CORE_BET.COST_FUND1
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public BigDecimal getCostFund1() {
        return costFund1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.COST_FUND1
     *
     * @param costFund1 the value for TLT_CORE_BET.COST_FUND1
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setCostFund1(BigDecimal costFund1) {
        this.costFund1 = costFund1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.COST_FUND2
     *
     * @return the value of TLT_CORE_BET.COST_FUND2
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public BigDecimal getCostFund2() {
        return costFund2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.COST_FUND2
     *
     * @param costFund2 the value for TLT_CORE_BET.COST_FUND2
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setCostFund2(BigDecimal costFund2) {
        this.costFund2 = costFund2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.COST_FUND3
     *
     * @return the value of TLT_CORE_BET.COST_FUND3
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public BigDecimal getCostFund3() {
        return costFund3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.COST_FUND3
     *
     * @param costFund3 the value for TLT_CORE_BET.COST_FUND3
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setCostFund3(BigDecimal costFund3) {
        this.costFund3 = costFund3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.FUND_REF_ID
     *
     * @return the value of TLT_CORE_BET.FUND_REF_ID
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getFundRefId() {
        return fundRefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.FUND_REF_ID
     *
     * @param fundRefId the value for TLT_CORE_BET.FUND_REF_ID
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setFundRefId(String fundRefId) {
        this.fundRefId = fundRefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_BET.ISSUE_LOCK
     *
     * @return the value of TLT_CORE_BET.ISSUE_LOCK
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public String getIssueLock() {
        return issueLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_BET.ISSUE_LOCK
     *
     * @param issueLock the value for TLT_CORE_BET.ISSUE_LOCK
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    public void setIssueLock(String issueLock) {
        this.issueLock = issueLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TLTCoreBet other = (TLTCoreBet) that;
        return (this.getBetNo() == null ? other.getBetNo() == null : this.getBetNo().equals(other.getBetNo()))
            && (this.getTickNo() == null ? other.getTickNo() == null : this.getTickNo().equals(other.getTickNo()))
            && (this.getLtype() == null ? other.getLtype() == null : this.getLtype().equals(other.getLtype()))
            && (this.getLname() == null ? other.getLname() == null : this.getLname().equals(other.getLname()))
            && (this.getPlayType() == null ? other.getPlayType() == null : this.getPlayType().equals(other.getPlayType()))
            && (this.getMerchantid() == null ? other.getMerchantid() == null : this.getMerchantid().equals(other.getMerchantid()))
            && (this.getSerialNum() == null ? other.getSerialNum() == null : this.getSerialNum().equals(other.getSerialNum()))
            && (this.getBetAmounts() == null ? other.getBetAmounts() == null : this.getBetAmounts().equals(other.getBetAmounts()))
            && (this.getBetMulti() == null ? other.getBetMulti() == null : this.getBetMulti().equals(other.getBetMulti()))
            && (this.getIssueNo() == null ? other.getIssueNo() == null : this.getIssueNo().equals(other.getIssueNo()))
            && (this.getBetDatetime() == null ? other.getBetDatetime() == null : this.getBetDatetime().equals(other.getBetDatetime()))
            && (this.getBetDivContent() == null ? other.getBetDivContent() == null : this.getBetDivContent().equals(other.getBetDivContent()))
            && (this.getBetOrgCounts() == null ? other.getBetOrgCounts() == null : this.getBetOrgCounts().equals(other.getBetOrgCounts()))
            && (this.getBetOrgContent() == null ? other.getBetOrgContent() == null : this.getBetOrgContent().equals(other.getBetOrgContent()))
            && (this.getBetIp() == null ? other.getBetIp() == null : this.getBetIp().equals(other.getBetIp()))
            && (this.getBetMoneyUnit() == null ? other.getBetMoneyUnit() == null : this.getBetMoneyUnit().equals(other.getBetMoneyUnit()))
            && (this.getBonusMoneyMode() == null ? other.getBonusMoneyMode() == null : this.getBonusMoneyMode().equals(other.getBonusMoneyMode()))
            && (this.getBonusRateMode() == null ? other.getBonusRateMode() == null : this.getBonusRateMode().equals(other.getBonusRateMode()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getPrintTime() == null ? other.getPrintTime() == null : this.getPrintTime().equals(other.getPrintTime()))
            && (this.getBetStatus() == null ? other.getBetStatus() == null : this.getBetStatus().equals(other.getBetStatus()))
            && (this.getNotifystatus() == null ? other.getNotifystatus() == null : this.getNotifystatus().equals(other.getNotifystatus()))
            && (this.getRegion() == null ? other.getRegion() == null : this.getRegion().equals(other.getRegion()))
            && (this.getFailreason() == null ? other.getFailreason() == null : this.getFailreason().equals(other.getFailreason()))
            && (this.getMerchantuserid() == null ? other.getMerchantuserid() == null : this.getMerchantuserid().equals(other.getMerchantuserid()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getAutobetNo() == null ? other.getAutobetNo() == null : this.getAutobetNo().equals(other.getAutobetNo()))
            && (this.getIsAuto() == null ? other.getIsAuto() == null : this.getIsAuto().equals(other.getIsAuto()))
            && (this.getAutoRefTickno() == null ? other.getAutoRefTickno() == null : this.getAutoRefTickno().equals(other.getAutoRefTickno()))
            && (this.getCostFund0() == null ? other.getCostFund0() == null : this.getCostFund0().equals(other.getCostFund0()))
            && (this.getCostFund1() == null ? other.getCostFund1() == null : this.getCostFund1().equals(other.getCostFund1()))
            && (this.getCostFund2() == null ? other.getCostFund2() == null : this.getCostFund2().equals(other.getCostFund2()))
            && (this.getCostFund3() == null ? other.getCostFund3() == null : this.getCostFund3().equals(other.getCostFund3()))
            && (this.getFundRefId() == null ? other.getFundRefId() == null : this.getFundRefId().equals(other.getFundRefId()))
            && (this.getIssueLock() == null ? other.getIssueLock() == null : this.getIssueLock().equals(other.getIssueLock()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBetNo() == null) ? 0 : getBetNo().hashCode());
        result = prime * result + ((getTickNo() == null) ? 0 : getTickNo().hashCode());
        result = prime * result + ((getLtype() == null) ? 0 : getLtype().hashCode());
        result = prime * result + ((getLname() == null) ? 0 : getLname().hashCode());
        result = prime * result + ((getPlayType() == null) ? 0 : getPlayType().hashCode());
        result = prime * result + ((getMerchantid() == null) ? 0 : getMerchantid().hashCode());
        result = prime * result + ((getSerialNum() == null) ? 0 : getSerialNum().hashCode());
        result = prime * result + ((getBetAmounts() == null) ? 0 : getBetAmounts().hashCode());
        result = prime * result + ((getBetMulti() == null) ? 0 : getBetMulti().hashCode());
        result = prime * result + ((getIssueNo() == null) ? 0 : getIssueNo().hashCode());
        result = prime * result + ((getBetDatetime() == null) ? 0 : getBetDatetime().hashCode());
        result = prime * result + ((getBetDivContent() == null) ? 0 : getBetDivContent().hashCode());
        result = prime * result + ((getBetOrgCounts() == null) ? 0 : getBetOrgCounts().hashCode());
        result = prime * result + ((getBetOrgContent() == null) ? 0 : getBetOrgContent().hashCode());
        result = prime * result + ((getBetIp() == null) ? 0 : getBetIp().hashCode());
        result = prime * result + ((getBetMoneyUnit() == null) ? 0 : getBetMoneyUnit().hashCode());
        result = prime * result + ((getBonusMoneyMode() == null) ? 0 : getBonusMoneyMode().hashCode());
        result = prime * result + ((getBonusRateMode() == null) ? 0 : getBonusRateMode().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getPrintTime() == null) ? 0 : getPrintTime().hashCode());
        result = prime * result + ((getBetStatus() == null) ? 0 : getBetStatus().hashCode());
        result = prime * result + ((getNotifystatus() == null) ? 0 : getNotifystatus().hashCode());
        result = prime * result + ((getRegion() == null) ? 0 : getRegion().hashCode());
        result = prime * result + ((getFailreason() == null) ? 0 : getFailreason().hashCode());
        result = prime * result + ((getMerchantuserid() == null) ? 0 : getMerchantuserid().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAutobetNo() == null) ? 0 : getAutobetNo().hashCode());
        result = prime * result + ((getIsAuto() == null) ? 0 : getIsAuto().hashCode());
        result = prime * result + ((getAutoRefTickno() == null) ? 0 : getAutoRefTickno().hashCode());
        result = prime * result + ((getCostFund0() == null) ? 0 : getCostFund0().hashCode());
        result = prime * result + ((getCostFund1() == null) ? 0 : getCostFund1().hashCode());
        result = prime * result + ((getCostFund2() == null) ? 0 : getCostFund2().hashCode());
        result = prime * result + ((getCostFund3() == null) ? 0 : getCostFund3().hashCode());
        result = prime * result + ((getFundRefId() == null) ? 0 : getFundRefId().hashCode());
        result = prime * result + ((getIssueLock() == null) ? 0 : getIssueLock().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 14 00:28:11 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tickNo=").append(tickNo);
        sb.append(", ltype=").append(ltype);
        sb.append(", lname=").append(lname);
        sb.append(", playType=").append(playType);
        sb.append(", merchantid=").append(merchantid);
        sb.append(", serialNum=").append(serialNum);
        sb.append(", betAmounts=").append(betAmounts);
        sb.append(", betMulti=").append(betMulti);
        sb.append(", issueNo=").append(issueNo);
        sb.append(", betDatetime=").append(betDatetime);
        sb.append(", betDivContent=").append(betDivContent);
        sb.append(", betOrgCounts=").append(betOrgCounts);
        sb.append(", betOrgContent=").append(betOrgContent);
        sb.append(", betIp=").append(betIp);
        sb.append(", betMoneyUnit=").append(betMoneyUnit);
        sb.append(", bonusMoneyMode=").append(bonusMoneyMode);
        sb.append(", bonusRateMode=").append(bonusRateMode);
        sb.append(", version=").append(version);
        sb.append(", printTime=").append(printTime);
        sb.append(", betStatus=").append(betStatus);
        sb.append(", notifystatus=").append(notifystatus);
        sb.append(", region=").append(region);
        sb.append(", failreason=").append(failreason);
        sb.append(", merchantuserid=").append(merchantuserid);
        sb.append(", userId=").append(userId);
        sb.append(", autobetNo=").append(autobetNo);
        sb.append(", isAuto=").append(isAuto);
        sb.append(", autoRefTickno=").append(autoRefTickno);
        sb.append(", costFund0=").append(costFund0);
        sb.append(", costFund1=").append(costFund1);
        sb.append(", costFund2=").append(costFund2);
        sb.append(", costFund3=").append(costFund3);
        sb.append(", fundRefId=").append(fundRefId);
        sb.append(", issueLock=").append(issueLock);
        sb.append("]");
        return sb.toString();
    }
}