package onight.tfw.rest.db.ext;

import java.util.List;
import java.util.Map;

import lombok.Data;
import onight.tfg.ordbgens.sys.entity.TSysAction;

import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface EXSysActionMapper {
	
	@Data
	public class ActionCount {
		String actionCount;
	}

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated Wed Mar 25 19:58:40 CST 2015
     */
    @Select({
    	"SELECT COUNT(1) ACTION_COUNT FROM T_SYS_USER_ROLE A,T_SYS_ROLE_ACTION B,T_SYS_ACTION C",
    	"WHERE A.ROLE_ID = B.ROLE_ID",
    	"AND B.ACTION_ID = C.ACTION_ID",
    	"AND A.USER_ID=#{userId,jdbcType=VARCHAR}",
    	"AND C.ACTION_FLAG=#{actionFlag,jdbcType=VARCHAR}"
    })
    @Results({
		@Result(column = "ACTION_COUNT", property = "actionCount", jdbcType = JdbcType.VARCHAR)
    })
    List<ActionCount> selectActionCount(Map<String,String> map);
    
    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated Wed Mar 25 19:58:40 CST 2015
     */
    @Select({
    	"SELECT MENU_ID ACTION_ID,'' ACTION_FLAG,MENU_NAME ACTION_NAME,MENU_DESC ACTION_DESC,0 ACTION_MENU,MENU_NAME FIELD1 FROM T_SYS_MENU UNION SELECT * FROM T_SYS_ACTION"
    })
    @Results({
		@Result(column = "ACTION_ID", property = "actionId", jdbcType = JdbcType.VARCHAR),
		@Result(column = "ACTION_FLAG", property = "actionFlag", jdbcType = JdbcType.VARCHAR),
		@Result(column = "ACTION_NAME", property = "actionName", jdbcType = JdbcType.VARCHAR),
		@Result(column = "ACTION_DESC", property = "actionDesc", jdbcType = JdbcType.VARCHAR),
		@Result(column = "ACTION_MENU", property = "actionMenu", jdbcType = JdbcType.INTEGER),
		@Result(column = "FIELD1", property = "field1", jdbcType = JdbcType.VARCHAR)
    })
    List<TSysAction> selectActionList();
    
}
