package onight.tfg.ordbgens.tlt.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
public class TLTCoreWinKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_CORE_WIN.WIN_NO
     *
     * @mbggenerated Fri Apr 15 18:05:33 CST 2016
     */
    private String winNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_CORE_WIN.WIN_NO
     *
     * @return the value of TLT_CORE_WIN.WIN_NO
     *
     * @mbggenerated Fri Apr 15 18:05:33 CST 2016
     */
    public String getWinNo() {
        return winNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_CORE_WIN.WIN_NO
     *
     * @param winNo the value for TLT_CORE_WIN.WIN_NO
     *
     * @mbggenerated Fri Apr 15 18:05:33 CST 2016
     */
    public void setWinNo(String winNo) {
        this.winNo = winNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_WIN
     *
     * @mbggenerated Fri Apr 15 18:05:33 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TLTCoreWinKey other = (TLTCoreWinKey) that;
        return (this.getWinNo() == null ? other.getWinNo() == null : this.getWinNo().equals(other.getWinNo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_WIN
     *
     * @mbggenerated Fri Apr 15 18:05:33 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getWinNo() == null) ? 0 : getWinNo().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_WIN
     *
     * @mbggenerated Fri Apr 15 18:05:33 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", winNo=").append(winNo);
        sb.append("]");
        return sb.toString();
    }
}