package starstart.cgame.flows.mysqlgens.trade.entity;

import cn.msec.ojpa.api.annotations.Tab;

import java.math.BigDecimal;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_ACCS_101")
@AllArgsConstructor
@NoArgsConstructor
public class Accs101 extends Accs101Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String actName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String actType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.CERT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.CERT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.CATALOG
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String catalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String mchntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.UP_ACT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String upActNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.SYB_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String sybType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_YT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String actYt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.PROD_MCHNT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String prodMchntNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_YINIT_BAL
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private BigDecimal actYinitBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_DINIT_BAL
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private BigDecimal actDinitBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_TOLD_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private BigDecimal actToldAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_TOLC_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private BigDecimal actTolcAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_YTOLD_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private BigDecimal actYtoldAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_YTOLC_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private BigDecimal actYtolcAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_CUR_BAL
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private BigDecimal actCurBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_STAT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String actStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_MAXOD_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private BigDecimal actMaxodAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_CTRL_BAL
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private BigDecimal actCtrlBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.ACT_BAL_WARN_FLAG
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private String actBalWarnFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCS_101.UPD_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    private Date updTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_NAME
     *
     * @return the value of T_ACCS_101.ACT_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getActName() {
        return actName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_NAME
     *
     * @param actName the value for T_ACCS_101.ACT_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActName(String actName) {
        this.actName = actName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_TYPE
     *
     * @return the value of T_ACCS_101.ACT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getActType() {
        return actType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_TYPE
     *
     * @param actType the value for T_ACCS_101.ACT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActType(String actType) {
        this.actType = actType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.CERT_TYPE
     *
     * @return the value of T_ACCS_101.CERT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.CERT_TYPE
     *
     * @param certType the value for T_ACCS_101.CERT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setCertType(String certType) {
        this.certType = certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.CERT_NO
     *
     * @return the value of T_ACCS_101.CERT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.CERT_NO
     *
     * @param certNo the value for T_ACCS_101.CERT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.CATALOG
     *
     * @return the value of T_ACCS_101.CATALOG
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.CATALOG
     *
     * @param catalog the value for T_ACCS_101.CATALOG
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.MCHNT_ID
     *
     * @return the value of T_ACCS_101.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getMchntId() {
        return mchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.MCHNT_ID
     *
     * @param mchntId the value for T_ACCS_101.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setMchntId(String mchntId) {
        this.mchntId = mchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.UP_ACT_NO
     *
     * @return the value of T_ACCS_101.UP_ACT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getUpActNo() {
        return upActNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.UP_ACT_NO
     *
     * @param upActNo the value for T_ACCS_101.UP_ACT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setUpActNo(String upActNo) {
        this.upActNo = upActNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.SYB_TYPE
     *
     * @return the value of T_ACCS_101.SYB_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getSybType() {
        return sybType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.SYB_TYPE
     *
     * @param sybType the value for T_ACCS_101.SYB_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setSybType(String sybType) {
        this.sybType = sybType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_YT
     *
     * @return the value of T_ACCS_101.ACT_YT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getActYt() {
        return actYt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_YT
     *
     * @param actYt the value for T_ACCS_101.ACT_YT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActYt(String actYt) {
        this.actYt = actYt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.PROD_MCHNT_NO
     *
     * @return the value of T_ACCS_101.PROD_MCHNT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getProdMchntNo() {
        return prodMchntNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.PROD_MCHNT_NO
     *
     * @param prodMchntNo the value for T_ACCS_101.PROD_MCHNT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setProdMchntNo(String prodMchntNo) {
        this.prodMchntNo = prodMchntNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.PROD_ID
     *
     * @return the value of T_ACCS_101.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.PROD_ID
     *
     * @param prodId the value for T_ACCS_101.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setProdId(String prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_YINIT_BAL
     *
     * @return the value of T_ACCS_101.ACT_YINIT_BAL
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public BigDecimal getActYinitBal() {
        return actYinitBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_YINIT_BAL
     *
     * @param actYinitBal the value for T_ACCS_101.ACT_YINIT_BAL
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActYinitBal(BigDecimal actYinitBal) {
        this.actYinitBal = actYinitBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_DINIT_BAL
     *
     * @return the value of T_ACCS_101.ACT_DINIT_BAL
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public BigDecimal getActDinitBal() {
        return actDinitBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_DINIT_BAL
     *
     * @param actDinitBal the value for T_ACCS_101.ACT_DINIT_BAL
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActDinitBal(BigDecimal actDinitBal) {
        this.actDinitBal = actDinitBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_TOLD_AMT
     *
     * @return the value of T_ACCS_101.ACT_TOLD_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public BigDecimal getActToldAmt() {
        return actToldAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_TOLD_AMT
     *
     * @param actToldAmt the value for T_ACCS_101.ACT_TOLD_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActToldAmt(BigDecimal actToldAmt) {
        this.actToldAmt = actToldAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_TOLC_AMT
     *
     * @return the value of T_ACCS_101.ACT_TOLC_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public BigDecimal getActTolcAmt() {
        return actTolcAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_TOLC_AMT
     *
     * @param actTolcAmt the value for T_ACCS_101.ACT_TOLC_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActTolcAmt(BigDecimal actTolcAmt) {
        this.actTolcAmt = actTolcAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_YTOLD_AMT
     *
     * @return the value of T_ACCS_101.ACT_YTOLD_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public BigDecimal getActYtoldAmt() {
        return actYtoldAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_YTOLD_AMT
     *
     * @param actYtoldAmt the value for T_ACCS_101.ACT_YTOLD_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActYtoldAmt(BigDecimal actYtoldAmt) {
        this.actYtoldAmt = actYtoldAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_YTOLC_AMT
     *
     * @return the value of T_ACCS_101.ACT_YTOLC_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public BigDecimal getActYtolcAmt() {
        return actYtolcAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_YTOLC_AMT
     *
     * @param actYtolcAmt the value for T_ACCS_101.ACT_YTOLC_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActYtolcAmt(BigDecimal actYtolcAmt) {
        this.actYtolcAmt = actYtolcAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_CUR_BAL
     *
     * @return the value of T_ACCS_101.ACT_CUR_BAL
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public BigDecimal getActCurBal() {
        return actCurBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_CUR_BAL
     *
     * @param actCurBal the value for T_ACCS_101.ACT_CUR_BAL
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActCurBal(BigDecimal actCurBal) {
        this.actCurBal = actCurBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_STAT
     *
     * @return the value of T_ACCS_101.ACT_STAT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getActStat() {
        return actStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_STAT
     *
     * @param actStat the value for T_ACCS_101.ACT_STAT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActStat(String actStat) {
        this.actStat = actStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_MAXOD_AMT
     *
     * @return the value of T_ACCS_101.ACT_MAXOD_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public BigDecimal getActMaxodAmt() {
        return actMaxodAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_MAXOD_AMT
     *
     * @param actMaxodAmt the value for T_ACCS_101.ACT_MAXOD_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActMaxodAmt(BigDecimal actMaxodAmt) {
        this.actMaxodAmt = actMaxodAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_CTRL_BAL
     *
     * @return the value of T_ACCS_101.ACT_CTRL_BAL
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public BigDecimal getActCtrlBal() {
        return actCtrlBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_CTRL_BAL
     *
     * @param actCtrlBal the value for T_ACCS_101.ACT_CTRL_BAL
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActCtrlBal(BigDecimal actCtrlBal) {
        this.actCtrlBal = actCtrlBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.ACT_BAL_WARN_FLAG
     *
     * @return the value of T_ACCS_101.ACT_BAL_WARN_FLAG
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public String getActBalWarnFlag() {
        return actBalWarnFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.ACT_BAL_WARN_FLAG
     *
     * @param actBalWarnFlag the value for T_ACCS_101.ACT_BAL_WARN_FLAG
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setActBalWarnFlag(String actBalWarnFlag) {
        this.actBalWarnFlag = actBalWarnFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCS_101.UPD_TIME
     *
     * @return the value of T_ACCS_101.UPD_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCS_101.UPD_TIME
     *
     * @param updTime the value for T_ACCS_101.UPD_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCS_101
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Accs101 other = (Accs101) that;
        return (this.getActNo() == null ? other.getActNo() == null : this.getActNo().equals(other.getActNo()))
            && (this.getActName() == null ? other.getActName() == null : this.getActName().equals(other.getActName()))
            && (this.getActType() == null ? other.getActType() == null : this.getActType().equals(other.getActType()))
            && (this.getCertType() == null ? other.getCertType() == null : this.getCertType().equals(other.getCertType()))
            && (this.getCertNo() == null ? other.getCertNo() == null : this.getCertNo().equals(other.getCertNo()))
            && (this.getCatalog() == null ? other.getCatalog() == null : this.getCatalog().equals(other.getCatalog()))
            && (this.getMchntId() == null ? other.getMchntId() == null : this.getMchntId().equals(other.getMchntId()))
            && (this.getUpActNo() == null ? other.getUpActNo() == null : this.getUpActNo().equals(other.getUpActNo()))
            && (this.getSybType() == null ? other.getSybType() == null : this.getSybType().equals(other.getSybType()))
            && (this.getActYt() == null ? other.getActYt() == null : this.getActYt().equals(other.getActYt()))
            && (this.getProdMchntNo() == null ? other.getProdMchntNo() == null : this.getProdMchntNo().equals(other.getProdMchntNo()))
            && (this.getProdId() == null ? other.getProdId() == null : this.getProdId().equals(other.getProdId()))
            && (this.getActYinitBal() == null ? other.getActYinitBal() == null : this.getActYinitBal().equals(other.getActYinitBal()))
            && (this.getActDinitBal() == null ? other.getActDinitBal() == null : this.getActDinitBal().equals(other.getActDinitBal()))
            && (this.getActToldAmt() == null ? other.getActToldAmt() == null : this.getActToldAmt().equals(other.getActToldAmt()))
            && (this.getActTolcAmt() == null ? other.getActTolcAmt() == null : this.getActTolcAmt().equals(other.getActTolcAmt()))
            && (this.getActYtoldAmt() == null ? other.getActYtoldAmt() == null : this.getActYtoldAmt().equals(other.getActYtoldAmt()))
            && (this.getActYtolcAmt() == null ? other.getActYtolcAmt() == null : this.getActYtolcAmt().equals(other.getActYtolcAmt()))
            && (this.getActCurBal() == null ? other.getActCurBal() == null : this.getActCurBal().equals(other.getActCurBal()))
            && (this.getActStat() == null ? other.getActStat() == null : this.getActStat().equals(other.getActStat()))
            && (this.getActMaxodAmt() == null ? other.getActMaxodAmt() == null : this.getActMaxodAmt().equals(other.getActMaxodAmt()))
            && (this.getActCtrlBal() == null ? other.getActCtrlBal() == null : this.getActCtrlBal().equals(other.getActCtrlBal()))
            && (this.getActBalWarnFlag() == null ? other.getActBalWarnFlag() == null : this.getActBalWarnFlag().equals(other.getActBalWarnFlag()))
            && (this.getUpdTime() == null ? other.getUpdTime() == null : this.getUpdTime().equals(other.getUpdTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCS_101
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getActNo() == null) ? 0 : getActNo().hashCode());
        result = prime * result + ((getActName() == null) ? 0 : getActName().hashCode());
        result = prime * result + ((getActType() == null) ? 0 : getActType().hashCode());
        result = prime * result + ((getCertType() == null) ? 0 : getCertType().hashCode());
        result = prime * result + ((getCertNo() == null) ? 0 : getCertNo().hashCode());
        result = prime * result + ((getCatalog() == null) ? 0 : getCatalog().hashCode());
        result = prime * result + ((getMchntId() == null) ? 0 : getMchntId().hashCode());
        result = prime * result + ((getUpActNo() == null) ? 0 : getUpActNo().hashCode());
        result = prime * result + ((getSybType() == null) ? 0 : getSybType().hashCode());
        result = prime * result + ((getActYt() == null) ? 0 : getActYt().hashCode());
        result = prime * result + ((getProdMchntNo() == null) ? 0 : getProdMchntNo().hashCode());
        result = prime * result + ((getProdId() == null) ? 0 : getProdId().hashCode());
        result = prime * result + ((getActYinitBal() == null) ? 0 : getActYinitBal().hashCode());
        result = prime * result + ((getActDinitBal() == null) ? 0 : getActDinitBal().hashCode());
        result = prime * result + ((getActToldAmt() == null) ? 0 : getActToldAmt().hashCode());
        result = prime * result + ((getActTolcAmt() == null) ? 0 : getActTolcAmt().hashCode());
        result = prime * result + ((getActYtoldAmt() == null) ? 0 : getActYtoldAmt().hashCode());
        result = prime * result + ((getActYtolcAmt() == null) ? 0 : getActYtolcAmt().hashCode());
        result = prime * result + ((getActCurBal() == null) ? 0 : getActCurBal().hashCode());
        result = prime * result + ((getActStat() == null) ? 0 : getActStat().hashCode());
        result = prime * result + ((getActMaxodAmt() == null) ? 0 : getActMaxodAmt().hashCode());
        result = prime * result + ((getActCtrlBal() == null) ? 0 : getActCtrlBal().hashCode());
        result = prime * result + ((getActBalWarnFlag() == null) ? 0 : getActBalWarnFlag().hashCode());
        result = prime * result + ((getUpdTime() == null) ? 0 : getUpdTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCS_101
     *
     * @mbggenerated Mon Jun 08 20:40:14 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", actName=").append(actName);
        sb.append(", actType=").append(actType);
        sb.append(", certType=").append(certType);
        sb.append(", certNo=").append(certNo);
        sb.append(", catalog=").append(catalog);
        sb.append(", mchntId=").append(mchntId);
        sb.append(", upActNo=").append(upActNo);
        sb.append(", sybType=").append(sybType);
        sb.append(", actYt=").append(actYt);
        sb.append(", prodMchntNo=").append(prodMchntNo);
        sb.append(", prodId=").append(prodId);
        sb.append(", actYinitBal=").append(actYinitBal);
        sb.append(", actDinitBal=").append(actDinitBal);
        sb.append(", actToldAmt=").append(actToldAmt);
        sb.append(", actTolcAmt=").append(actTolcAmt);
        sb.append(", actYtoldAmt=").append(actYtoldAmt);
        sb.append(", actYtolcAmt=").append(actYtolcAmt);
        sb.append(", actCurBal=").append(actCurBal);
        sb.append(", actStat=").append(actStat);
        sb.append(", actMaxodAmt=").append(actMaxodAmt);
        sb.append(", actCtrlBal=").append(actCtrlBal);
        sb.append(", actBalWarnFlag=").append(actBalWarnFlag);
        sb.append(", updTime=").append(updTime);
        sb.append("]");
        return sb.toString();
    }
}