package starstart.cgame.flows.mysqlgens.trade.entity;

import cn.msec.ojpa.api.annotations.Tab;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_FRONT_DIGACCT_INF")
@AllArgsConstructor
@NoArgsConstructor
public class FrontDigacctInf extends FrontDigacctInfKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.MCHNT_RECORD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String mchntRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.PROD_RECORD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String prodRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.TRANS_REQ_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private Date transReqTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.AC_STATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String acState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.LAND_ACCT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String landAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.LAND_CUST_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String landCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.ACCT_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String acctName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.CURRENCY
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.LAND_MCHT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String landMchtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.CUST_CH_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String custChName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.CUST_EN_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String custEnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.CERT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.CERT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.TEL_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String telNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.EMAIL
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.CR_FLAG
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String crFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.OPEN_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.OPEN_CHANNELID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String openChannelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.REMARK
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_DIGACCT_INF.CREATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.MCHNT_RECORD_ID
     *
     * @return the value of T_FRONT_DIGACCT_INF.MCHNT_RECORD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getMchntRecordId() {
        return mchntRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.MCHNT_RECORD_ID
     *
     * @param mchntRecordId the value for T_FRONT_DIGACCT_INF.MCHNT_RECORD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setMchntRecordId(String mchntRecordId) {
        this.mchntRecordId = mchntRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.PROD_RECORD_ID
     *
     * @return the value of T_FRONT_DIGACCT_INF.PROD_RECORD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getProdRecordId() {
        return prodRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.PROD_RECORD_ID
     *
     * @param prodRecordId the value for T_FRONT_DIGACCT_INF.PROD_RECORD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setProdRecordId(String prodRecordId) {
        this.prodRecordId = prodRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.TRANS_REQ_TIME
     *
     * @return the value of T_FRONT_DIGACCT_INF.TRANS_REQ_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getTransReqTime() {
        return transReqTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.TRANS_REQ_TIME
     *
     * @param transReqTime the value for T_FRONT_DIGACCT_INF.TRANS_REQ_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setTransReqTime(Date transReqTime) {
        this.transReqTime = transReqTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.STATUS
     *
     * @return the value of T_FRONT_DIGACCT_INF.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.STATUS
     *
     * @param status the value for T_FRONT_DIGACCT_INF.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.AC_STATE
     *
     * @return the value of T_FRONT_DIGACCT_INF.AC_STATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getAcState() {
        return acState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.AC_STATE
     *
     * @param acState the value for T_FRONT_DIGACCT_INF.AC_STATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setAcState(String acState) {
        this.acState = acState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.LAND_ACCT_NO
     *
     * @return the value of T_FRONT_DIGACCT_INF.LAND_ACCT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getLandAcctNo() {
        return landAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.LAND_ACCT_NO
     *
     * @param landAcctNo the value for T_FRONT_DIGACCT_INF.LAND_ACCT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setLandAcctNo(String landAcctNo) {
        this.landAcctNo = landAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.LAND_CUST_ID
     *
     * @return the value of T_FRONT_DIGACCT_INF.LAND_CUST_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getLandCustId() {
        return landCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.LAND_CUST_ID
     *
     * @param landCustId the value for T_FRONT_DIGACCT_INF.LAND_CUST_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setLandCustId(String landCustId) {
        this.landCustId = landCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.ACCT_NAME
     *
     * @return the value of T_FRONT_DIGACCT_INF.ACCT_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getAcctName() {
        return acctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.ACCT_NAME
     *
     * @param acctName the value for T_FRONT_DIGACCT_INF.ACCT_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setAcctName(String acctName) {
        this.acctName = acctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.PROD_ID
     *
     * @return the value of T_FRONT_DIGACCT_INF.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.PROD_ID
     *
     * @param prodId the value for T_FRONT_DIGACCT_INF.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setProdId(String prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.CURRENCY
     *
     * @return the value of T_FRONT_DIGACCT_INF.CURRENCY
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.CURRENCY
     *
     * @param currency the value for T_FRONT_DIGACCT_INF.CURRENCY
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.LAND_MCHT_ID
     *
     * @return the value of T_FRONT_DIGACCT_INF.LAND_MCHT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getLandMchtId() {
        return landMchtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.LAND_MCHT_ID
     *
     * @param landMchtId the value for T_FRONT_DIGACCT_INF.LAND_MCHT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setLandMchtId(String landMchtId) {
        this.landMchtId = landMchtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.CUST_CH_NAME
     *
     * @return the value of T_FRONT_DIGACCT_INF.CUST_CH_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getCustChName() {
        return custChName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.CUST_CH_NAME
     *
     * @param custChName the value for T_FRONT_DIGACCT_INF.CUST_CH_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCustChName(String custChName) {
        this.custChName = custChName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.CUST_EN_NAME
     *
     * @return the value of T_FRONT_DIGACCT_INF.CUST_EN_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getCustEnName() {
        return custEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.CUST_EN_NAME
     *
     * @param custEnName the value for T_FRONT_DIGACCT_INF.CUST_EN_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCustEnName(String custEnName) {
        this.custEnName = custEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.CERT_TYPE
     *
     * @return the value of T_FRONT_DIGACCT_INF.CERT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.CERT_TYPE
     *
     * @param certType the value for T_FRONT_DIGACCT_INF.CERT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCertType(String certType) {
        this.certType = certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.CERT_NO
     *
     * @return the value of T_FRONT_DIGACCT_INF.CERT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.CERT_NO
     *
     * @param certNo the value for T_FRONT_DIGACCT_INF.CERT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.TEL_NO
     *
     * @return the value of T_FRONT_DIGACCT_INF.TEL_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.TEL_NO
     *
     * @param telNo the value for T_FRONT_DIGACCT_INF.TEL_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.EMAIL
     *
     * @return the value of T_FRONT_DIGACCT_INF.EMAIL
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.EMAIL
     *
     * @param email the value for T_FRONT_DIGACCT_INF.EMAIL
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.CR_FLAG
     *
     * @return the value of T_FRONT_DIGACCT_INF.CR_FLAG
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getCrFlag() {
        return crFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.CR_FLAG
     *
     * @param crFlag the value for T_FRONT_DIGACCT_INF.CR_FLAG
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCrFlag(String crFlag) {
        this.crFlag = crFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.OPEN_DATE
     *
     * @return the value of T_FRONT_DIGACCT_INF.OPEN_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.OPEN_DATE
     *
     * @param openDate the value for T_FRONT_DIGACCT_INF.OPEN_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setOpenDate(String openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.OPEN_CHANNELID
     *
     * @return the value of T_FRONT_DIGACCT_INF.OPEN_CHANNELID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getOpenChannelid() {
        return openChannelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.OPEN_CHANNELID
     *
     * @param openChannelid the value for T_FRONT_DIGACCT_INF.OPEN_CHANNELID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setOpenChannelid(String openChannelid) {
        this.openChannelid = openChannelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.REMARK
     *
     * @return the value of T_FRONT_DIGACCT_INF.REMARK
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.REMARK
     *
     * @param remark the value for T_FRONT_DIGACCT_INF.REMARK
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_DIGACCT_INF.CREATE_TIME
     *
     * @return the value of T_FRONT_DIGACCT_INF.CREATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_DIGACCT_INF.CREATE_TIME
     *
     * @param createTime the value for T_FRONT_DIGACCT_INF.CREATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_DIGACCT_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FrontDigacctInf other = (FrontDigacctInf) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMchntRecordId() == null ? other.getMchntRecordId() == null : this.getMchntRecordId().equals(other.getMchntRecordId()))
            && (this.getProdRecordId() == null ? other.getProdRecordId() == null : this.getProdRecordId().equals(other.getProdRecordId()))
            && (this.getTransReqTime() == null ? other.getTransReqTime() == null : this.getTransReqTime().equals(other.getTransReqTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getAcState() == null ? other.getAcState() == null : this.getAcState().equals(other.getAcState()))
            && (this.getLandAcctNo() == null ? other.getLandAcctNo() == null : this.getLandAcctNo().equals(other.getLandAcctNo()))
            && (this.getLandCustId() == null ? other.getLandCustId() == null : this.getLandCustId().equals(other.getLandCustId()))
            && (this.getAcctName() == null ? other.getAcctName() == null : this.getAcctName().equals(other.getAcctName()))
            && (this.getProdId() == null ? other.getProdId() == null : this.getProdId().equals(other.getProdId()))
            && (this.getCurrency() == null ? other.getCurrency() == null : this.getCurrency().equals(other.getCurrency()))
            && (this.getLandMchtId() == null ? other.getLandMchtId() == null : this.getLandMchtId().equals(other.getLandMchtId()))
            && (this.getCustChName() == null ? other.getCustChName() == null : this.getCustChName().equals(other.getCustChName()))
            && (this.getCustEnName() == null ? other.getCustEnName() == null : this.getCustEnName().equals(other.getCustEnName()))
            && (this.getCertType() == null ? other.getCertType() == null : this.getCertType().equals(other.getCertType()))
            && (this.getCertNo() == null ? other.getCertNo() == null : this.getCertNo().equals(other.getCertNo()))
            && (this.getTelNo() == null ? other.getTelNo() == null : this.getTelNo().equals(other.getTelNo()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getCrFlag() == null ? other.getCrFlag() == null : this.getCrFlag().equals(other.getCrFlag()))
            && (this.getOpenDate() == null ? other.getOpenDate() == null : this.getOpenDate().equals(other.getOpenDate()))
            && (this.getOpenChannelid() == null ? other.getOpenChannelid() == null : this.getOpenChannelid().equals(other.getOpenChannelid()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_DIGACCT_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMchntRecordId() == null) ? 0 : getMchntRecordId().hashCode());
        result = prime * result + ((getProdRecordId() == null) ? 0 : getProdRecordId().hashCode());
        result = prime * result + ((getTransReqTime() == null) ? 0 : getTransReqTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getAcState() == null) ? 0 : getAcState().hashCode());
        result = prime * result + ((getLandAcctNo() == null) ? 0 : getLandAcctNo().hashCode());
        result = prime * result + ((getLandCustId() == null) ? 0 : getLandCustId().hashCode());
        result = prime * result + ((getAcctName() == null) ? 0 : getAcctName().hashCode());
        result = prime * result + ((getProdId() == null) ? 0 : getProdId().hashCode());
        result = prime * result + ((getCurrency() == null) ? 0 : getCurrency().hashCode());
        result = prime * result + ((getLandMchtId() == null) ? 0 : getLandMchtId().hashCode());
        result = prime * result + ((getCustChName() == null) ? 0 : getCustChName().hashCode());
        result = prime * result + ((getCustEnName() == null) ? 0 : getCustEnName().hashCode());
        result = prime * result + ((getCertType() == null) ? 0 : getCertType().hashCode());
        result = prime * result + ((getCertNo() == null) ? 0 : getCertNo().hashCode());
        result = prime * result + ((getTelNo() == null) ? 0 : getTelNo().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getCrFlag() == null) ? 0 : getCrFlag().hashCode());
        result = prime * result + ((getOpenDate() == null) ? 0 : getOpenDate().hashCode());
        result = prime * result + ((getOpenChannelid() == null) ? 0 : getOpenChannelid().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_DIGACCT_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mchntRecordId=").append(mchntRecordId);
        sb.append(", prodRecordId=").append(prodRecordId);
        sb.append(", transReqTime=").append(transReqTime);
        sb.append(", status=").append(status);
        sb.append(", acState=").append(acState);
        sb.append(", landAcctNo=").append(landAcctNo);
        sb.append(", landCustId=").append(landCustId);
        sb.append(", acctName=").append(acctName);
        sb.append(", prodId=").append(prodId);
        sb.append(", currency=").append(currency);
        sb.append(", landMchtId=").append(landMchtId);
        sb.append(", custChName=").append(custChName);
        sb.append(", custEnName=").append(custEnName);
        sb.append(", certType=").append(certType);
        sb.append(", certNo=").append(certNo);
        sb.append(", telNo=").append(telNo);
        sb.append(", email=").append(email);
        sb.append(", crFlag=").append(crFlag);
        sb.append(", openDate=").append(openDate);
        sb.append(", openChannelid=").append(openChannelid);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}