package starstart.cgame.flows.mysqlgens.trade.entity;

import cn.msec.ojpa.api.annotations.Tab;

import java.math.BigDecimal;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_FRONT_USER_PROD_ACCT")
@AllArgsConstructor
@NoArgsConstructor
public class FrontUserProdAcct extends FrontUserProdAcctKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.USER_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.LAND_ACCT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String landAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String mchntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.TOTAL_PROFIT_LAST_DAY
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private BigDecimal totalProfitLastDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.PROFIT_DAY
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private BigDecimal profitDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.TOTAL_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private BigDecimal totalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.TOTAL_DEPOSIT_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private BigDecimal totalDepositAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.DAY_DEPOSIT_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private BigDecimal dayDepositAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.DAY_WITHDRAW_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private BigDecimal dayWithdrawAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.CUST_CH_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String custChName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.CUST_EN_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String custEnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.CERT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.CERT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.TEL_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String telNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.EMAIL
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.OPEN_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.CREATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FRONT_USER_PROD_ACCT.UPD_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private Date updTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.USER_ID
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.USER_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.USER_ID
     *
     * @param userId the value for T_FRONT_USER_PROD_ACCT.USER_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.LAND_ACCT_NO
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.LAND_ACCT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getLandAcctNo() {
        return landAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.LAND_ACCT_NO
     *
     * @param landAcctNo the value for T_FRONT_USER_PROD_ACCT.LAND_ACCT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setLandAcctNo(String landAcctNo) {
        this.landAcctNo = landAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.MCHNT_ID
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getMchntId() {
        return mchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.MCHNT_ID
     *
     * @param mchntId the value for T_FRONT_USER_PROD_ACCT.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setMchntId(String mchntId) {
        this.mchntId = mchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.TOTAL_PROFIT_LAST_DAY
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.TOTAL_PROFIT_LAST_DAY
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public BigDecimal getTotalProfitLastDay() {
        return totalProfitLastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.TOTAL_PROFIT_LAST_DAY
     *
     * @param totalProfitLastDay the value for T_FRONT_USER_PROD_ACCT.TOTAL_PROFIT_LAST_DAY
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setTotalProfitLastDay(BigDecimal totalProfitLastDay) {
        this.totalProfitLastDay = totalProfitLastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.PROFIT_DAY
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.PROFIT_DAY
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public BigDecimal getProfitDay() {
        return profitDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.PROFIT_DAY
     *
     * @param profitDay the value for T_FRONT_USER_PROD_ACCT.PROFIT_DAY
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setProfitDay(BigDecimal profitDay) {
        this.profitDay = profitDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.TOTAL_AMT
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.TOTAL_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public BigDecimal getTotalAmt() {
        return totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.TOTAL_AMT
     *
     * @param totalAmt the value for T_FRONT_USER_PROD_ACCT.TOTAL_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setTotalAmt(BigDecimal totalAmt) {
        this.totalAmt = totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.TOTAL_DEPOSIT_AMT
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.TOTAL_DEPOSIT_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public BigDecimal getTotalDepositAmt() {
        return totalDepositAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.TOTAL_DEPOSIT_AMT
     *
     * @param totalDepositAmt the value for T_FRONT_USER_PROD_ACCT.TOTAL_DEPOSIT_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setTotalDepositAmt(BigDecimal totalDepositAmt) {
        this.totalDepositAmt = totalDepositAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.DAY_DEPOSIT_AMT
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.DAY_DEPOSIT_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public BigDecimal getDayDepositAmt() {
        return dayDepositAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.DAY_DEPOSIT_AMT
     *
     * @param dayDepositAmt the value for T_FRONT_USER_PROD_ACCT.DAY_DEPOSIT_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setDayDepositAmt(BigDecimal dayDepositAmt) {
        this.dayDepositAmt = dayDepositAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.DAY_WITHDRAW_AMT
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.DAY_WITHDRAW_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public BigDecimal getDayWithdrawAmt() {
        return dayWithdrawAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.DAY_WITHDRAW_AMT
     *
     * @param dayWithdrawAmt the value for T_FRONT_USER_PROD_ACCT.DAY_WITHDRAW_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setDayWithdrawAmt(BigDecimal dayWithdrawAmt) {
        this.dayWithdrawAmt = dayWithdrawAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.STATUS
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.STATUS
     *
     * @param status the value for T_FRONT_USER_PROD_ACCT.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.CUST_CH_NAME
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.CUST_CH_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getCustChName() {
        return custChName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.CUST_CH_NAME
     *
     * @param custChName the value for T_FRONT_USER_PROD_ACCT.CUST_CH_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCustChName(String custChName) {
        this.custChName = custChName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.CUST_EN_NAME
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.CUST_EN_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getCustEnName() {
        return custEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.CUST_EN_NAME
     *
     * @param custEnName the value for T_FRONT_USER_PROD_ACCT.CUST_EN_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCustEnName(String custEnName) {
        this.custEnName = custEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.CERT_TYPE
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.CERT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.CERT_TYPE
     *
     * @param certType the value for T_FRONT_USER_PROD_ACCT.CERT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCertType(String certType) {
        this.certType = certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.CERT_NO
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.CERT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.CERT_NO
     *
     * @param certNo the value for T_FRONT_USER_PROD_ACCT.CERT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.TEL_NO
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.TEL_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.TEL_NO
     *
     * @param telNo the value for T_FRONT_USER_PROD_ACCT.TEL_NO
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.EMAIL
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.EMAIL
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.EMAIL
     *
     * @param email the value for T_FRONT_USER_PROD_ACCT.EMAIL
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.OPEN_DATE
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.OPEN_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.OPEN_DATE
     *
     * @param openDate the value for T_FRONT_USER_PROD_ACCT.OPEN_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setOpenDate(String openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.CREATE_TIME
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.CREATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.CREATE_TIME
     *
     * @param createTime the value for T_FRONT_USER_PROD_ACCT.CREATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FRONT_USER_PROD_ACCT.UPD_TIME
     *
     * @return the value of T_FRONT_USER_PROD_ACCT.UPD_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FRONT_USER_PROD_ACCT.UPD_TIME
     *
     * @param updTime the value for T_FRONT_USER_PROD_ACCT.UPD_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_USER_PROD_ACCT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FrontUserProdAcct other = (FrontUserProdAcct) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getLandAcctNo() == null ? other.getLandAcctNo() == null : this.getLandAcctNo().equals(other.getLandAcctNo()))
            && (this.getMchntId() == null ? other.getMchntId() == null : this.getMchntId().equals(other.getMchntId()))
            && (this.getTotalProfitLastDay() == null ? other.getTotalProfitLastDay() == null : this.getTotalProfitLastDay().equals(other.getTotalProfitLastDay()))
            && (this.getProfitDay() == null ? other.getProfitDay() == null : this.getProfitDay().equals(other.getProfitDay()))
            && (this.getTotalAmt() == null ? other.getTotalAmt() == null : this.getTotalAmt().equals(other.getTotalAmt()))
            && (this.getTotalDepositAmt() == null ? other.getTotalDepositAmt() == null : this.getTotalDepositAmt().equals(other.getTotalDepositAmt()))
            && (this.getDayDepositAmt() == null ? other.getDayDepositAmt() == null : this.getDayDepositAmt().equals(other.getDayDepositAmt()))
            && (this.getDayWithdrawAmt() == null ? other.getDayWithdrawAmt() == null : this.getDayWithdrawAmt().equals(other.getDayWithdrawAmt()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCustChName() == null ? other.getCustChName() == null : this.getCustChName().equals(other.getCustChName()))
            && (this.getCustEnName() == null ? other.getCustEnName() == null : this.getCustEnName().equals(other.getCustEnName()))
            && (this.getCertType() == null ? other.getCertType() == null : this.getCertType().equals(other.getCertType()))
            && (this.getCertNo() == null ? other.getCertNo() == null : this.getCertNo().equals(other.getCertNo()))
            && (this.getTelNo() == null ? other.getTelNo() == null : this.getTelNo().equals(other.getTelNo()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getOpenDate() == null ? other.getOpenDate() == null : this.getOpenDate().equals(other.getOpenDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdTime() == null ? other.getUpdTime() == null : this.getUpdTime().equals(other.getUpdTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_USER_PROD_ACCT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getLandAcctNo() == null) ? 0 : getLandAcctNo().hashCode());
        result = prime * result + ((getMchntId() == null) ? 0 : getMchntId().hashCode());
        result = prime * result + ((getTotalProfitLastDay() == null) ? 0 : getTotalProfitLastDay().hashCode());
        result = prime * result + ((getProfitDay() == null) ? 0 : getProfitDay().hashCode());
        result = prime * result + ((getTotalAmt() == null) ? 0 : getTotalAmt().hashCode());
        result = prime * result + ((getTotalDepositAmt() == null) ? 0 : getTotalDepositAmt().hashCode());
        result = prime * result + ((getDayDepositAmt() == null) ? 0 : getDayDepositAmt().hashCode());
        result = prime * result + ((getDayWithdrawAmt() == null) ? 0 : getDayWithdrawAmt().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCustChName() == null) ? 0 : getCustChName().hashCode());
        result = prime * result + ((getCustEnName() == null) ? 0 : getCustEnName().hashCode());
        result = prime * result + ((getCertType() == null) ? 0 : getCertType().hashCode());
        result = prime * result + ((getCertNo() == null) ? 0 : getCertNo().hashCode());
        result = prime * result + ((getTelNo() == null) ? 0 : getTelNo().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getOpenDate() == null) ? 0 : getOpenDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdTime() == null) ? 0 : getUpdTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_USER_PROD_ACCT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", landAcctNo=").append(landAcctNo);
        sb.append(", mchntId=").append(mchntId);
        sb.append(", totalProfitLastDay=").append(totalProfitLastDay);
        sb.append(", profitDay=").append(profitDay);
        sb.append(", totalAmt=").append(totalAmt);
        sb.append(", totalDepositAmt=").append(totalDepositAmt);
        sb.append(", dayDepositAmt=").append(dayDepositAmt);
        sb.append(", dayWithdrawAmt=").append(dayWithdrawAmt);
        sb.append(", status=").append(status);
        sb.append(", custChName=").append(custChName);
        sb.append(", custEnName=").append(custEnName);
        sb.append(", certType=").append(certType);
        sb.append(", certNo=").append(certNo);
        sb.append(", telNo=").append(telNo);
        sb.append(", email=").append(email);
        sb.append(", openDate=").append(openDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", updTime=").append(updTime);
        sb.append("]");
        return sb.toString();
    }
}