package starstart.cgame.flows.mysqlgens.trade.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class FrontCustInfExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public FrontCustInfExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInnerCustIdIsNull() {
            addCriterion("INNER_CUST_ID is null");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdIsNotNull() {
            addCriterion("INNER_CUST_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdEqualTo(String value) {
            addCriterion("INNER_CUST_ID =", value, "innerCustId");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdNotEqualTo(String value) {
            addCriterion("INNER_CUST_ID <>", value, "innerCustId");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdGreaterThan(String value) {
            addCriterion("INNER_CUST_ID >", value, "innerCustId");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdGreaterThanOrEqualTo(String value) {
            addCriterion("INNER_CUST_ID >=", value, "innerCustId");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdLessThan(String value) {
            addCriterion("INNER_CUST_ID <", value, "innerCustId");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdLessThanOrEqualTo(String value) {
            addCriterion("INNER_CUST_ID <=", value, "innerCustId");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdLike(String value) {
            addCriterion("INNER_CUST_ID like", value, "innerCustId");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdNotLike(String value) {
            addCriterion("INNER_CUST_ID not like", value, "innerCustId");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdIn(List<String> values) {
            addCriterion("INNER_CUST_ID in", values, "innerCustId");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdNotIn(List<String> values) {
            addCriterion("INNER_CUST_ID not in", values, "innerCustId");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdBetween(String value1, String value2) {
            addCriterion("INNER_CUST_ID between", value1, value2, "innerCustId");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdNotBetween(String value1, String value2) {
            addCriterion("INNER_CUST_ID not between", value1, value2, "innerCustId");
            return (Criteria) this;
        }

        public Criteria andCertNoIsNull() {
            addCriterion("CERT_NO is null");
            return (Criteria) this;
        }

        public Criteria andCertNoIsNotNull() {
            addCriterion("CERT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCertNoEqualTo(String value) {
            addCriterion("CERT_NO =", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotEqualTo(String value) {
            addCriterion("CERT_NO <>", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoGreaterThan(String value) {
            addCriterion("CERT_NO >", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoGreaterThanOrEqualTo(String value) {
            addCriterion("CERT_NO >=", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoLessThan(String value) {
            addCriterion("CERT_NO <", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoLessThanOrEqualTo(String value) {
            addCriterion("CERT_NO <=", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoLike(String value) {
            addCriterion("CERT_NO like", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotLike(String value) {
            addCriterion("CERT_NO not like", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoIn(List<String> values) {
            addCriterion("CERT_NO in", values, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotIn(List<String> values) {
            addCriterion("CERT_NO not in", values, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoBetween(String value1, String value2) {
            addCriterion("CERT_NO between", value1, value2, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotBetween(String value1, String value2) {
            addCriterion("CERT_NO not between", value1, value2, "certNo");
            return (Criteria) this;
        }

        public Criteria andCustChNameIsNull() {
            addCriterion("CUST_CH_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCustChNameIsNotNull() {
            addCriterion("CUST_CH_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCustChNameEqualTo(String value) {
            addCriterion("CUST_CH_NAME =", value, "custChName");
            return (Criteria) this;
        }

        public Criteria andCustChNameNotEqualTo(String value) {
            addCriterion("CUST_CH_NAME <>", value, "custChName");
            return (Criteria) this;
        }

        public Criteria andCustChNameGreaterThan(String value) {
            addCriterion("CUST_CH_NAME >", value, "custChName");
            return (Criteria) this;
        }

        public Criteria andCustChNameGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_CH_NAME >=", value, "custChName");
            return (Criteria) this;
        }

        public Criteria andCustChNameLessThan(String value) {
            addCriterion("CUST_CH_NAME <", value, "custChName");
            return (Criteria) this;
        }

        public Criteria andCustChNameLessThanOrEqualTo(String value) {
            addCriterion("CUST_CH_NAME <=", value, "custChName");
            return (Criteria) this;
        }

        public Criteria andCustChNameLike(String value) {
            addCriterion("CUST_CH_NAME like", value, "custChName");
            return (Criteria) this;
        }

        public Criteria andCustChNameNotLike(String value) {
            addCriterion("CUST_CH_NAME not like", value, "custChName");
            return (Criteria) this;
        }

        public Criteria andCustChNameIn(List<String> values) {
            addCriterion("CUST_CH_NAME in", values, "custChName");
            return (Criteria) this;
        }

        public Criteria andCustChNameNotIn(List<String> values) {
            addCriterion("CUST_CH_NAME not in", values, "custChName");
            return (Criteria) this;
        }

        public Criteria andCustChNameBetween(String value1, String value2) {
            addCriterion("CUST_CH_NAME between", value1, value2, "custChName");
            return (Criteria) this;
        }

        public Criteria andCustChNameNotBetween(String value1, String value2) {
            addCriterion("CUST_CH_NAME not between", value1, value2, "custChName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameIsNull() {
            addCriterion("CUST_EN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCustEnNameIsNotNull() {
            addCriterion("CUST_EN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCustEnNameEqualTo(String value) {
            addCriterion("CUST_EN_NAME =", value, "custEnName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameNotEqualTo(String value) {
            addCriterion("CUST_EN_NAME <>", value, "custEnName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameGreaterThan(String value) {
            addCriterion("CUST_EN_NAME >", value, "custEnName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_EN_NAME >=", value, "custEnName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameLessThan(String value) {
            addCriterion("CUST_EN_NAME <", value, "custEnName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameLessThanOrEqualTo(String value) {
            addCriterion("CUST_EN_NAME <=", value, "custEnName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameLike(String value) {
            addCriterion("CUST_EN_NAME like", value, "custEnName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameNotLike(String value) {
            addCriterion("CUST_EN_NAME not like", value, "custEnName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameIn(List<String> values) {
            addCriterion("CUST_EN_NAME in", values, "custEnName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameNotIn(List<String> values) {
            addCriterion("CUST_EN_NAME not in", values, "custEnName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameBetween(String value1, String value2) {
            addCriterion("CUST_EN_NAME between", value1, value2, "custEnName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameNotBetween(String value1, String value2) {
            addCriterion("CUST_EN_NAME not between", value1, value2, "custEnName");
            return (Criteria) this;
        }

        public Criteria andCertTypeIsNull() {
            addCriterion("CERT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCertTypeIsNotNull() {
            addCriterion("CERT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCertTypeEqualTo(String value) {
            addCriterion("CERT_TYPE =", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotEqualTo(String value) {
            addCriterion("CERT_TYPE <>", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeGreaterThan(String value) {
            addCriterion("CERT_TYPE >", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CERT_TYPE >=", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeLessThan(String value) {
            addCriterion("CERT_TYPE <", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeLessThanOrEqualTo(String value) {
            addCriterion("CERT_TYPE <=", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeLike(String value) {
            addCriterion("CERT_TYPE like", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotLike(String value) {
            addCriterion("CERT_TYPE not like", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeIn(List<String> values) {
            addCriterion("CERT_TYPE in", values, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotIn(List<String> values) {
            addCriterion("CERT_TYPE not in", values, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeBetween(String value1, String value2) {
            addCriterion("CERT_TYPE between", value1, value2, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotBetween(String value1, String value2) {
            addCriterion("CERT_TYPE not between", value1, value2, "certType");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("BIRTHDAY is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("BIRTHDAY is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(String value) {
            addCriterion("BIRTHDAY =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(String value) {
            addCriterion("BIRTHDAY <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(String value) {
            addCriterion("BIRTHDAY >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(String value) {
            addCriterion("BIRTHDAY <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLike(String value) {
            addCriterion("BIRTHDAY like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotLike(String value) {
            addCriterion("BIRTHDAY not like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<String> values) {
            addCriterion("BIRTHDAY in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<String> values) {
            addCriterion("BIRTHDAY not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(String value1, String value2) {
            addCriterion("BIRTHDAY between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(String value1, String value2) {
            addCriterion("BIRTHDAY not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andNatioIsNull() {
            addCriterion("NATIO is null");
            return (Criteria) this;
        }

        public Criteria andNatioIsNotNull() {
            addCriterion("NATIO is not null");
            return (Criteria) this;
        }

        public Criteria andNatioEqualTo(String value) {
            addCriterion("NATIO =", value, "natio");
            return (Criteria) this;
        }

        public Criteria andNatioNotEqualTo(String value) {
            addCriterion("NATIO <>", value, "natio");
            return (Criteria) this;
        }

        public Criteria andNatioGreaterThan(String value) {
            addCriterion("NATIO >", value, "natio");
            return (Criteria) this;
        }

        public Criteria andNatioGreaterThanOrEqualTo(String value) {
            addCriterion("NATIO >=", value, "natio");
            return (Criteria) this;
        }

        public Criteria andNatioLessThan(String value) {
            addCriterion("NATIO <", value, "natio");
            return (Criteria) this;
        }

        public Criteria andNatioLessThanOrEqualTo(String value) {
            addCriterion("NATIO <=", value, "natio");
            return (Criteria) this;
        }

        public Criteria andNatioLike(String value) {
            addCriterion("NATIO like", value, "natio");
            return (Criteria) this;
        }

        public Criteria andNatioNotLike(String value) {
            addCriterion("NATIO not like", value, "natio");
            return (Criteria) this;
        }

        public Criteria andNatioIn(List<String> values) {
            addCriterion("NATIO in", values, "natio");
            return (Criteria) this;
        }

        public Criteria andNatioNotIn(List<String> values) {
            addCriterion("NATIO not in", values, "natio");
            return (Criteria) this;
        }

        public Criteria andNatioBetween(String value1, String value2) {
            addCriterion("NATIO between", value1, value2, "natio");
            return (Criteria) this;
        }

        public Criteria andNatioNotBetween(String value1, String value2) {
            addCriterion("NATIO not between", value1, value2, "natio");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("SEX =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("SEX <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("SEX >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("SEX >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("SEX <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("SEX <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("SEX like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("SEX not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("SEX in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("SEX not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCheckFlagIsNull() {
            addCriterion("CHECK_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andCheckFlagIsNotNull() {
            addCriterion("CHECK_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andCheckFlagEqualTo(String value) {
            addCriterion("CHECK_FLAG =", value, "checkFlag");
            return (Criteria) this;
        }

        public Criteria andCheckFlagNotEqualTo(String value) {
            addCriterion("CHECK_FLAG <>", value, "checkFlag");
            return (Criteria) this;
        }

        public Criteria andCheckFlagGreaterThan(String value) {
            addCriterion("CHECK_FLAG >", value, "checkFlag");
            return (Criteria) this;
        }

        public Criteria andCheckFlagGreaterThanOrEqualTo(String value) {
            addCriterion("CHECK_FLAG >=", value, "checkFlag");
            return (Criteria) this;
        }

        public Criteria andCheckFlagLessThan(String value) {
            addCriterion("CHECK_FLAG <", value, "checkFlag");
            return (Criteria) this;
        }

        public Criteria andCheckFlagLessThanOrEqualTo(String value) {
            addCriterion("CHECK_FLAG <=", value, "checkFlag");
            return (Criteria) this;
        }

        public Criteria andCheckFlagLike(String value) {
            addCriterion("CHECK_FLAG like", value, "checkFlag");
            return (Criteria) this;
        }

        public Criteria andCheckFlagNotLike(String value) {
            addCriterion("CHECK_FLAG not like", value, "checkFlag");
            return (Criteria) this;
        }

        public Criteria andCheckFlagIn(List<String> values) {
            addCriterion("CHECK_FLAG in", values, "checkFlag");
            return (Criteria) this;
        }

        public Criteria andCheckFlagNotIn(List<String> values) {
            addCriterion("CHECK_FLAG not in", values, "checkFlag");
            return (Criteria) this;
        }

        public Criteria andCheckFlagBetween(String value1, String value2) {
            addCriterion("CHECK_FLAG between", value1, value2, "checkFlag");
            return (Criteria) this;
        }

        public Criteria andCheckFlagNotBetween(String value1, String value2) {
            addCriterion("CHECK_FLAG not between", value1, value2, "checkFlag");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andInnerCustIdLikeInsensitive(String value) {
            addCriterion("upper(INNER_CUST_ID) like", value.toUpperCase(), "innerCustId");
            return (Criteria) this;
        }

        public Criteria andCertNoLikeInsensitive(String value) {
            addCriterion("upper(CERT_NO) like", value.toUpperCase(), "certNo");
            return (Criteria) this;
        }

        public Criteria andCustChNameLikeInsensitive(String value) {
            addCriterion("upper(CUST_CH_NAME) like", value.toUpperCase(), "custChName");
            return (Criteria) this;
        }

        public Criteria andCustEnNameLikeInsensitive(String value) {
            addCriterion("upper(CUST_EN_NAME) like", value.toUpperCase(), "custEnName");
            return (Criteria) this;
        }

        public Criteria andCertTypeLikeInsensitive(String value) {
            addCriterion("upper(CERT_TYPE) like", value.toUpperCase(), "certType");
            return (Criteria) this;
        }

        public Criteria andBirthdayLikeInsensitive(String value) {
            addCriterion("upper(BIRTHDAY) like", value.toUpperCase(), "birthday");
            return (Criteria) this;
        }

        public Criteria andNatioLikeInsensitive(String value) {
            addCriterion("upper(NATIO) like", value.toUpperCase(), "natio");
            return (Criteria) this;
        }

        public Criteria andSexLikeInsensitive(String value) {
            addCriterion("upper(SEX) like", value.toUpperCase(), "sex");
            return (Criteria) this;
        }

        public Criteria andCheckFlagLikeInsensitive(String value) {
            addCriterion("upper(CHECK_FLAG) like", value.toUpperCase(), "checkFlag");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(STATUS) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 08 20:40:12 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_FRONT_CUST_INF
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}