package starstart.cgame.flows.mysqlgens.trade.entity;

import cn.msec.ojpa.api.annotations.Tab;

import java.math.BigDecimal;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_LAND_MSCS153")
@AllArgsConstructor
@NoArgsConstructor
public class LandMscs153 extends LandMscs153Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.RSP_MSG_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String rspMsgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.RESULT_CODE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String resultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.RESULT_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String resultDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.SND_MCH_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String sndMchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.ORG_BIZ_ORDER_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String orgBizOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.ORG_BIZ_MSG_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String orgBizMsgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.ORG_RESULT_CODE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String orgResultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.ORG_RESULT_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String orgResultDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.ORG_CRT_DATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private Date orgCrtDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.STTL_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String sttlDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.CURRENCY
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.STTL_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal sttlAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.MSC_SERVICE_FEE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal mscServiceFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.PRODUCT_AMOUNT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal productAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.PRODUCT_PRICE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.PRODUCT_SHARE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String productShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.PRODUCT_BALANCE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String productBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.ACT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String actNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.PRODUCT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.INV_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal invAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.PRD_SERVICE_FEE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal prdServiceFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.RECV_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private Date recvTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_MSCS153.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.RSP_MSG_ID
     *
     * @return the value of T_LAND_MSCS153.RSP_MSG_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getRspMsgId() {
        return rspMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.RSP_MSG_ID
     *
     * @param rspMsgId the value for T_LAND_MSCS153.RSP_MSG_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setRspMsgId(String rspMsgId) {
        this.rspMsgId = rspMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.RESULT_CODE
     *
     * @return the value of T_LAND_MSCS153.RESULT_CODE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.RESULT_CODE
     *
     * @param resultCode the value for T_LAND_MSCS153.RESULT_CODE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.RESULT_DESC
     *
     * @return the value of T_LAND_MSCS153.RESULT_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getResultDesc() {
        return resultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.RESULT_DESC
     *
     * @param resultDesc the value for T_LAND_MSCS153.RESULT_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setResultDesc(String resultDesc) {
        this.resultDesc = resultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.SND_MCH_ID
     *
     * @return the value of T_LAND_MSCS153.SND_MCH_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getSndMchId() {
        return sndMchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.SND_MCH_ID
     *
     * @param sndMchId the value for T_LAND_MSCS153.SND_MCH_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setSndMchId(String sndMchId) {
        this.sndMchId = sndMchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.ORG_BIZ_ORDER_ID
     *
     * @return the value of T_LAND_MSCS153.ORG_BIZ_ORDER_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getOrgBizOrderId() {
        return orgBizOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.ORG_BIZ_ORDER_ID
     *
     * @param orgBizOrderId the value for T_LAND_MSCS153.ORG_BIZ_ORDER_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setOrgBizOrderId(String orgBizOrderId) {
        this.orgBizOrderId = orgBizOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.ORG_BIZ_MSG_TYPE
     *
     * @return the value of T_LAND_MSCS153.ORG_BIZ_MSG_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getOrgBizMsgType() {
        return orgBizMsgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.ORG_BIZ_MSG_TYPE
     *
     * @param orgBizMsgType the value for T_LAND_MSCS153.ORG_BIZ_MSG_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setOrgBizMsgType(String orgBizMsgType) {
        this.orgBizMsgType = orgBizMsgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.ORG_RESULT_CODE
     *
     * @return the value of T_LAND_MSCS153.ORG_RESULT_CODE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getOrgResultCode() {
        return orgResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.ORG_RESULT_CODE
     *
     * @param orgResultCode the value for T_LAND_MSCS153.ORG_RESULT_CODE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setOrgResultCode(String orgResultCode) {
        this.orgResultCode = orgResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.ORG_RESULT_DESC
     *
     * @return the value of T_LAND_MSCS153.ORG_RESULT_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getOrgResultDesc() {
        return orgResultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.ORG_RESULT_DESC
     *
     * @param orgResultDesc the value for T_LAND_MSCS153.ORG_RESULT_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setOrgResultDesc(String orgResultDesc) {
        this.orgResultDesc = orgResultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.ORG_CRT_DATE_TIME
     *
     * @return the value of T_LAND_MSCS153.ORG_CRT_DATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getOrgCrtDateTime() {
        return orgCrtDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.ORG_CRT_DATE_TIME
     *
     * @param orgCrtDateTime the value for T_LAND_MSCS153.ORG_CRT_DATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setOrgCrtDateTime(Date orgCrtDateTime) {
        this.orgCrtDateTime = orgCrtDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.STTL_DATE
     *
     * @return the value of T_LAND_MSCS153.STTL_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getSttlDate() {
        return sttlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.STTL_DATE
     *
     * @param sttlDate the value for T_LAND_MSCS153.STTL_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setSttlDate(String sttlDate) {
        this.sttlDate = sttlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.CURRENCY
     *
     * @return the value of T_LAND_MSCS153.CURRENCY
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.CURRENCY
     *
     * @param currency the value for T_LAND_MSCS153.CURRENCY
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.STTL_AMT
     *
     * @return the value of T_LAND_MSCS153.STTL_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getSttlAmt() {
        return sttlAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.STTL_AMT
     *
     * @param sttlAmt the value for T_LAND_MSCS153.STTL_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setSttlAmt(BigDecimal sttlAmt) {
        this.sttlAmt = sttlAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.MSC_SERVICE_FEE
     *
     * @return the value of T_LAND_MSCS153.MSC_SERVICE_FEE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getMscServiceFee() {
        return mscServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.MSC_SERVICE_FEE
     *
     * @param mscServiceFee the value for T_LAND_MSCS153.MSC_SERVICE_FEE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setMscServiceFee(BigDecimal mscServiceFee) {
        this.mscServiceFee = mscServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.PRODUCT_AMOUNT
     *
     * @return the value of T_LAND_MSCS153.PRODUCT_AMOUNT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getProductAmount() {
        return productAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.PRODUCT_AMOUNT
     *
     * @param productAmount the value for T_LAND_MSCS153.PRODUCT_AMOUNT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProductAmount(BigDecimal productAmount) {
        this.productAmount = productAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.PRODUCT_PRICE
     *
     * @return the value of T_LAND_MSCS153.PRODUCT_PRICE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.PRODUCT_PRICE
     *
     * @param productPrice the value for T_LAND_MSCS153.PRODUCT_PRICE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProductPrice(String productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.PRODUCT_SHARE
     *
     * @return the value of T_LAND_MSCS153.PRODUCT_SHARE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProductShare() {
        return productShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.PRODUCT_SHARE
     *
     * @param productShare the value for T_LAND_MSCS153.PRODUCT_SHARE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProductShare(String productShare) {
        this.productShare = productShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.PRODUCT_BALANCE
     *
     * @return the value of T_LAND_MSCS153.PRODUCT_BALANCE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProductBalance() {
        return productBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.PRODUCT_BALANCE
     *
     * @param productBalance the value for T_LAND_MSCS153.PRODUCT_BALANCE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProductBalance(String productBalance) {
        this.productBalance = productBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.ACT_NO
     *
     * @return the value of T_LAND_MSCS153.ACT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getActNo() {
        return actNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.ACT_NO
     *
     * @param actNo the value for T_LAND_MSCS153.ACT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setActNo(String actNo) {
        this.actNo = actNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.PRODUCT_ID
     *
     * @return the value of T_LAND_MSCS153.PRODUCT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.PRODUCT_ID
     *
     * @param productId the value for T_LAND_MSCS153.PRODUCT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.INV_AMT
     *
     * @return the value of T_LAND_MSCS153.INV_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getInvAmt() {
        return invAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.INV_AMT
     *
     * @param invAmt the value for T_LAND_MSCS153.INV_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setInvAmt(BigDecimal invAmt) {
        this.invAmt = invAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.PRD_SERVICE_FEE
     *
     * @return the value of T_LAND_MSCS153.PRD_SERVICE_FEE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getPrdServiceFee() {
        return prdServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.PRD_SERVICE_FEE
     *
     * @param prdServiceFee the value for T_LAND_MSCS153.PRD_SERVICE_FEE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setPrdServiceFee(BigDecimal prdServiceFee) {
        this.prdServiceFee = prdServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.RECV_TIME
     *
     * @return the value of T_LAND_MSCS153.RECV_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getRecvTime() {
        return recvTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.RECV_TIME
     *
     * @param recvTime the value for T_LAND_MSCS153.RECV_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setRecvTime(Date recvTime) {
        this.recvTime = recvTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_MSCS153.UPDATE_TIME
     *
     * @return the value of T_LAND_MSCS153.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_MSCS153.UPDATE_TIME
     *
     * @param updateTime the value for T_LAND_MSCS153.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_MSCS153
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LandMscs153 other = (LandMscs153) that;
        return (this.getMsgId() == null ? other.getMsgId() == null : this.getMsgId().equals(other.getMsgId()))
            && (this.getRspMsgId() == null ? other.getRspMsgId() == null : this.getRspMsgId().equals(other.getRspMsgId()))
            && (this.getResultCode() == null ? other.getResultCode() == null : this.getResultCode().equals(other.getResultCode()))
            && (this.getResultDesc() == null ? other.getResultDesc() == null : this.getResultDesc().equals(other.getResultDesc()))
            && (this.getSndMchId() == null ? other.getSndMchId() == null : this.getSndMchId().equals(other.getSndMchId()))
            && (this.getOrgBizOrderId() == null ? other.getOrgBizOrderId() == null : this.getOrgBizOrderId().equals(other.getOrgBizOrderId()))
            && (this.getOrgBizMsgType() == null ? other.getOrgBizMsgType() == null : this.getOrgBizMsgType().equals(other.getOrgBizMsgType()))
            && (this.getOrgResultCode() == null ? other.getOrgResultCode() == null : this.getOrgResultCode().equals(other.getOrgResultCode()))
            && (this.getOrgResultDesc() == null ? other.getOrgResultDesc() == null : this.getOrgResultDesc().equals(other.getOrgResultDesc()))
            && (this.getOrgCrtDateTime() == null ? other.getOrgCrtDateTime() == null : this.getOrgCrtDateTime().equals(other.getOrgCrtDateTime()))
            && (this.getSttlDate() == null ? other.getSttlDate() == null : this.getSttlDate().equals(other.getSttlDate()))
            && (this.getCurrency() == null ? other.getCurrency() == null : this.getCurrency().equals(other.getCurrency()))
            && (this.getSttlAmt() == null ? other.getSttlAmt() == null : this.getSttlAmt().equals(other.getSttlAmt()))
            && (this.getMscServiceFee() == null ? other.getMscServiceFee() == null : this.getMscServiceFee().equals(other.getMscServiceFee()))
            && (this.getProductAmount() == null ? other.getProductAmount() == null : this.getProductAmount().equals(other.getProductAmount()))
            && (this.getProductPrice() == null ? other.getProductPrice() == null : this.getProductPrice().equals(other.getProductPrice()))
            && (this.getProductShare() == null ? other.getProductShare() == null : this.getProductShare().equals(other.getProductShare()))
            && (this.getProductBalance() == null ? other.getProductBalance() == null : this.getProductBalance().equals(other.getProductBalance()))
            && (this.getActNo() == null ? other.getActNo() == null : this.getActNo().equals(other.getActNo()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getInvAmt() == null ? other.getInvAmt() == null : this.getInvAmt().equals(other.getInvAmt()))
            && (this.getPrdServiceFee() == null ? other.getPrdServiceFee() == null : this.getPrdServiceFee().equals(other.getPrdServiceFee()))
            && (this.getRecvTime() == null ? other.getRecvTime() == null : this.getRecvTime().equals(other.getRecvTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_MSCS153
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMsgId() == null) ? 0 : getMsgId().hashCode());
        result = prime * result + ((getRspMsgId() == null) ? 0 : getRspMsgId().hashCode());
        result = prime * result + ((getResultCode() == null) ? 0 : getResultCode().hashCode());
        result = prime * result + ((getResultDesc() == null) ? 0 : getResultDesc().hashCode());
        result = prime * result + ((getSndMchId() == null) ? 0 : getSndMchId().hashCode());
        result = prime * result + ((getOrgBizOrderId() == null) ? 0 : getOrgBizOrderId().hashCode());
        result = prime * result + ((getOrgBizMsgType() == null) ? 0 : getOrgBizMsgType().hashCode());
        result = prime * result + ((getOrgResultCode() == null) ? 0 : getOrgResultCode().hashCode());
        result = prime * result + ((getOrgResultDesc() == null) ? 0 : getOrgResultDesc().hashCode());
        result = prime * result + ((getOrgCrtDateTime() == null) ? 0 : getOrgCrtDateTime().hashCode());
        result = prime * result + ((getSttlDate() == null) ? 0 : getSttlDate().hashCode());
        result = prime * result + ((getCurrency() == null) ? 0 : getCurrency().hashCode());
        result = prime * result + ((getSttlAmt() == null) ? 0 : getSttlAmt().hashCode());
        result = prime * result + ((getMscServiceFee() == null) ? 0 : getMscServiceFee().hashCode());
        result = prime * result + ((getProductAmount() == null) ? 0 : getProductAmount().hashCode());
        result = prime * result + ((getProductPrice() == null) ? 0 : getProductPrice().hashCode());
        result = prime * result + ((getProductShare() == null) ? 0 : getProductShare().hashCode());
        result = prime * result + ((getProductBalance() == null) ? 0 : getProductBalance().hashCode());
        result = prime * result + ((getActNo() == null) ? 0 : getActNo().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getInvAmt() == null) ? 0 : getInvAmt().hashCode());
        result = prime * result + ((getPrdServiceFee() == null) ? 0 : getPrdServiceFee().hashCode());
        result = prime * result + ((getRecvTime() == null) ? 0 : getRecvTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_MSCS153
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rspMsgId=").append(rspMsgId);
        sb.append(", resultCode=").append(resultCode);
        sb.append(", resultDesc=").append(resultDesc);
        sb.append(", sndMchId=").append(sndMchId);
        sb.append(", orgBizOrderId=").append(orgBizOrderId);
        sb.append(", orgBizMsgType=").append(orgBizMsgType);
        sb.append(", orgResultCode=").append(orgResultCode);
        sb.append(", orgResultDesc=").append(orgResultDesc);
        sb.append(", orgCrtDateTime=").append(orgCrtDateTime);
        sb.append(", sttlDate=").append(sttlDate);
        sb.append(", currency=").append(currency);
        sb.append(", sttlAmt=").append(sttlAmt);
        sb.append(", mscServiceFee=").append(mscServiceFee);
        sb.append(", productAmount=").append(productAmount);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", productShare=").append(productShare);
        sb.append(", productBalance=").append(productBalance);
        sb.append(", actNo=").append(actNo);
        sb.append(", productId=").append(productId);
        sb.append(", invAmt=").append(invAmt);
        sb.append(", prdServiceFee=").append(prdServiceFee);
        sb.append(", recvTime=").append(recvTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}