package starstart.cgame.flows.mysqlgens.trade.entity;

import cn.msec.ojpa.api.annotations.Tab;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_LAND_DX_ID_DESC")
@AllArgsConstructor
@NoArgsConstructor
public class LandDxIdDesc extends LandDxIdDescKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_DX_ID_DESC.CHANNEL_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_DX_ID_DESC.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_DX_ID_DESC.CHANNEL_DX_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String channelDxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_DX_ID_DESC.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_DX_ID_DESC.CHANNEL_ID
     *
     * @return the value of T_LAND_DX_ID_DESC.CHANNEL_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_DX_ID_DESC.CHANNEL_ID
     *
     * @param channelId the value for T_LAND_DX_ID_DESC.CHANNEL_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_DX_ID_DESC.PROD_ID
     *
     * @return the value of T_LAND_DX_ID_DESC.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_DX_ID_DESC.PROD_ID
     *
     * @param prodId the value for T_LAND_DX_ID_DESC.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setProdId(String prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_DX_ID_DESC.CHANNEL_DX_ID
     *
     * @return the value of T_LAND_DX_ID_DESC.CHANNEL_DX_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getChannelDxId() {
        return channelDxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_DX_ID_DESC.CHANNEL_DX_ID
     *
     * @param channelDxId the value for T_LAND_DX_ID_DESC.CHANNEL_DX_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setChannelDxId(String channelDxId) {
        this.channelDxId = channelDxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_DX_ID_DESC.STATUS
     *
     * @return the value of T_LAND_DX_ID_DESC.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_DX_ID_DESC.STATUS
     *
     * @param status the value for T_LAND_DX_ID_DESC.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_DX_ID_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LandDxIdDesc other = (LandDxIdDesc) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getChannelId() == null ? other.getChannelId() == null : this.getChannelId().equals(other.getChannelId()))
            && (this.getProdId() == null ? other.getProdId() == null : this.getProdId().equals(other.getProdId()))
            && (this.getChannelDxId() == null ? other.getChannelDxId() == null : this.getChannelDxId().equals(other.getChannelDxId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_DX_ID_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getChannelId() == null) ? 0 : getChannelId().hashCode());
        result = prime * result + ((getProdId() == null) ? 0 : getProdId().hashCode());
        result = prime * result + ((getChannelDxId() == null) ? 0 : getChannelDxId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_DX_ID_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", channelId=").append(channelId);
        sb.append(", prodId=").append(prodId);
        sb.append(", channelDxId=").append(channelDxId);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}