package starstart.cgame.flows.mysqlgens.trade.entity;

import cn.msec.ojpa.api.annotations.Tab;

import java.math.BigDecimal;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_LAND_PROD_INFO")
@AllArgsConstructor
@NoArgsConstructor
public class LandProdInfo extends LandProdInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String mchntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.OUT_PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String outProdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.OUT_SUB_PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String outSubProdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PRODUCT_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PRODUCT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.RISK_LEVEL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String riskLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.CURRENCY
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PRODUCT_STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String productStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PRODUCT_TAGS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String productTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PRODUCT_TITLE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String productTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PRODUCT_LOGO
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String productLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PRODUCT_URL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String productUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.ADD_OPR
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String addOpr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.APPROVE_OPR
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String approveOpr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PROC_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String procDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.CREATE_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.UPD_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private Date updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.INV_AMT_UNIT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal invAmtUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.INV_AMT_MIN
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal invAmtMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.INV_AMT_MAX
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal invAmtMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.NAV_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String navDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.DAYS_ERN
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal daysErn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.ANNUALIZED_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal annualizedRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.ERN_PAY_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String ernPayDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.FNC_DAYS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private Integer fncDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.FNC_BEGIN
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String fncBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.FNC_ENDS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String fncEnds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.FNC_TOTAL_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal fncTotalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.FNC_REMAINDER_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal fncRemainderAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PROGRESS_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal progressRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.INV_END_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private Date invEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.INV_CAN_RET
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String invCanRet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.INV_CAN_SELL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String invCanSell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.INV_HOLD_MIN_DAYS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private Integer invHoldMinDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.STTL_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String sttlDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PRINCIPAL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.INTEREST
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PRESENT_ERN_PAYDATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String presentErnPaydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.FUND_MNGR_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String fundMngrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.FUND_MNGR_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String fundMngrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.FUND_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String fundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.FUND_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String fundName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.FUND_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String fundType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.INV_BEGIN_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private Date invBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.CLS_BEGIN_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private Date clsBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.CLS_END_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private Date clsEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.SUBSCRIBE_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal subscribeFeeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PURCHASE_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal purchaseFeeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.REDEEM_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal redeemFeeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.MANAGE_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal manageFeeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.DEPOSIT_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal depositFeeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.SALES_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal salesFeeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.M1_INV_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal m1InvRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.M3_ERN_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal m3ErnRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.Y1_ERN_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal y1ErnRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.HT_ERN_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal htErnRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.NAV_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal navAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.HT_NAV_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal htNavAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.ERN_PAY_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String ernPayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.PRESENT_ANNUALIZED_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal presentAnnualizedRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.DEBTOR
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String debtor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.GUARANTOR
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String guarantor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.RESELL_MAX_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal resellMaxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.RESELL_MIN_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal resellMinRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.RESELL_MAX_DAY
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal resellMaxDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.RESELL_MIN_DAY
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private BigDecimal resellMinDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_INFO.IS_CLEAR_ACCT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String isClearAcct;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.MCHNT_ID
     *
     * @return the value of T_LAND_PROD_INFO.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getMchntId() {
        return mchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.MCHNT_ID
     *
     * @param mchntId the value for T_LAND_PROD_INFO.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setMchntId(String mchntId) {
        this.mchntId = mchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.OUT_PROD_ID
     *
     * @return the value of T_LAND_PROD_INFO.OUT_PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getOutProdId() {
        return outProdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.OUT_PROD_ID
     *
     * @param outProdId the value for T_LAND_PROD_INFO.OUT_PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setOutProdId(String outProdId) {
        this.outProdId = outProdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.OUT_SUB_PROD_ID
     *
     * @return the value of T_LAND_PROD_INFO.OUT_SUB_PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getOutSubProdId() {
        return outSubProdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.OUT_SUB_PROD_ID
     *
     * @param outSubProdId the value for T_LAND_PROD_INFO.OUT_SUB_PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setOutSubProdId(String outSubProdId) {
        this.outSubProdId = outSubProdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PRODUCT_NAME
     *
     * @return the value of T_LAND_PROD_INFO.PRODUCT_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PRODUCT_NAME
     *
     * @param productName the value for T_LAND_PROD_INFO.PRODUCT_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PRODUCT_TYPE
     *
     * @return the value of T_LAND_PROD_INFO.PRODUCT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PRODUCT_TYPE
     *
     * @param productType the value for T_LAND_PROD_INFO.PRODUCT_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.RISK_LEVEL
     *
     * @return the value of T_LAND_PROD_INFO.RISK_LEVEL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getRiskLevel() {
        return riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.RISK_LEVEL
     *
     * @param riskLevel the value for T_LAND_PROD_INFO.RISK_LEVEL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setRiskLevel(String riskLevel) {
        this.riskLevel = riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.CURRENCY
     *
     * @return the value of T_LAND_PROD_INFO.CURRENCY
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.CURRENCY
     *
     * @param currency the value for T_LAND_PROD_INFO.CURRENCY
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PRODUCT_STATUS
     *
     * @return the value of T_LAND_PROD_INFO.PRODUCT_STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PRODUCT_STATUS
     *
     * @param productStatus the value for T_LAND_PROD_INFO.PRODUCT_STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PRODUCT_TAGS
     *
     * @return the value of T_LAND_PROD_INFO.PRODUCT_TAGS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProductTags() {
        return productTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PRODUCT_TAGS
     *
     * @param productTags the value for T_LAND_PROD_INFO.PRODUCT_TAGS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProductTags(String productTags) {
        this.productTags = productTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PRODUCT_TITLE
     *
     * @return the value of T_LAND_PROD_INFO.PRODUCT_TITLE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProductTitle() {
        return productTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PRODUCT_TITLE
     *
     * @param productTitle the value for T_LAND_PROD_INFO.PRODUCT_TITLE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProductTitle(String productTitle) {
        this.productTitle = productTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PRODUCT_LOGO
     *
     * @return the value of T_LAND_PROD_INFO.PRODUCT_LOGO
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProductLogo() {
        return productLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PRODUCT_LOGO
     *
     * @param productLogo the value for T_LAND_PROD_INFO.PRODUCT_LOGO
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProductLogo(String productLogo) {
        this.productLogo = productLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PRODUCT_URL
     *
     * @return the value of T_LAND_PROD_INFO.PRODUCT_URL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProductUrl() {
        return productUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PRODUCT_URL
     *
     * @param productUrl the value for T_LAND_PROD_INFO.PRODUCT_URL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProductUrl(String productUrl) {
        this.productUrl = productUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.ADD_OPR
     *
     * @return the value of T_LAND_PROD_INFO.ADD_OPR
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getAddOpr() {
        return addOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.ADD_OPR
     *
     * @param addOpr the value for T_LAND_PROD_INFO.ADD_OPR
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setAddOpr(String addOpr) {
        this.addOpr = addOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.APPROVE_OPR
     *
     * @return the value of T_LAND_PROD_INFO.APPROVE_OPR
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getApproveOpr() {
        return approveOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.APPROVE_OPR
     *
     * @param approveOpr the value for T_LAND_PROD_INFO.APPROVE_OPR
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setApproveOpr(String approveOpr) {
        this.approveOpr = approveOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.STATUS
     *
     * @return the value of T_LAND_PROD_INFO.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.STATUS
     *
     * @param status the value for T_LAND_PROD_INFO.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PROC_DESC
     *
     * @return the value of T_LAND_PROD_INFO.PROC_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProcDesc() {
        return procDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PROC_DESC
     *
     * @param procDesc the value for T_LAND_PROD_INFO.PROC_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProcDesc(String procDesc) {
        this.procDesc = procDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.CREATE_DATE
     *
     * @return the value of T_LAND_PROD_INFO.CREATE_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.CREATE_DATE
     *
     * @param createDate the value for T_LAND_PROD_INFO.CREATE_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.CREATE_TIME
     *
     * @return the value of T_LAND_PROD_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.CREATE_TIME
     *
     * @param createTime the value for T_LAND_PROD_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.UPD_TIME
     *
     * @return the value of T_LAND_PROD_INFO.UPD_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.UPD_TIME
     *
     * @param updTime the value for T_LAND_PROD_INFO.UPD_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.INV_AMT_UNIT
     *
     * @return the value of T_LAND_PROD_INFO.INV_AMT_UNIT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getInvAmtUnit() {
        return invAmtUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.INV_AMT_UNIT
     *
     * @param invAmtUnit the value for T_LAND_PROD_INFO.INV_AMT_UNIT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setInvAmtUnit(BigDecimal invAmtUnit) {
        this.invAmtUnit = invAmtUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.INV_AMT_MIN
     *
     * @return the value of T_LAND_PROD_INFO.INV_AMT_MIN
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getInvAmtMin() {
        return invAmtMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.INV_AMT_MIN
     *
     * @param invAmtMin the value for T_LAND_PROD_INFO.INV_AMT_MIN
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setInvAmtMin(BigDecimal invAmtMin) {
        this.invAmtMin = invAmtMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.INV_AMT_MAX
     *
     * @return the value of T_LAND_PROD_INFO.INV_AMT_MAX
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getInvAmtMax() {
        return invAmtMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.INV_AMT_MAX
     *
     * @param invAmtMax the value for T_LAND_PROD_INFO.INV_AMT_MAX
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setInvAmtMax(BigDecimal invAmtMax) {
        this.invAmtMax = invAmtMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.NAV_DATE
     *
     * @return the value of T_LAND_PROD_INFO.NAV_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getNavDate() {
        return navDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.NAV_DATE
     *
     * @param navDate the value for T_LAND_PROD_INFO.NAV_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setNavDate(String navDate) {
        this.navDate = navDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.DAYS_ERN
     *
     * @return the value of T_LAND_PROD_INFO.DAYS_ERN
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getDaysErn() {
        return daysErn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.DAYS_ERN
     *
     * @param daysErn the value for T_LAND_PROD_INFO.DAYS_ERN
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setDaysErn(BigDecimal daysErn) {
        this.daysErn = daysErn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.ANNUALIZED_RATE
     *
     * @return the value of T_LAND_PROD_INFO.ANNUALIZED_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getAnnualizedRate() {
        return annualizedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.ANNUALIZED_RATE
     *
     * @param annualizedRate the value for T_LAND_PROD_INFO.ANNUALIZED_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setAnnualizedRate(BigDecimal annualizedRate) {
        this.annualizedRate = annualizedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.ERN_PAY_DATE
     *
     * @return the value of T_LAND_PROD_INFO.ERN_PAY_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getErnPayDate() {
        return ernPayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.ERN_PAY_DATE
     *
     * @param ernPayDate the value for T_LAND_PROD_INFO.ERN_PAY_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setErnPayDate(String ernPayDate) {
        this.ernPayDate = ernPayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.FNC_DAYS
     *
     * @return the value of T_LAND_PROD_INFO.FNC_DAYS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public Integer getFncDays() {
        return fncDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.FNC_DAYS
     *
     * @param fncDays the value for T_LAND_PROD_INFO.FNC_DAYS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setFncDays(Integer fncDays) {
        this.fncDays = fncDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.FNC_BEGIN
     *
     * @return the value of T_LAND_PROD_INFO.FNC_BEGIN
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getFncBegin() {
        return fncBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.FNC_BEGIN
     *
     * @param fncBegin the value for T_LAND_PROD_INFO.FNC_BEGIN
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setFncBegin(String fncBegin) {
        this.fncBegin = fncBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.FNC_ENDS
     *
     * @return the value of T_LAND_PROD_INFO.FNC_ENDS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getFncEnds() {
        return fncEnds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.FNC_ENDS
     *
     * @param fncEnds the value for T_LAND_PROD_INFO.FNC_ENDS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setFncEnds(String fncEnds) {
        this.fncEnds = fncEnds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.FNC_TOTAL_AMT
     *
     * @return the value of T_LAND_PROD_INFO.FNC_TOTAL_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getFncTotalAmt() {
        return fncTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.FNC_TOTAL_AMT
     *
     * @param fncTotalAmt the value for T_LAND_PROD_INFO.FNC_TOTAL_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setFncTotalAmt(BigDecimal fncTotalAmt) {
        this.fncTotalAmt = fncTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.FNC_REMAINDER_AMT
     *
     * @return the value of T_LAND_PROD_INFO.FNC_REMAINDER_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getFncRemainderAmt() {
        return fncRemainderAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.FNC_REMAINDER_AMT
     *
     * @param fncRemainderAmt the value for T_LAND_PROD_INFO.FNC_REMAINDER_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setFncRemainderAmt(BigDecimal fncRemainderAmt) {
        this.fncRemainderAmt = fncRemainderAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PROGRESS_RATE
     *
     * @return the value of T_LAND_PROD_INFO.PROGRESS_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getProgressRate() {
        return progressRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PROGRESS_RATE
     *
     * @param progressRate the value for T_LAND_PROD_INFO.PROGRESS_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProgressRate(BigDecimal progressRate) {
        this.progressRate = progressRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.INV_END_TIME
     *
     * @return the value of T_LAND_PROD_INFO.INV_END_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getInvEndTime() {
        return invEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.INV_END_TIME
     *
     * @param invEndTime the value for T_LAND_PROD_INFO.INV_END_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setInvEndTime(Date invEndTime) {
        this.invEndTime = invEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.INV_CAN_RET
     *
     * @return the value of T_LAND_PROD_INFO.INV_CAN_RET
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getInvCanRet() {
        return invCanRet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.INV_CAN_RET
     *
     * @param invCanRet the value for T_LAND_PROD_INFO.INV_CAN_RET
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setInvCanRet(String invCanRet) {
        this.invCanRet = invCanRet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.INV_CAN_SELL
     *
     * @return the value of T_LAND_PROD_INFO.INV_CAN_SELL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getInvCanSell() {
        return invCanSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.INV_CAN_SELL
     *
     * @param invCanSell the value for T_LAND_PROD_INFO.INV_CAN_SELL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setInvCanSell(String invCanSell) {
        this.invCanSell = invCanSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.INV_HOLD_MIN_DAYS
     *
     * @return the value of T_LAND_PROD_INFO.INV_HOLD_MIN_DAYS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public Integer getInvHoldMinDays() {
        return invHoldMinDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.INV_HOLD_MIN_DAYS
     *
     * @param invHoldMinDays the value for T_LAND_PROD_INFO.INV_HOLD_MIN_DAYS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setInvHoldMinDays(Integer invHoldMinDays) {
        this.invHoldMinDays = invHoldMinDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.STTL_DATE
     *
     * @return the value of T_LAND_PROD_INFO.STTL_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getSttlDate() {
        return sttlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.STTL_DATE
     *
     * @param sttlDate the value for T_LAND_PROD_INFO.STTL_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setSttlDate(String sttlDate) {
        this.sttlDate = sttlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PRINCIPAL
     *
     * @return the value of T_LAND_PROD_INFO.PRINCIPAL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PRINCIPAL
     *
     * @param principal the value for T_LAND_PROD_INFO.PRINCIPAL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setPrincipal(BigDecimal principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.INTEREST
     *
     * @return the value of T_LAND_PROD_INFO.INTEREST
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.INTEREST
     *
     * @param interest the value for T_LAND_PROD_INFO.INTEREST
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PRESENT_ERN_PAYDATE
     *
     * @return the value of T_LAND_PROD_INFO.PRESENT_ERN_PAYDATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getPresentErnPaydate() {
        return presentErnPaydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PRESENT_ERN_PAYDATE
     *
     * @param presentErnPaydate the value for T_LAND_PROD_INFO.PRESENT_ERN_PAYDATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setPresentErnPaydate(String presentErnPaydate) {
        this.presentErnPaydate = presentErnPaydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.FUND_MNGR_ID
     *
     * @return the value of T_LAND_PROD_INFO.FUND_MNGR_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getFundMngrId() {
        return fundMngrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.FUND_MNGR_ID
     *
     * @param fundMngrId the value for T_LAND_PROD_INFO.FUND_MNGR_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setFundMngrId(String fundMngrId) {
        this.fundMngrId = fundMngrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.FUND_MNGR_NAME
     *
     * @return the value of T_LAND_PROD_INFO.FUND_MNGR_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getFundMngrName() {
        return fundMngrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.FUND_MNGR_NAME
     *
     * @param fundMngrName the value for T_LAND_PROD_INFO.FUND_MNGR_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setFundMngrName(String fundMngrName) {
        this.fundMngrName = fundMngrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.FUND_ID
     *
     * @return the value of T_LAND_PROD_INFO.FUND_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getFundId() {
        return fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.FUND_ID
     *
     * @param fundId the value for T_LAND_PROD_INFO.FUND_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setFundId(String fundId) {
        this.fundId = fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.FUND_NAME
     *
     * @return the value of T_LAND_PROD_INFO.FUND_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.FUND_NAME
     *
     * @param fundName the value for T_LAND_PROD_INFO.FUND_NAME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setFundName(String fundName) {
        this.fundName = fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.FUND_TYPE
     *
     * @return the value of T_LAND_PROD_INFO.FUND_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getFundType() {
        return fundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.FUND_TYPE
     *
     * @param fundType the value for T_LAND_PROD_INFO.FUND_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setFundType(String fundType) {
        this.fundType = fundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.INV_BEGIN_TIME
     *
     * @return the value of T_LAND_PROD_INFO.INV_BEGIN_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getInvBeginTime() {
        return invBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.INV_BEGIN_TIME
     *
     * @param invBeginTime the value for T_LAND_PROD_INFO.INV_BEGIN_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setInvBeginTime(Date invBeginTime) {
        this.invBeginTime = invBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.CLS_BEGIN_TIME
     *
     * @return the value of T_LAND_PROD_INFO.CLS_BEGIN_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getClsBeginTime() {
        return clsBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.CLS_BEGIN_TIME
     *
     * @param clsBeginTime the value for T_LAND_PROD_INFO.CLS_BEGIN_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setClsBeginTime(Date clsBeginTime) {
        this.clsBeginTime = clsBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.CLS_END_TIME
     *
     * @return the value of T_LAND_PROD_INFO.CLS_END_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getClsEndTime() {
        return clsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.CLS_END_TIME
     *
     * @param clsEndTime the value for T_LAND_PROD_INFO.CLS_END_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setClsEndTime(Date clsEndTime) {
        this.clsEndTime = clsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.SUBSCRIBE_FEE_RATE
     *
     * @return the value of T_LAND_PROD_INFO.SUBSCRIBE_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getSubscribeFeeRate() {
        return subscribeFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.SUBSCRIBE_FEE_RATE
     *
     * @param subscribeFeeRate the value for T_LAND_PROD_INFO.SUBSCRIBE_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setSubscribeFeeRate(BigDecimal subscribeFeeRate) {
        this.subscribeFeeRate = subscribeFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PURCHASE_FEE_RATE
     *
     * @return the value of T_LAND_PROD_INFO.PURCHASE_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getPurchaseFeeRate() {
        return purchaseFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PURCHASE_FEE_RATE
     *
     * @param purchaseFeeRate the value for T_LAND_PROD_INFO.PURCHASE_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setPurchaseFeeRate(BigDecimal purchaseFeeRate) {
        this.purchaseFeeRate = purchaseFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.REDEEM_FEE_RATE
     *
     * @return the value of T_LAND_PROD_INFO.REDEEM_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getRedeemFeeRate() {
        return redeemFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.REDEEM_FEE_RATE
     *
     * @param redeemFeeRate the value for T_LAND_PROD_INFO.REDEEM_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setRedeemFeeRate(BigDecimal redeemFeeRate) {
        this.redeemFeeRate = redeemFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.MANAGE_FEE_RATE
     *
     * @return the value of T_LAND_PROD_INFO.MANAGE_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getManageFeeRate() {
        return manageFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.MANAGE_FEE_RATE
     *
     * @param manageFeeRate the value for T_LAND_PROD_INFO.MANAGE_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setManageFeeRate(BigDecimal manageFeeRate) {
        this.manageFeeRate = manageFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.DEPOSIT_FEE_RATE
     *
     * @return the value of T_LAND_PROD_INFO.DEPOSIT_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getDepositFeeRate() {
        return depositFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.DEPOSIT_FEE_RATE
     *
     * @param depositFeeRate the value for T_LAND_PROD_INFO.DEPOSIT_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setDepositFeeRate(BigDecimal depositFeeRate) {
        this.depositFeeRate = depositFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.SALES_FEE_RATE
     *
     * @return the value of T_LAND_PROD_INFO.SALES_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getSalesFeeRate() {
        return salesFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.SALES_FEE_RATE
     *
     * @param salesFeeRate the value for T_LAND_PROD_INFO.SALES_FEE_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setSalesFeeRate(BigDecimal salesFeeRate) {
        this.salesFeeRate = salesFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.M1_INV_RATE
     *
     * @return the value of T_LAND_PROD_INFO.M1_INV_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getM1InvRate() {
        return m1InvRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.M1_INV_RATE
     *
     * @param m1InvRate the value for T_LAND_PROD_INFO.M1_INV_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setM1InvRate(BigDecimal m1InvRate) {
        this.m1InvRate = m1InvRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.M3_ERN_RATE
     *
     * @return the value of T_LAND_PROD_INFO.M3_ERN_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getM3ErnRate() {
        return m3ErnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.M3_ERN_RATE
     *
     * @param m3ErnRate the value for T_LAND_PROD_INFO.M3_ERN_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setM3ErnRate(BigDecimal m3ErnRate) {
        this.m3ErnRate = m3ErnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.Y1_ERN_RATE
     *
     * @return the value of T_LAND_PROD_INFO.Y1_ERN_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getY1ErnRate() {
        return y1ErnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.Y1_ERN_RATE
     *
     * @param y1ErnRate the value for T_LAND_PROD_INFO.Y1_ERN_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setY1ErnRate(BigDecimal y1ErnRate) {
        this.y1ErnRate = y1ErnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.HT_ERN_RATE
     *
     * @return the value of T_LAND_PROD_INFO.HT_ERN_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getHtErnRate() {
        return htErnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.HT_ERN_RATE
     *
     * @param htErnRate the value for T_LAND_PROD_INFO.HT_ERN_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setHtErnRate(BigDecimal htErnRate) {
        this.htErnRate = htErnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.NAV_AMT
     *
     * @return the value of T_LAND_PROD_INFO.NAV_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getNavAmt() {
        return navAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.NAV_AMT
     *
     * @param navAmt the value for T_LAND_PROD_INFO.NAV_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setNavAmt(BigDecimal navAmt) {
        this.navAmt = navAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.HT_NAV_AMT
     *
     * @return the value of T_LAND_PROD_INFO.HT_NAV_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getHtNavAmt() {
        return htNavAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.HT_NAV_AMT
     *
     * @param htNavAmt the value for T_LAND_PROD_INFO.HT_NAV_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setHtNavAmt(BigDecimal htNavAmt) {
        this.htNavAmt = htNavAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.ERN_PAY_TYPE
     *
     * @return the value of T_LAND_PROD_INFO.ERN_PAY_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getErnPayType() {
        return ernPayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.ERN_PAY_TYPE
     *
     * @param ernPayType the value for T_LAND_PROD_INFO.ERN_PAY_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setErnPayType(String ernPayType) {
        this.ernPayType = ernPayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.PRESENT_ANNUALIZED_RATE
     *
     * @return the value of T_LAND_PROD_INFO.PRESENT_ANNUALIZED_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getPresentAnnualizedRate() {
        return presentAnnualizedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.PRESENT_ANNUALIZED_RATE
     *
     * @param presentAnnualizedRate the value for T_LAND_PROD_INFO.PRESENT_ANNUALIZED_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setPresentAnnualizedRate(BigDecimal presentAnnualizedRate) {
        this.presentAnnualizedRate = presentAnnualizedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.DEBTOR
     *
     * @return the value of T_LAND_PROD_INFO.DEBTOR
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getDebtor() {
        return debtor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.DEBTOR
     *
     * @param debtor the value for T_LAND_PROD_INFO.DEBTOR
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setDebtor(String debtor) {
        this.debtor = debtor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.GUARANTOR
     *
     * @return the value of T_LAND_PROD_INFO.GUARANTOR
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getGuarantor() {
        return guarantor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.GUARANTOR
     *
     * @param guarantor the value for T_LAND_PROD_INFO.GUARANTOR
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setGuarantor(String guarantor) {
        this.guarantor = guarantor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.RESELL_MAX_RATE
     *
     * @return the value of T_LAND_PROD_INFO.RESELL_MAX_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getResellMaxRate() {
        return resellMaxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.RESELL_MAX_RATE
     *
     * @param resellMaxRate the value for T_LAND_PROD_INFO.RESELL_MAX_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setResellMaxRate(BigDecimal resellMaxRate) {
        this.resellMaxRate = resellMaxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.RESELL_MIN_RATE
     *
     * @return the value of T_LAND_PROD_INFO.RESELL_MIN_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getResellMinRate() {
        return resellMinRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.RESELL_MIN_RATE
     *
     * @param resellMinRate the value for T_LAND_PROD_INFO.RESELL_MIN_RATE
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setResellMinRate(BigDecimal resellMinRate) {
        this.resellMinRate = resellMinRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.RESELL_MAX_DAY
     *
     * @return the value of T_LAND_PROD_INFO.RESELL_MAX_DAY
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getResellMaxDay() {
        return resellMaxDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.RESELL_MAX_DAY
     *
     * @param resellMaxDay the value for T_LAND_PROD_INFO.RESELL_MAX_DAY
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setResellMaxDay(BigDecimal resellMaxDay) {
        this.resellMaxDay = resellMaxDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.RESELL_MIN_DAY
     *
     * @return the value of T_LAND_PROD_INFO.RESELL_MIN_DAY
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public BigDecimal getResellMinDay() {
        return resellMinDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.RESELL_MIN_DAY
     *
     * @param resellMinDay the value for T_LAND_PROD_INFO.RESELL_MIN_DAY
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setResellMinDay(BigDecimal resellMinDay) {
        this.resellMinDay = resellMinDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_INFO.IS_CLEAR_ACCT
     *
     * @return the value of T_LAND_PROD_INFO.IS_CLEAR_ACCT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getIsClearAcct() {
        return isClearAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_INFO.IS_CLEAR_ACCT
     *
     * @param isClearAcct the value for T_LAND_PROD_INFO.IS_CLEAR_ACCT
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setIsClearAcct(String isClearAcct) {
        this.isClearAcct = isClearAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PROD_INFO
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LandProdInfo other = (LandProdInfo) that;
        return (this.getProdId() == null ? other.getProdId() == null : this.getProdId().equals(other.getProdId()))
            && (this.getMchntId() == null ? other.getMchntId() == null : this.getMchntId().equals(other.getMchntId()))
            && (this.getOutProdId() == null ? other.getOutProdId() == null : this.getOutProdId().equals(other.getOutProdId()))
            && (this.getOutSubProdId() == null ? other.getOutSubProdId() == null : this.getOutSubProdId().equals(other.getOutSubProdId()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getProductType() == null ? other.getProductType() == null : this.getProductType().equals(other.getProductType()))
            && (this.getRiskLevel() == null ? other.getRiskLevel() == null : this.getRiskLevel().equals(other.getRiskLevel()))
            && (this.getCurrency() == null ? other.getCurrency() == null : this.getCurrency().equals(other.getCurrency()))
            && (this.getProductStatus() == null ? other.getProductStatus() == null : this.getProductStatus().equals(other.getProductStatus()))
            && (this.getProductTags() == null ? other.getProductTags() == null : this.getProductTags().equals(other.getProductTags()))
            && (this.getProductTitle() == null ? other.getProductTitle() == null : this.getProductTitle().equals(other.getProductTitle()))
            && (this.getProductLogo() == null ? other.getProductLogo() == null : this.getProductLogo().equals(other.getProductLogo()))
            && (this.getProductUrl() == null ? other.getProductUrl() == null : this.getProductUrl().equals(other.getProductUrl()))
            && (this.getAddOpr() == null ? other.getAddOpr() == null : this.getAddOpr().equals(other.getAddOpr()))
            && (this.getApproveOpr() == null ? other.getApproveOpr() == null : this.getApproveOpr().equals(other.getApproveOpr()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getProcDesc() == null ? other.getProcDesc() == null : this.getProcDesc().equals(other.getProcDesc()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdTime() == null ? other.getUpdTime() == null : this.getUpdTime().equals(other.getUpdTime()))
            && (this.getInvAmtUnit() == null ? other.getInvAmtUnit() == null : this.getInvAmtUnit().equals(other.getInvAmtUnit()))
            && (this.getInvAmtMin() == null ? other.getInvAmtMin() == null : this.getInvAmtMin().equals(other.getInvAmtMin()))
            && (this.getInvAmtMax() == null ? other.getInvAmtMax() == null : this.getInvAmtMax().equals(other.getInvAmtMax()))
            && (this.getNavDate() == null ? other.getNavDate() == null : this.getNavDate().equals(other.getNavDate()))
            && (this.getDaysErn() == null ? other.getDaysErn() == null : this.getDaysErn().equals(other.getDaysErn()))
            && (this.getAnnualizedRate() == null ? other.getAnnualizedRate() == null : this.getAnnualizedRate().equals(other.getAnnualizedRate()))
            && (this.getErnPayDate() == null ? other.getErnPayDate() == null : this.getErnPayDate().equals(other.getErnPayDate()))
            && (this.getFncDays() == null ? other.getFncDays() == null : this.getFncDays().equals(other.getFncDays()))
            && (this.getFncBegin() == null ? other.getFncBegin() == null : this.getFncBegin().equals(other.getFncBegin()))
            && (this.getFncEnds() == null ? other.getFncEnds() == null : this.getFncEnds().equals(other.getFncEnds()))
            && (this.getFncTotalAmt() == null ? other.getFncTotalAmt() == null : this.getFncTotalAmt().equals(other.getFncTotalAmt()))
            && (this.getFncRemainderAmt() == null ? other.getFncRemainderAmt() == null : this.getFncRemainderAmt().equals(other.getFncRemainderAmt()))
            && (this.getProgressRate() == null ? other.getProgressRate() == null : this.getProgressRate().equals(other.getProgressRate()))
            && (this.getInvEndTime() == null ? other.getInvEndTime() == null : this.getInvEndTime().equals(other.getInvEndTime()))
            && (this.getInvCanRet() == null ? other.getInvCanRet() == null : this.getInvCanRet().equals(other.getInvCanRet()))
            && (this.getInvCanSell() == null ? other.getInvCanSell() == null : this.getInvCanSell().equals(other.getInvCanSell()))
            && (this.getInvHoldMinDays() == null ? other.getInvHoldMinDays() == null : this.getInvHoldMinDays().equals(other.getInvHoldMinDays()))
            && (this.getSttlDate() == null ? other.getSttlDate() == null : this.getSttlDate().equals(other.getSttlDate()))
            && (this.getPrincipal() == null ? other.getPrincipal() == null : this.getPrincipal().equals(other.getPrincipal()))
            && (this.getInterest() == null ? other.getInterest() == null : this.getInterest().equals(other.getInterest()))
            && (this.getPresentErnPaydate() == null ? other.getPresentErnPaydate() == null : this.getPresentErnPaydate().equals(other.getPresentErnPaydate()))
            && (this.getFundMngrId() == null ? other.getFundMngrId() == null : this.getFundMngrId().equals(other.getFundMngrId()))
            && (this.getFundMngrName() == null ? other.getFundMngrName() == null : this.getFundMngrName().equals(other.getFundMngrName()))
            && (this.getFundId() == null ? other.getFundId() == null : this.getFundId().equals(other.getFundId()))
            && (this.getFundName() == null ? other.getFundName() == null : this.getFundName().equals(other.getFundName()))
            && (this.getFundType() == null ? other.getFundType() == null : this.getFundType().equals(other.getFundType()))
            && (this.getInvBeginTime() == null ? other.getInvBeginTime() == null : this.getInvBeginTime().equals(other.getInvBeginTime()))
            && (this.getClsBeginTime() == null ? other.getClsBeginTime() == null : this.getClsBeginTime().equals(other.getClsBeginTime()))
            && (this.getClsEndTime() == null ? other.getClsEndTime() == null : this.getClsEndTime().equals(other.getClsEndTime()))
            && (this.getSubscribeFeeRate() == null ? other.getSubscribeFeeRate() == null : this.getSubscribeFeeRate().equals(other.getSubscribeFeeRate()))
            && (this.getPurchaseFeeRate() == null ? other.getPurchaseFeeRate() == null : this.getPurchaseFeeRate().equals(other.getPurchaseFeeRate()))
            && (this.getRedeemFeeRate() == null ? other.getRedeemFeeRate() == null : this.getRedeemFeeRate().equals(other.getRedeemFeeRate()))
            && (this.getManageFeeRate() == null ? other.getManageFeeRate() == null : this.getManageFeeRate().equals(other.getManageFeeRate()))
            && (this.getDepositFeeRate() == null ? other.getDepositFeeRate() == null : this.getDepositFeeRate().equals(other.getDepositFeeRate()))
            && (this.getSalesFeeRate() == null ? other.getSalesFeeRate() == null : this.getSalesFeeRate().equals(other.getSalesFeeRate()))
            && (this.getM1InvRate() == null ? other.getM1InvRate() == null : this.getM1InvRate().equals(other.getM1InvRate()))
            && (this.getM3ErnRate() == null ? other.getM3ErnRate() == null : this.getM3ErnRate().equals(other.getM3ErnRate()))
            && (this.getY1ErnRate() == null ? other.getY1ErnRate() == null : this.getY1ErnRate().equals(other.getY1ErnRate()))
            && (this.getHtErnRate() == null ? other.getHtErnRate() == null : this.getHtErnRate().equals(other.getHtErnRate()))
            && (this.getNavAmt() == null ? other.getNavAmt() == null : this.getNavAmt().equals(other.getNavAmt()))
            && (this.getHtNavAmt() == null ? other.getHtNavAmt() == null : this.getHtNavAmt().equals(other.getHtNavAmt()))
            && (this.getErnPayType() == null ? other.getErnPayType() == null : this.getErnPayType().equals(other.getErnPayType()))
            && (this.getPresentAnnualizedRate() == null ? other.getPresentAnnualizedRate() == null : this.getPresentAnnualizedRate().equals(other.getPresentAnnualizedRate()))
            && (this.getDebtor() == null ? other.getDebtor() == null : this.getDebtor().equals(other.getDebtor()))
            && (this.getGuarantor() == null ? other.getGuarantor() == null : this.getGuarantor().equals(other.getGuarantor()))
            && (this.getResellMaxRate() == null ? other.getResellMaxRate() == null : this.getResellMaxRate().equals(other.getResellMaxRate()))
            && (this.getResellMinRate() == null ? other.getResellMinRate() == null : this.getResellMinRate().equals(other.getResellMinRate()))
            && (this.getResellMaxDay() == null ? other.getResellMaxDay() == null : this.getResellMaxDay().equals(other.getResellMaxDay()))
            && (this.getResellMinDay() == null ? other.getResellMinDay() == null : this.getResellMinDay().equals(other.getResellMinDay()))
            && (this.getIsClearAcct() == null ? other.getIsClearAcct() == null : this.getIsClearAcct().equals(other.getIsClearAcct()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PROD_INFO
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProdId() == null) ? 0 : getProdId().hashCode());
        result = prime * result + ((getMchntId() == null) ? 0 : getMchntId().hashCode());
        result = prime * result + ((getOutProdId() == null) ? 0 : getOutProdId().hashCode());
        result = prime * result + ((getOutSubProdId() == null) ? 0 : getOutSubProdId().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getProductType() == null) ? 0 : getProductType().hashCode());
        result = prime * result + ((getRiskLevel() == null) ? 0 : getRiskLevel().hashCode());
        result = prime * result + ((getCurrency() == null) ? 0 : getCurrency().hashCode());
        result = prime * result + ((getProductStatus() == null) ? 0 : getProductStatus().hashCode());
        result = prime * result + ((getProductTags() == null) ? 0 : getProductTags().hashCode());
        result = prime * result + ((getProductTitle() == null) ? 0 : getProductTitle().hashCode());
        result = prime * result + ((getProductLogo() == null) ? 0 : getProductLogo().hashCode());
        result = prime * result + ((getProductUrl() == null) ? 0 : getProductUrl().hashCode());
        result = prime * result + ((getAddOpr() == null) ? 0 : getAddOpr().hashCode());
        result = prime * result + ((getApproveOpr() == null) ? 0 : getApproveOpr().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getProcDesc() == null) ? 0 : getProcDesc().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdTime() == null) ? 0 : getUpdTime().hashCode());
        result = prime * result + ((getInvAmtUnit() == null) ? 0 : getInvAmtUnit().hashCode());
        result = prime * result + ((getInvAmtMin() == null) ? 0 : getInvAmtMin().hashCode());
        result = prime * result + ((getInvAmtMax() == null) ? 0 : getInvAmtMax().hashCode());
        result = prime * result + ((getNavDate() == null) ? 0 : getNavDate().hashCode());
        result = prime * result + ((getDaysErn() == null) ? 0 : getDaysErn().hashCode());
        result = prime * result + ((getAnnualizedRate() == null) ? 0 : getAnnualizedRate().hashCode());
        result = prime * result + ((getErnPayDate() == null) ? 0 : getErnPayDate().hashCode());
        result = prime * result + ((getFncDays() == null) ? 0 : getFncDays().hashCode());
        result = prime * result + ((getFncBegin() == null) ? 0 : getFncBegin().hashCode());
        result = prime * result + ((getFncEnds() == null) ? 0 : getFncEnds().hashCode());
        result = prime * result + ((getFncTotalAmt() == null) ? 0 : getFncTotalAmt().hashCode());
        result = prime * result + ((getFncRemainderAmt() == null) ? 0 : getFncRemainderAmt().hashCode());
        result = prime * result + ((getProgressRate() == null) ? 0 : getProgressRate().hashCode());
        result = prime * result + ((getInvEndTime() == null) ? 0 : getInvEndTime().hashCode());
        result = prime * result + ((getInvCanRet() == null) ? 0 : getInvCanRet().hashCode());
        result = prime * result + ((getInvCanSell() == null) ? 0 : getInvCanSell().hashCode());
        result = prime * result + ((getInvHoldMinDays() == null) ? 0 : getInvHoldMinDays().hashCode());
        result = prime * result + ((getSttlDate() == null) ? 0 : getSttlDate().hashCode());
        result = prime * result + ((getPrincipal() == null) ? 0 : getPrincipal().hashCode());
        result = prime * result + ((getInterest() == null) ? 0 : getInterest().hashCode());
        result = prime * result + ((getPresentErnPaydate() == null) ? 0 : getPresentErnPaydate().hashCode());
        result = prime * result + ((getFundMngrId() == null) ? 0 : getFundMngrId().hashCode());
        result = prime * result + ((getFundMngrName() == null) ? 0 : getFundMngrName().hashCode());
        result = prime * result + ((getFundId() == null) ? 0 : getFundId().hashCode());
        result = prime * result + ((getFundName() == null) ? 0 : getFundName().hashCode());
        result = prime * result + ((getFundType() == null) ? 0 : getFundType().hashCode());
        result = prime * result + ((getInvBeginTime() == null) ? 0 : getInvBeginTime().hashCode());
        result = prime * result + ((getClsBeginTime() == null) ? 0 : getClsBeginTime().hashCode());
        result = prime * result + ((getClsEndTime() == null) ? 0 : getClsEndTime().hashCode());
        result = prime * result + ((getSubscribeFeeRate() == null) ? 0 : getSubscribeFeeRate().hashCode());
        result = prime * result + ((getPurchaseFeeRate() == null) ? 0 : getPurchaseFeeRate().hashCode());
        result = prime * result + ((getRedeemFeeRate() == null) ? 0 : getRedeemFeeRate().hashCode());
        result = prime * result + ((getManageFeeRate() == null) ? 0 : getManageFeeRate().hashCode());
        result = prime * result + ((getDepositFeeRate() == null) ? 0 : getDepositFeeRate().hashCode());
        result = prime * result + ((getSalesFeeRate() == null) ? 0 : getSalesFeeRate().hashCode());
        result = prime * result + ((getM1InvRate() == null) ? 0 : getM1InvRate().hashCode());
        result = prime * result + ((getM3ErnRate() == null) ? 0 : getM3ErnRate().hashCode());
        result = prime * result + ((getY1ErnRate() == null) ? 0 : getY1ErnRate().hashCode());
        result = prime * result + ((getHtErnRate() == null) ? 0 : getHtErnRate().hashCode());
        result = prime * result + ((getNavAmt() == null) ? 0 : getNavAmt().hashCode());
        result = prime * result + ((getHtNavAmt() == null) ? 0 : getHtNavAmt().hashCode());
        result = prime * result + ((getErnPayType() == null) ? 0 : getErnPayType().hashCode());
        result = prime * result + ((getPresentAnnualizedRate() == null) ? 0 : getPresentAnnualizedRate().hashCode());
        result = prime * result + ((getDebtor() == null) ? 0 : getDebtor().hashCode());
        result = prime * result + ((getGuarantor() == null) ? 0 : getGuarantor().hashCode());
        result = prime * result + ((getResellMaxRate() == null) ? 0 : getResellMaxRate().hashCode());
        result = prime * result + ((getResellMinRate() == null) ? 0 : getResellMinRate().hashCode());
        result = prime * result + ((getResellMaxDay() == null) ? 0 : getResellMaxDay().hashCode());
        result = prime * result + ((getResellMinDay() == null) ? 0 : getResellMinDay().hashCode());
        result = prime * result + ((getIsClearAcct() == null) ? 0 : getIsClearAcct().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PROD_INFO
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mchntId=").append(mchntId);
        sb.append(", outProdId=").append(outProdId);
        sb.append(", outSubProdId=").append(outSubProdId);
        sb.append(", productName=").append(productName);
        sb.append(", productType=").append(productType);
        sb.append(", riskLevel=").append(riskLevel);
        sb.append(", currency=").append(currency);
        sb.append(", productStatus=").append(productStatus);
        sb.append(", productTags=").append(productTags);
        sb.append(", productTitle=").append(productTitle);
        sb.append(", productLogo=").append(productLogo);
        sb.append(", productUrl=").append(productUrl);
        sb.append(", addOpr=").append(addOpr);
        sb.append(", approveOpr=").append(approveOpr);
        sb.append(", status=").append(status);
        sb.append(", procDesc=").append(procDesc);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", updTime=").append(updTime);
        sb.append(", invAmtUnit=").append(invAmtUnit);
        sb.append(", invAmtMin=").append(invAmtMin);
        sb.append(", invAmtMax=").append(invAmtMax);
        sb.append(", navDate=").append(navDate);
        sb.append(", daysErn=").append(daysErn);
        sb.append(", annualizedRate=").append(annualizedRate);
        sb.append(", ernPayDate=").append(ernPayDate);
        sb.append(", fncDays=").append(fncDays);
        sb.append(", fncBegin=").append(fncBegin);
        sb.append(", fncEnds=").append(fncEnds);
        sb.append(", fncTotalAmt=").append(fncTotalAmt);
        sb.append(", fncRemainderAmt=").append(fncRemainderAmt);
        sb.append(", progressRate=").append(progressRate);
        sb.append(", invEndTime=").append(invEndTime);
        sb.append(", invCanRet=").append(invCanRet);
        sb.append(", invCanSell=").append(invCanSell);
        sb.append(", invHoldMinDays=").append(invHoldMinDays);
        sb.append(", sttlDate=").append(sttlDate);
        sb.append(", principal=").append(principal);
        sb.append(", interest=").append(interest);
        sb.append(", presentErnPaydate=").append(presentErnPaydate);
        sb.append(", fundMngrId=").append(fundMngrId);
        sb.append(", fundMngrName=").append(fundMngrName);
        sb.append(", fundId=").append(fundId);
        sb.append(", fundName=").append(fundName);
        sb.append(", fundType=").append(fundType);
        sb.append(", invBeginTime=").append(invBeginTime);
        sb.append(", clsBeginTime=").append(clsBeginTime);
        sb.append(", clsEndTime=").append(clsEndTime);
        sb.append(", subscribeFeeRate=").append(subscribeFeeRate);
        sb.append(", purchaseFeeRate=").append(purchaseFeeRate);
        sb.append(", redeemFeeRate=").append(redeemFeeRate);
        sb.append(", manageFeeRate=").append(manageFeeRate);
        sb.append(", depositFeeRate=").append(depositFeeRate);
        sb.append(", salesFeeRate=").append(salesFeeRate);
        sb.append(", m1InvRate=").append(m1InvRate);
        sb.append(", m3ErnRate=").append(m3ErnRate);
        sb.append(", y1ErnRate=").append(y1ErnRate);
        sb.append(", htErnRate=").append(htErnRate);
        sb.append(", navAmt=").append(navAmt);
        sb.append(", htNavAmt=").append(htNavAmt);
        sb.append(", ernPayType=").append(ernPayType);
        sb.append(", presentAnnualizedRate=").append(presentAnnualizedRate);
        sb.append(", debtor=").append(debtor);
        sb.append(", guarantor=").append(guarantor);
        sb.append(", resellMaxRate=").append(resellMaxRate);
        sb.append(", resellMinRate=").append(resellMinRate);
        sb.append(", resellMaxDay=").append(resellMaxDay);
        sb.append(", resellMinDay=").append(resellMinDay);
        sb.append(", isClearAcct=").append(isClearAcct);
        sb.append("]");
        return sb.toString();
    }
}