package starstart.cgame.flows.mysqlgens.trade.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class LandProdlistMagExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public LandProdlistMagExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andApplyIdIsNull() {
            addCriterion("APPLY_ID is null");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNotNull() {
            addCriterion("APPLY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andApplyIdEqualTo(String value) {
            addCriterion("APPLY_ID =", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotEqualTo(String value) {
            addCriterion("APPLY_ID <>", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThan(String value) {
            addCriterion("APPLY_ID >", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("APPLY_ID >=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThan(String value) {
            addCriterion("APPLY_ID <", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThanOrEqualTo(String value) {
            addCriterion("APPLY_ID <=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLike(String value) {
            addCriterion("APPLY_ID like", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotLike(String value) {
            addCriterion("APPLY_ID not like", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdIn(List<String> values) {
            addCriterion("APPLY_ID in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotIn(List<String> values) {
            addCriterion("APPLY_ID not in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdBetween(String value1, String value2) {
            addCriterion("APPLY_ID between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotBetween(String value1, String value2) {
            addCriterion("APPLY_ID not between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andMchntNoIsNull() {
            addCriterion("MCHNT_NO is null");
            return (Criteria) this;
        }

        public Criteria andMchntNoIsNotNull() {
            addCriterion("MCHNT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMchntNoEqualTo(String value) {
            addCriterion("MCHNT_NO =", value, "mchntNo");
            return (Criteria) this;
        }

        public Criteria andMchntNoNotEqualTo(String value) {
            addCriterion("MCHNT_NO <>", value, "mchntNo");
            return (Criteria) this;
        }

        public Criteria andMchntNoGreaterThan(String value) {
            addCriterion("MCHNT_NO >", value, "mchntNo");
            return (Criteria) this;
        }

        public Criteria andMchntNoGreaterThanOrEqualTo(String value) {
            addCriterion("MCHNT_NO >=", value, "mchntNo");
            return (Criteria) this;
        }

        public Criteria andMchntNoLessThan(String value) {
            addCriterion("MCHNT_NO <", value, "mchntNo");
            return (Criteria) this;
        }

        public Criteria andMchntNoLessThanOrEqualTo(String value) {
            addCriterion("MCHNT_NO <=", value, "mchntNo");
            return (Criteria) this;
        }

        public Criteria andMchntNoLike(String value) {
            addCriterion("MCHNT_NO like", value, "mchntNo");
            return (Criteria) this;
        }

        public Criteria andMchntNoNotLike(String value) {
            addCriterion("MCHNT_NO not like", value, "mchntNo");
            return (Criteria) this;
        }

        public Criteria andMchntNoIn(List<String> values) {
            addCriterion("MCHNT_NO in", values, "mchntNo");
            return (Criteria) this;
        }

        public Criteria andMchntNoNotIn(List<String> values) {
            addCriterion("MCHNT_NO not in", values, "mchntNo");
            return (Criteria) this;
        }

        public Criteria andMchntNoBetween(String value1, String value2) {
            addCriterion("MCHNT_NO between", value1, value2, "mchntNo");
            return (Criteria) this;
        }

        public Criteria andMchntNoNotBetween(String value1, String value2) {
            addCriterion("MCHNT_NO not between", value1, value2, "mchntNo");
            return (Criteria) this;
        }

        public Criteria andProdListIsNull() {
            addCriterion("PROD_LIST is null");
            return (Criteria) this;
        }

        public Criteria andProdListIsNotNull() {
            addCriterion("PROD_LIST is not null");
            return (Criteria) this;
        }

        public Criteria andProdListEqualTo(String value) {
            addCriterion("PROD_LIST =", value, "prodList");
            return (Criteria) this;
        }

        public Criteria andProdListNotEqualTo(String value) {
            addCriterion("PROD_LIST <>", value, "prodList");
            return (Criteria) this;
        }

        public Criteria andProdListGreaterThan(String value) {
            addCriterion("PROD_LIST >", value, "prodList");
            return (Criteria) this;
        }

        public Criteria andProdListGreaterThanOrEqualTo(String value) {
            addCriterion("PROD_LIST >=", value, "prodList");
            return (Criteria) this;
        }

        public Criteria andProdListLessThan(String value) {
            addCriterion("PROD_LIST <", value, "prodList");
            return (Criteria) this;
        }

        public Criteria andProdListLessThanOrEqualTo(String value) {
            addCriterion("PROD_LIST <=", value, "prodList");
            return (Criteria) this;
        }

        public Criteria andProdListLike(String value) {
            addCriterion("PROD_LIST like", value, "prodList");
            return (Criteria) this;
        }

        public Criteria andProdListNotLike(String value) {
            addCriterion("PROD_LIST not like", value, "prodList");
            return (Criteria) this;
        }

        public Criteria andProdListIn(List<String> values) {
            addCriterion("PROD_LIST in", values, "prodList");
            return (Criteria) this;
        }

        public Criteria andProdListNotIn(List<String> values) {
            addCriterion("PROD_LIST not in", values, "prodList");
            return (Criteria) this;
        }

        public Criteria andProdListBetween(String value1, String value2) {
            addCriterion("PROD_LIST between", value1, value2, "prodList");
            return (Criteria) this;
        }

        public Criteria andProdListNotBetween(String value1, String value2) {
            addCriterion("PROD_LIST not between", value1, value2, "prodList");
            return (Criteria) this;
        }

        public Criteria andRespIdIsNull() {
            addCriterion("RESP_ID is null");
            return (Criteria) this;
        }

        public Criteria andRespIdIsNotNull() {
            addCriterion("RESP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRespIdEqualTo(String value) {
            addCriterion("RESP_ID =", value, "respId");
            return (Criteria) this;
        }

        public Criteria andRespIdNotEqualTo(String value) {
            addCriterion("RESP_ID <>", value, "respId");
            return (Criteria) this;
        }

        public Criteria andRespIdGreaterThan(String value) {
            addCriterion("RESP_ID >", value, "respId");
            return (Criteria) this;
        }

        public Criteria andRespIdGreaterThanOrEqualTo(String value) {
            addCriterion("RESP_ID >=", value, "respId");
            return (Criteria) this;
        }

        public Criteria andRespIdLessThan(String value) {
            addCriterion("RESP_ID <", value, "respId");
            return (Criteria) this;
        }

        public Criteria andRespIdLessThanOrEqualTo(String value) {
            addCriterion("RESP_ID <=", value, "respId");
            return (Criteria) this;
        }

        public Criteria andRespIdLike(String value) {
            addCriterion("RESP_ID like", value, "respId");
            return (Criteria) this;
        }

        public Criteria andRespIdNotLike(String value) {
            addCriterion("RESP_ID not like", value, "respId");
            return (Criteria) this;
        }

        public Criteria andRespIdIn(List<String> values) {
            addCriterion("RESP_ID in", values, "respId");
            return (Criteria) this;
        }

        public Criteria andRespIdNotIn(List<String> values) {
            addCriterion("RESP_ID not in", values, "respId");
            return (Criteria) this;
        }

        public Criteria andRespIdBetween(String value1, String value2) {
            addCriterion("RESP_ID between", value1, value2, "respId");
            return (Criteria) this;
        }

        public Criteria andRespIdNotBetween(String value1, String value2) {
            addCriterion("RESP_ID not between", value1, value2, "respId");
            return (Criteria) this;
        }

        public Criteria andProcStatusIsNull() {
            addCriterion("PROC_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andProcStatusIsNotNull() {
            addCriterion("PROC_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andProcStatusEqualTo(String value) {
            addCriterion("PROC_STATUS =", value, "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcStatusNotEqualTo(String value) {
            addCriterion("PROC_STATUS <>", value, "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcStatusGreaterThan(String value) {
            addCriterion("PROC_STATUS >", value, "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcStatusGreaterThanOrEqualTo(String value) {
            addCriterion("PROC_STATUS >=", value, "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcStatusLessThan(String value) {
            addCriterion("PROC_STATUS <", value, "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcStatusLessThanOrEqualTo(String value) {
            addCriterion("PROC_STATUS <=", value, "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcStatusLike(String value) {
            addCriterion("PROC_STATUS like", value, "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcStatusNotLike(String value) {
            addCriterion("PROC_STATUS not like", value, "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcStatusIn(List<String> values) {
            addCriterion("PROC_STATUS in", values, "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcStatusNotIn(List<String> values) {
            addCriterion("PROC_STATUS not in", values, "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcStatusBetween(String value1, String value2) {
            addCriterion("PROC_STATUS between", value1, value2, "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcStatusNotBetween(String value1, String value2) {
            addCriterion("PROC_STATUS not between", value1, value2, "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcDescIsNull() {
            addCriterion("PROC_DESC is null");
            return (Criteria) this;
        }

        public Criteria andProcDescIsNotNull() {
            addCriterion("PROC_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andProcDescEqualTo(String value) {
            addCriterion("PROC_DESC =", value, "procDesc");
            return (Criteria) this;
        }

        public Criteria andProcDescNotEqualTo(String value) {
            addCriterion("PROC_DESC <>", value, "procDesc");
            return (Criteria) this;
        }

        public Criteria andProcDescGreaterThan(String value) {
            addCriterion("PROC_DESC >", value, "procDesc");
            return (Criteria) this;
        }

        public Criteria andProcDescGreaterThanOrEqualTo(String value) {
            addCriterion("PROC_DESC >=", value, "procDesc");
            return (Criteria) this;
        }

        public Criteria andProcDescLessThan(String value) {
            addCriterion("PROC_DESC <", value, "procDesc");
            return (Criteria) this;
        }

        public Criteria andProcDescLessThanOrEqualTo(String value) {
            addCriterion("PROC_DESC <=", value, "procDesc");
            return (Criteria) this;
        }

        public Criteria andProcDescLike(String value) {
            addCriterion("PROC_DESC like", value, "procDesc");
            return (Criteria) this;
        }

        public Criteria andProcDescNotLike(String value) {
            addCriterion("PROC_DESC not like", value, "procDesc");
            return (Criteria) this;
        }

        public Criteria andProcDescIn(List<String> values) {
            addCriterion("PROC_DESC in", values, "procDesc");
            return (Criteria) this;
        }

        public Criteria andProcDescNotIn(List<String> values) {
            addCriterion("PROC_DESC not in", values, "procDesc");
            return (Criteria) this;
        }

        public Criteria andProcDescBetween(String value1, String value2) {
            addCriterion("PROC_DESC between", value1, value2, "procDesc");
            return (Criteria) this;
        }

        public Criteria andProcDescNotBetween(String value1, String value2) {
            addCriterion("PROC_DESC not between", value1, value2, "procDesc");
            return (Criteria) this;
        }

        public Criteria andRecvDateIsNull() {
            addCriterion("RECV_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRecvDateIsNotNull() {
            addCriterion("RECV_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRecvDateEqualTo(String value) {
            addCriterion("RECV_DATE =", value, "recvDate");
            return (Criteria) this;
        }

        public Criteria andRecvDateNotEqualTo(String value) {
            addCriterion("RECV_DATE <>", value, "recvDate");
            return (Criteria) this;
        }

        public Criteria andRecvDateGreaterThan(String value) {
            addCriterion("RECV_DATE >", value, "recvDate");
            return (Criteria) this;
        }

        public Criteria andRecvDateGreaterThanOrEqualTo(String value) {
            addCriterion("RECV_DATE >=", value, "recvDate");
            return (Criteria) this;
        }

        public Criteria andRecvDateLessThan(String value) {
            addCriterion("RECV_DATE <", value, "recvDate");
            return (Criteria) this;
        }

        public Criteria andRecvDateLessThanOrEqualTo(String value) {
            addCriterion("RECV_DATE <=", value, "recvDate");
            return (Criteria) this;
        }

        public Criteria andRecvDateLike(String value) {
            addCriterion("RECV_DATE like", value, "recvDate");
            return (Criteria) this;
        }

        public Criteria andRecvDateNotLike(String value) {
            addCriterion("RECV_DATE not like", value, "recvDate");
            return (Criteria) this;
        }

        public Criteria andRecvDateIn(List<String> values) {
            addCriterion("RECV_DATE in", values, "recvDate");
            return (Criteria) this;
        }

        public Criteria andRecvDateNotIn(List<String> values) {
            addCriterion("RECV_DATE not in", values, "recvDate");
            return (Criteria) this;
        }

        public Criteria andRecvDateBetween(String value1, String value2) {
            addCriterion("RECV_DATE between", value1, value2, "recvDate");
            return (Criteria) this;
        }

        public Criteria andRecvDateNotBetween(String value1, String value2) {
            addCriterion("RECV_DATE not between", value1, value2, "recvDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNull() {
            addCriterion("UPD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNotNull() {
            addCriterion("UPD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeEqualTo(Date value) {
            addCriterion("UPD_TIME =", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotEqualTo(Date value) {
            addCriterion("UPD_TIME <>", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThan(Date value) {
            addCriterion("UPD_TIME >", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_TIME >=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThan(Date value) {
            addCriterion("UPD_TIME <", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPD_TIME <=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIn(List<Date> values) {
            addCriterion("UPD_TIME in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotIn(List<Date> values) {
            addCriterion("UPD_TIME not in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeBetween(Date value1, Date value2) {
            addCriterion("UPD_TIME between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPD_TIME not between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andApplyIdLikeInsensitive(String value) {
            addCriterion("upper(APPLY_ID) like", value.toUpperCase(), "applyId");
            return (Criteria) this;
        }

        public Criteria andMchntNoLikeInsensitive(String value) {
            addCriterion("upper(MCHNT_NO) like", value.toUpperCase(), "mchntNo");
            return (Criteria) this;
        }

        public Criteria andProdListLikeInsensitive(String value) {
            addCriterion("upper(PROD_LIST) like", value.toUpperCase(), "prodList");
            return (Criteria) this;
        }

        public Criteria andRespIdLikeInsensitive(String value) {
            addCriterion("upper(RESP_ID) like", value.toUpperCase(), "respId");
            return (Criteria) this;
        }

        public Criteria andProcStatusLikeInsensitive(String value) {
            addCriterion("upper(PROC_STATUS) like", value.toUpperCase(), "procStatus");
            return (Criteria) this;
        }

        public Criteria andProcDescLikeInsensitive(String value) {
            addCriterion("upper(PROC_DESC) like", value.toUpperCase(), "procDesc");
            return (Criteria) this;
        }

        public Criteria andRecvDateLikeInsensitive(String value) {
            addCriterion("upper(RECV_DATE) like", value.toUpperCase(), "recvDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 08 20:40:13 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_LAND_PRODLIST_MAG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}