package starstart.cgame.flows.mysqlgens.trade.entity;

import cn.msec.ojpa.api.annotations.Tab;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_LAND_PROD_QUERY")
@AllArgsConstructor
@NoArgsConstructor
public class LandProdQuery extends LandProdQueryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_QUERY.PORD_DESC1
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String pordDesc1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_QUERY.PORD_DESC2
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String pordDesc2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LAND_PROD_QUERY.UPD_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private Date updDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_QUERY.PORD_DESC1
     *
     * @return the value of T_LAND_PROD_QUERY.PORD_DESC1
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getPordDesc1() {
        return pordDesc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_QUERY.PORD_DESC1
     *
     * @param pordDesc1 the value for T_LAND_PROD_QUERY.PORD_DESC1
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setPordDesc1(String pordDesc1) {
        this.pordDesc1 = pordDesc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_QUERY.PORD_DESC2
     *
     * @return the value of T_LAND_PROD_QUERY.PORD_DESC2
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getPordDesc2() {
        return pordDesc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_QUERY.PORD_DESC2
     *
     * @param pordDesc2 the value for T_LAND_PROD_QUERY.PORD_DESC2
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setPordDesc2(String pordDesc2) {
        this.pordDesc2 = pordDesc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LAND_PROD_QUERY.UPD_DATE
     *
     * @return the value of T_LAND_PROD_QUERY.UPD_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LAND_PROD_QUERY.UPD_DATE
     *
     * @param updDate the value for T_LAND_PROD_QUERY.UPD_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PROD_QUERY
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LandProdQuery other = (LandProdQuery) that;
        return (this.getProdId() == null ? other.getProdId() == null : this.getProdId().equals(other.getProdId()))
            && (this.getPordDesc1() == null ? other.getPordDesc1() == null : this.getPordDesc1().equals(other.getPordDesc1()))
            && (this.getPordDesc2() == null ? other.getPordDesc2() == null : this.getPordDesc2().equals(other.getPordDesc2()))
            && (this.getUpdDate() == null ? other.getUpdDate() == null : this.getUpdDate().equals(other.getUpdDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PROD_QUERY
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProdId() == null) ? 0 : getProdId().hashCode());
        result = prime * result + ((getPordDesc1() == null) ? 0 : getPordDesc1().hashCode());
        result = prime * result + ((getPordDesc2() == null) ? 0 : getPordDesc2().hashCode());
        result = prime * result + ((getUpdDate() == null) ? 0 : getUpdDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LAND_PROD_QUERY
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pordDesc1=").append(pordDesc1);
        sb.append(", pordDesc2=").append(pordDesc2);
        sb.append(", updDate=").append(updDate);
        sb.append("]");
        return sb.toString();
    }
}