package starstart.cgame.flows.mysqlgens.trade.entity;

import cn.msec.ojpa.api.annotations.Tab;

import java.math.BigDecimal;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_MCH_FEE_DESC")
@AllArgsConstructor
@NoArgsConstructor
public class MchFeeDesc extends MchFeeDescKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String mchntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.SEQ_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String seqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.FEE_FLAG
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String feeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.FEE_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.FEE_VALUE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private BigDecimal feeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.FEE_MAX_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private BigDecimal feeMaxAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.ST_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private BigDecimal stAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.END_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private BigDecimal endAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.FEE_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private BigDecimal feeAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.PRE_SETT_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String preSettDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.CYCLE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.FEE_ST_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private Date feeStDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.FEE_END_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private Date feeEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MCH_FEE_DESC.FIELD1
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    private String field1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.MCHNT_ID
     *
     * @return the value of T_MCH_FEE_DESC.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getMchntId() {
        return mchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.MCHNT_ID
     *
     * @param mchntId the value for T_MCH_FEE_DESC.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setMchntId(String mchntId) {
        this.mchntId = mchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.PROD_ID
     *
     * @return the value of T_MCH_FEE_DESC.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.PROD_ID
     *
     * @param prodId the value for T_MCH_FEE_DESC.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setProdId(String prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.SEQ_ID
     *
     * @return the value of T_MCH_FEE_DESC.SEQ_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getSeqId() {
        return seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.SEQ_ID
     *
     * @param seqId the value for T_MCH_FEE_DESC.SEQ_ID
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setSeqId(String seqId) {
        this.seqId = seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.FEE_FLAG
     *
     * @return the value of T_MCH_FEE_DESC.FEE_FLAG
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getFeeFlag() {
        return feeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.FEE_FLAG
     *
     * @param feeFlag the value for T_MCH_FEE_DESC.FEE_FLAG
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setFeeFlag(String feeFlag) {
        this.feeFlag = feeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.FEE_TYPE
     *
     * @return the value of T_MCH_FEE_DESC.FEE_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.FEE_TYPE
     *
     * @param feeType the value for T_MCH_FEE_DESC.FEE_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setFeeType(String feeType) {
        this.feeType = feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.FEE_VALUE
     *
     * @return the value of T_MCH_FEE_DESC.FEE_VALUE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public BigDecimal getFeeValue() {
        return feeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.FEE_VALUE
     *
     * @param feeValue the value for T_MCH_FEE_DESC.FEE_VALUE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setFeeValue(BigDecimal feeValue) {
        this.feeValue = feeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.FEE_MAX_AMT
     *
     * @return the value of T_MCH_FEE_DESC.FEE_MAX_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public BigDecimal getFeeMaxAmt() {
        return feeMaxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.FEE_MAX_AMT
     *
     * @param feeMaxAmt the value for T_MCH_FEE_DESC.FEE_MAX_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setFeeMaxAmt(BigDecimal feeMaxAmt) {
        this.feeMaxAmt = feeMaxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.ST_AMT
     *
     * @return the value of T_MCH_FEE_DESC.ST_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public BigDecimal getStAmt() {
        return stAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.ST_AMT
     *
     * @param stAmt the value for T_MCH_FEE_DESC.ST_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setStAmt(BigDecimal stAmt) {
        this.stAmt = stAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.END_AMT
     *
     * @return the value of T_MCH_FEE_DESC.END_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public BigDecimal getEndAmt() {
        return endAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.END_AMT
     *
     * @param endAmt the value for T_MCH_FEE_DESC.END_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setEndAmt(BigDecimal endAmt) {
        this.endAmt = endAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.FEE_AMT
     *
     * @return the value of T_MCH_FEE_DESC.FEE_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public BigDecimal getFeeAmt() {
        return feeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.FEE_AMT
     *
     * @param feeAmt the value for T_MCH_FEE_DESC.FEE_AMT
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setFeeAmt(BigDecimal feeAmt) {
        this.feeAmt = feeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.PRE_SETT_DATE
     *
     * @return the value of T_MCH_FEE_DESC.PRE_SETT_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getPreSettDate() {
        return preSettDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.PRE_SETT_DATE
     *
     * @param preSettDate the value for T_MCH_FEE_DESC.PRE_SETT_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setPreSettDate(String preSettDate) {
        this.preSettDate = preSettDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.CYCLE
     *
     * @return the value of T_MCH_FEE_DESC.CYCLE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.CYCLE
     *
     * @param cycle the value for T_MCH_FEE_DESC.CYCLE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setCycle(String cycle) {
        this.cycle = cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.FEE_ST_DATE
     *
     * @return the value of T_MCH_FEE_DESC.FEE_ST_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getFeeStDate() {
        return feeStDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.FEE_ST_DATE
     *
     * @param feeStDate the value for T_MCH_FEE_DESC.FEE_ST_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setFeeStDate(Date feeStDate) {
        this.feeStDate = feeStDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.FEE_END_DATE
     *
     * @return the value of T_MCH_FEE_DESC.FEE_END_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getFeeEndDate() {
        return feeEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.FEE_END_DATE
     *
     * @param feeEndDate the value for T_MCH_FEE_DESC.FEE_END_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setFeeEndDate(Date feeEndDate) {
        this.feeEndDate = feeEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MCH_FEE_DESC.FIELD1
     *
     * @return the value of T_MCH_FEE_DESC.FIELD1
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MCH_FEE_DESC.FIELD1
     *
     * @param field1 the value for T_MCH_FEE_DESC.FIELD1
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setField1(String field1) {
        this.field1 = field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MchFeeDesc other = (MchFeeDesc) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMchntId() == null ? other.getMchntId() == null : this.getMchntId().equals(other.getMchntId()))
            && (this.getProdId() == null ? other.getProdId() == null : this.getProdId().equals(other.getProdId()))
            && (this.getSeqId() == null ? other.getSeqId() == null : this.getSeqId().equals(other.getSeqId()))
            && (this.getFeeFlag() == null ? other.getFeeFlag() == null : this.getFeeFlag().equals(other.getFeeFlag()))
            && (this.getFeeType() == null ? other.getFeeType() == null : this.getFeeType().equals(other.getFeeType()))
            && (this.getFeeValue() == null ? other.getFeeValue() == null : this.getFeeValue().equals(other.getFeeValue()))
            && (this.getFeeMaxAmt() == null ? other.getFeeMaxAmt() == null : this.getFeeMaxAmt().equals(other.getFeeMaxAmt()))
            && (this.getStAmt() == null ? other.getStAmt() == null : this.getStAmt().equals(other.getStAmt()))
            && (this.getEndAmt() == null ? other.getEndAmt() == null : this.getEndAmt().equals(other.getEndAmt()))
            && (this.getFeeAmt() == null ? other.getFeeAmt() == null : this.getFeeAmt().equals(other.getFeeAmt()))
            && (this.getPreSettDate() == null ? other.getPreSettDate() == null : this.getPreSettDate().equals(other.getPreSettDate()))
            && (this.getCycle() == null ? other.getCycle() == null : this.getCycle().equals(other.getCycle()))
            && (this.getFeeStDate() == null ? other.getFeeStDate() == null : this.getFeeStDate().equals(other.getFeeStDate()))
            && (this.getFeeEndDate() == null ? other.getFeeEndDate() == null : this.getFeeEndDate().equals(other.getFeeEndDate()))
            && (this.getField1() == null ? other.getField1() == null : this.getField1().equals(other.getField1()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMchntId() == null) ? 0 : getMchntId().hashCode());
        result = prime * result + ((getProdId() == null) ? 0 : getProdId().hashCode());
        result = prime * result + ((getSeqId() == null) ? 0 : getSeqId().hashCode());
        result = prime * result + ((getFeeFlag() == null) ? 0 : getFeeFlag().hashCode());
        result = prime * result + ((getFeeType() == null) ? 0 : getFeeType().hashCode());
        result = prime * result + ((getFeeValue() == null) ? 0 : getFeeValue().hashCode());
        result = prime * result + ((getFeeMaxAmt() == null) ? 0 : getFeeMaxAmt().hashCode());
        result = prime * result + ((getStAmt() == null) ? 0 : getStAmt().hashCode());
        result = prime * result + ((getEndAmt() == null) ? 0 : getEndAmt().hashCode());
        result = prime * result + ((getFeeAmt() == null) ? 0 : getFeeAmt().hashCode());
        result = prime * result + ((getPreSettDate() == null) ? 0 : getPreSettDate().hashCode());
        result = prime * result + ((getCycle() == null) ? 0 : getCycle().hashCode());
        result = prime * result + ((getFeeStDate() == null) ? 0 : getFeeStDate().hashCode());
        result = prime * result + ((getFeeEndDate() == null) ? 0 : getFeeEndDate().hashCode());
        result = prime * result + ((getField1() == null) ? 0 : getField1().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mchntId=").append(mchntId);
        sb.append(", prodId=").append(prodId);
        sb.append(", seqId=").append(seqId);
        sb.append(", feeFlag=").append(feeFlag);
        sb.append(", feeType=").append(feeType);
        sb.append(", feeValue=").append(feeValue);
        sb.append(", feeMaxAmt=").append(feeMaxAmt);
        sb.append(", stAmt=").append(stAmt);
        sb.append(", endAmt=").append(endAmt);
        sb.append(", feeAmt=").append(feeAmt);
        sb.append(", preSettDate=").append(preSettDate);
        sb.append(", cycle=").append(cycle);
        sb.append(", feeStDate=").append(feeStDate);
        sb.append(", feeEndDate=").append(feeEndDate);
        sb.append(", field1=").append(field1);
        sb.append("]");
        return sb.toString();
    }
}