package starstart.cgame.flows.mysqlgens.trade.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class MchFeeDescExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public MchFeeDescExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMchntIdIsNull() {
            addCriterion("MCHNT_ID is null");
            return (Criteria) this;
        }

        public Criteria andMchntIdIsNotNull() {
            addCriterion("MCHNT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMchntIdEqualTo(String value) {
            addCriterion("MCHNT_ID =", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdNotEqualTo(String value) {
            addCriterion("MCHNT_ID <>", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdGreaterThan(String value) {
            addCriterion("MCHNT_ID >", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdGreaterThanOrEqualTo(String value) {
            addCriterion("MCHNT_ID >=", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdLessThan(String value) {
            addCriterion("MCHNT_ID <", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdLessThanOrEqualTo(String value) {
            addCriterion("MCHNT_ID <=", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdLike(String value) {
            addCriterion("MCHNT_ID like", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdNotLike(String value) {
            addCriterion("MCHNT_ID not like", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdIn(List<String> values) {
            addCriterion("MCHNT_ID in", values, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdNotIn(List<String> values) {
            addCriterion("MCHNT_ID not in", values, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdBetween(String value1, String value2) {
            addCriterion("MCHNT_ID between", value1, value2, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdNotBetween(String value1, String value2) {
            addCriterion("MCHNT_ID not between", value1, value2, "mchntId");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNull() {
            addCriterion("PROD_ID is null");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNotNull() {
            addCriterion("PROD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProdIdEqualTo(String value) {
            addCriterion("PROD_ID =", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotEqualTo(String value) {
            addCriterion("PROD_ID <>", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThan(String value) {
            addCriterion("PROD_ID >", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThanOrEqualTo(String value) {
            addCriterion("PROD_ID >=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThan(String value) {
            addCriterion("PROD_ID <", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThanOrEqualTo(String value) {
            addCriterion("PROD_ID <=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLike(String value) {
            addCriterion("PROD_ID like", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotLike(String value) {
            addCriterion("PROD_ID not like", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdIn(List<String> values) {
            addCriterion("PROD_ID in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotIn(List<String> values) {
            addCriterion("PROD_ID not in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdBetween(String value1, String value2) {
            addCriterion("PROD_ID between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotBetween(String value1, String value2) {
            addCriterion("PROD_ID not between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andSeqIdIsNull() {
            addCriterion("SEQ_ID is null");
            return (Criteria) this;
        }

        public Criteria andSeqIdIsNotNull() {
            addCriterion("SEQ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSeqIdEqualTo(String value) {
            addCriterion("SEQ_ID =", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotEqualTo(String value) {
            addCriterion("SEQ_ID <>", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdGreaterThan(String value) {
            addCriterion("SEQ_ID >", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_ID >=", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdLessThan(String value) {
            addCriterion("SEQ_ID <", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdLessThanOrEqualTo(String value) {
            addCriterion("SEQ_ID <=", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdLike(String value) {
            addCriterion("SEQ_ID like", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotLike(String value) {
            addCriterion("SEQ_ID not like", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdIn(List<String> values) {
            addCriterion("SEQ_ID in", values, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotIn(List<String> values) {
            addCriterion("SEQ_ID not in", values, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdBetween(String value1, String value2) {
            addCriterion("SEQ_ID between", value1, value2, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotBetween(String value1, String value2) {
            addCriterion("SEQ_ID not between", value1, value2, "seqId");
            return (Criteria) this;
        }

        public Criteria andFeeFlagIsNull() {
            addCriterion("FEE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFeeFlagIsNotNull() {
            addCriterion("FEE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFeeFlagEqualTo(String value) {
            addCriterion("FEE_FLAG =", value, "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeFlagNotEqualTo(String value) {
            addCriterion("FEE_FLAG <>", value, "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeFlagGreaterThan(String value) {
            addCriterion("FEE_FLAG >", value, "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeFlagGreaterThanOrEqualTo(String value) {
            addCriterion("FEE_FLAG >=", value, "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeFlagLessThan(String value) {
            addCriterion("FEE_FLAG <", value, "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeFlagLessThanOrEqualTo(String value) {
            addCriterion("FEE_FLAG <=", value, "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeFlagLike(String value) {
            addCriterion("FEE_FLAG like", value, "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeFlagNotLike(String value) {
            addCriterion("FEE_FLAG not like", value, "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeFlagIn(List<String> values) {
            addCriterion("FEE_FLAG in", values, "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeFlagNotIn(List<String> values) {
            addCriterion("FEE_FLAG not in", values, "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeFlagBetween(String value1, String value2) {
            addCriterion("FEE_FLAG between", value1, value2, "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeFlagNotBetween(String value1, String value2) {
            addCriterion("FEE_FLAG not between", value1, value2, "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeTypeIsNull() {
            addCriterion("FEE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andFeeTypeIsNotNull() {
            addCriterion("FEE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFeeTypeEqualTo(String value) {
            addCriterion("FEE_TYPE =", value, "feeType");
            return (Criteria) this;
        }

        public Criteria andFeeTypeNotEqualTo(String value) {
            addCriterion("FEE_TYPE <>", value, "feeType");
            return (Criteria) this;
        }

        public Criteria andFeeTypeGreaterThan(String value) {
            addCriterion("FEE_TYPE >", value, "feeType");
            return (Criteria) this;
        }

        public Criteria andFeeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FEE_TYPE >=", value, "feeType");
            return (Criteria) this;
        }

        public Criteria andFeeTypeLessThan(String value) {
            addCriterion("FEE_TYPE <", value, "feeType");
            return (Criteria) this;
        }

        public Criteria andFeeTypeLessThanOrEqualTo(String value) {
            addCriterion("FEE_TYPE <=", value, "feeType");
            return (Criteria) this;
        }

        public Criteria andFeeTypeLike(String value) {
            addCriterion("FEE_TYPE like", value, "feeType");
            return (Criteria) this;
        }

        public Criteria andFeeTypeNotLike(String value) {
            addCriterion("FEE_TYPE not like", value, "feeType");
            return (Criteria) this;
        }

        public Criteria andFeeTypeIn(List<String> values) {
            addCriterion("FEE_TYPE in", values, "feeType");
            return (Criteria) this;
        }

        public Criteria andFeeTypeNotIn(List<String> values) {
            addCriterion("FEE_TYPE not in", values, "feeType");
            return (Criteria) this;
        }

        public Criteria andFeeTypeBetween(String value1, String value2) {
            addCriterion("FEE_TYPE between", value1, value2, "feeType");
            return (Criteria) this;
        }

        public Criteria andFeeTypeNotBetween(String value1, String value2) {
            addCriterion("FEE_TYPE not between", value1, value2, "feeType");
            return (Criteria) this;
        }

        public Criteria andFeeValueIsNull() {
            addCriterion("FEE_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andFeeValueIsNotNull() {
            addCriterion("FEE_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andFeeValueEqualTo(BigDecimal value) {
            addCriterion("FEE_VALUE =", value, "feeValue");
            return (Criteria) this;
        }

        public Criteria andFeeValueNotEqualTo(BigDecimal value) {
            addCriterion("FEE_VALUE <>", value, "feeValue");
            return (Criteria) this;
        }

        public Criteria andFeeValueGreaterThan(BigDecimal value) {
            addCriterion("FEE_VALUE >", value, "feeValue");
            return (Criteria) this;
        }

        public Criteria andFeeValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FEE_VALUE >=", value, "feeValue");
            return (Criteria) this;
        }

        public Criteria andFeeValueLessThan(BigDecimal value) {
            addCriterion("FEE_VALUE <", value, "feeValue");
            return (Criteria) this;
        }

        public Criteria andFeeValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FEE_VALUE <=", value, "feeValue");
            return (Criteria) this;
        }

        public Criteria andFeeValueIn(List<BigDecimal> values) {
            addCriterion("FEE_VALUE in", values, "feeValue");
            return (Criteria) this;
        }

        public Criteria andFeeValueNotIn(List<BigDecimal> values) {
            addCriterion("FEE_VALUE not in", values, "feeValue");
            return (Criteria) this;
        }

        public Criteria andFeeValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEE_VALUE between", value1, value2, "feeValue");
            return (Criteria) this;
        }

        public Criteria andFeeValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEE_VALUE not between", value1, value2, "feeValue");
            return (Criteria) this;
        }

        public Criteria andFeeMaxAmtIsNull() {
            addCriterion("FEE_MAX_AMT is null");
            return (Criteria) this;
        }

        public Criteria andFeeMaxAmtIsNotNull() {
            addCriterion("FEE_MAX_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andFeeMaxAmtEqualTo(BigDecimal value) {
            addCriterion("FEE_MAX_AMT =", value, "feeMaxAmt");
            return (Criteria) this;
        }

        public Criteria andFeeMaxAmtNotEqualTo(BigDecimal value) {
            addCriterion("FEE_MAX_AMT <>", value, "feeMaxAmt");
            return (Criteria) this;
        }

        public Criteria andFeeMaxAmtGreaterThan(BigDecimal value) {
            addCriterion("FEE_MAX_AMT >", value, "feeMaxAmt");
            return (Criteria) this;
        }

        public Criteria andFeeMaxAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FEE_MAX_AMT >=", value, "feeMaxAmt");
            return (Criteria) this;
        }

        public Criteria andFeeMaxAmtLessThan(BigDecimal value) {
            addCriterion("FEE_MAX_AMT <", value, "feeMaxAmt");
            return (Criteria) this;
        }

        public Criteria andFeeMaxAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FEE_MAX_AMT <=", value, "feeMaxAmt");
            return (Criteria) this;
        }

        public Criteria andFeeMaxAmtIn(List<BigDecimal> values) {
            addCriterion("FEE_MAX_AMT in", values, "feeMaxAmt");
            return (Criteria) this;
        }

        public Criteria andFeeMaxAmtNotIn(List<BigDecimal> values) {
            addCriterion("FEE_MAX_AMT not in", values, "feeMaxAmt");
            return (Criteria) this;
        }

        public Criteria andFeeMaxAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEE_MAX_AMT between", value1, value2, "feeMaxAmt");
            return (Criteria) this;
        }

        public Criteria andFeeMaxAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEE_MAX_AMT not between", value1, value2, "feeMaxAmt");
            return (Criteria) this;
        }

        public Criteria andStAmtIsNull() {
            addCriterion("ST_AMT is null");
            return (Criteria) this;
        }

        public Criteria andStAmtIsNotNull() {
            addCriterion("ST_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andStAmtEqualTo(BigDecimal value) {
            addCriterion("ST_AMT =", value, "stAmt");
            return (Criteria) this;
        }

        public Criteria andStAmtNotEqualTo(BigDecimal value) {
            addCriterion("ST_AMT <>", value, "stAmt");
            return (Criteria) this;
        }

        public Criteria andStAmtGreaterThan(BigDecimal value) {
            addCriterion("ST_AMT >", value, "stAmt");
            return (Criteria) this;
        }

        public Criteria andStAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ST_AMT >=", value, "stAmt");
            return (Criteria) this;
        }

        public Criteria andStAmtLessThan(BigDecimal value) {
            addCriterion("ST_AMT <", value, "stAmt");
            return (Criteria) this;
        }

        public Criteria andStAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ST_AMT <=", value, "stAmt");
            return (Criteria) this;
        }

        public Criteria andStAmtIn(List<BigDecimal> values) {
            addCriterion("ST_AMT in", values, "stAmt");
            return (Criteria) this;
        }

        public Criteria andStAmtNotIn(List<BigDecimal> values) {
            addCriterion("ST_AMT not in", values, "stAmt");
            return (Criteria) this;
        }

        public Criteria andStAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ST_AMT between", value1, value2, "stAmt");
            return (Criteria) this;
        }

        public Criteria andStAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ST_AMT not between", value1, value2, "stAmt");
            return (Criteria) this;
        }

        public Criteria andEndAmtIsNull() {
            addCriterion("END_AMT is null");
            return (Criteria) this;
        }

        public Criteria andEndAmtIsNotNull() {
            addCriterion("END_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andEndAmtEqualTo(BigDecimal value) {
            addCriterion("END_AMT =", value, "endAmt");
            return (Criteria) this;
        }

        public Criteria andEndAmtNotEqualTo(BigDecimal value) {
            addCriterion("END_AMT <>", value, "endAmt");
            return (Criteria) this;
        }

        public Criteria andEndAmtGreaterThan(BigDecimal value) {
            addCriterion("END_AMT >", value, "endAmt");
            return (Criteria) this;
        }

        public Criteria andEndAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("END_AMT >=", value, "endAmt");
            return (Criteria) this;
        }

        public Criteria andEndAmtLessThan(BigDecimal value) {
            addCriterion("END_AMT <", value, "endAmt");
            return (Criteria) this;
        }

        public Criteria andEndAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("END_AMT <=", value, "endAmt");
            return (Criteria) this;
        }

        public Criteria andEndAmtIn(List<BigDecimal> values) {
            addCriterion("END_AMT in", values, "endAmt");
            return (Criteria) this;
        }

        public Criteria andEndAmtNotIn(List<BigDecimal> values) {
            addCriterion("END_AMT not in", values, "endAmt");
            return (Criteria) this;
        }

        public Criteria andEndAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("END_AMT between", value1, value2, "endAmt");
            return (Criteria) this;
        }

        public Criteria andEndAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("END_AMT not between", value1, value2, "endAmt");
            return (Criteria) this;
        }

        public Criteria andFeeAmtIsNull() {
            addCriterion("FEE_AMT is null");
            return (Criteria) this;
        }

        public Criteria andFeeAmtIsNotNull() {
            addCriterion("FEE_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andFeeAmtEqualTo(BigDecimal value) {
            addCriterion("FEE_AMT =", value, "feeAmt");
            return (Criteria) this;
        }

        public Criteria andFeeAmtNotEqualTo(BigDecimal value) {
            addCriterion("FEE_AMT <>", value, "feeAmt");
            return (Criteria) this;
        }

        public Criteria andFeeAmtGreaterThan(BigDecimal value) {
            addCriterion("FEE_AMT >", value, "feeAmt");
            return (Criteria) this;
        }

        public Criteria andFeeAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FEE_AMT >=", value, "feeAmt");
            return (Criteria) this;
        }

        public Criteria andFeeAmtLessThan(BigDecimal value) {
            addCriterion("FEE_AMT <", value, "feeAmt");
            return (Criteria) this;
        }

        public Criteria andFeeAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FEE_AMT <=", value, "feeAmt");
            return (Criteria) this;
        }

        public Criteria andFeeAmtIn(List<BigDecimal> values) {
            addCriterion("FEE_AMT in", values, "feeAmt");
            return (Criteria) this;
        }

        public Criteria andFeeAmtNotIn(List<BigDecimal> values) {
            addCriterion("FEE_AMT not in", values, "feeAmt");
            return (Criteria) this;
        }

        public Criteria andFeeAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEE_AMT between", value1, value2, "feeAmt");
            return (Criteria) this;
        }

        public Criteria andFeeAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEE_AMT not between", value1, value2, "feeAmt");
            return (Criteria) this;
        }

        public Criteria andPreSettDateIsNull() {
            addCriterion("PRE_SETT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPreSettDateIsNotNull() {
            addCriterion("PRE_SETT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPreSettDateEqualTo(String value) {
            addCriterion("PRE_SETT_DATE =", value, "preSettDate");
            return (Criteria) this;
        }

        public Criteria andPreSettDateNotEqualTo(String value) {
            addCriterion("PRE_SETT_DATE <>", value, "preSettDate");
            return (Criteria) this;
        }

        public Criteria andPreSettDateGreaterThan(String value) {
            addCriterion("PRE_SETT_DATE >", value, "preSettDate");
            return (Criteria) this;
        }

        public Criteria andPreSettDateGreaterThanOrEqualTo(String value) {
            addCriterion("PRE_SETT_DATE >=", value, "preSettDate");
            return (Criteria) this;
        }

        public Criteria andPreSettDateLessThan(String value) {
            addCriterion("PRE_SETT_DATE <", value, "preSettDate");
            return (Criteria) this;
        }

        public Criteria andPreSettDateLessThanOrEqualTo(String value) {
            addCriterion("PRE_SETT_DATE <=", value, "preSettDate");
            return (Criteria) this;
        }

        public Criteria andPreSettDateLike(String value) {
            addCriterion("PRE_SETT_DATE like", value, "preSettDate");
            return (Criteria) this;
        }

        public Criteria andPreSettDateNotLike(String value) {
            addCriterion("PRE_SETT_DATE not like", value, "preSettDate");
            return (Criteria) this;
        }

        public Criteria andPreSettDateIn(List<String> values) {
            addCriterion("PRE_SETT_DATE in", values, "preSettDate");
            return (Criteria) this;
        }

        public Criteria andPreSettDateNotIn(List<String> values) {
            addCriterion("PRE_SETT_DATE not in", values, "preSettDate");
            return (Criteria) this;
        }

        public Criteria andPreSettDateBetween(String value1, String value2) {
            addCriterion("PRE_SETT_DATE between", value1, value2, "preSettDate");
            return (Criteria) this;
        }

        public Criteria andPreSettDateNotBetween(String value1, String value2) {
            addCriterion("PRE_SETT_DATE not between", value1, value2, "preSettDate");
            return (Criteria) this;
        }

        public Criteria andCycleIsNull() {
            addCriterion("CYCLE is null");
            return (Criteria) this;
        }

        public Criteria andCycleIsNotNull() {
            addCriterion("CYCLE is not null");
            return (Criteria) this;
        }

        public Criteria andCycleEqualTo(String value) {
            addCriterion("CYCLE =", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleNotEqualTo(String value) {
            addCriterion("CYCLE <>", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleGreaterThan(String value) {
            addCriterion("CYCLE >", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleGreaterThanOrEqualTo(String value) {
            addCriterion("CYCLE >=", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleLessThan(String value) {
            addCriterion("CYCLE <", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleLessThanOrEqualTo(String value) {
            addCriterion("CYCLE <=", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleLike(String value) {
            addCriterion("CYCLE like", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleNotLike(String value) {
            addCriterion("CYCLE not like", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleIn(List<String> values) {
            addCriterion("CYCLE in", values, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleNotIn(List<String> values) {
            addCriterion("CYCLE not in", values, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleBetween(String value1, String value2) {
            addCriterion("CYCLE between", value1, value2, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleNotBetween(String value1, String value2) {
            addCriterion("CYCLE not between", value1, value2, "cycle");
            return (Criteria) this;
        }

        public Criteria andFeeStDateIsNull() {
            addCriterion("FEE_ST_DATE is null");
            return (Criteria) this;
        }

        public Criteria andFeeStDateIsNotNull() {
            addCriterion("FEE_ST_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andFeeStDateEqualTo(Date value) {
            addCriterion("FEE_ST_DATE =", value, "feeStDate");
            return (Criteria) this;
        }

        public Criteria andFeeStDateNotEqualTo(Date value) {
            addCriterion("FEE_ST_DATE <>", value, "feeStDate");
            return (Criteria) this;
        }

        public Criteria andFeeStDateGreaterThan(Date value) {
            addCriterion("FEE_ST_DATE >", value, "feeStDate");
            return (Criteria) this;
        }

        public Criteria andFeeStDateGreaterThanOrEqualTo(Date value) {
            addCriterion("FEE_ST_DATE >=", value, "feeStDate");
            return (Criteria) this;
        }

        public Criteria andFeeStDateLessThan(Date value) {
            addCriterion("FEE_ST_DATE <", value, "feeStDate");
            return (Criteria) this;
        }

        public Criteria andFeeStDateLessThanOrEqualTo(Date value) {
            addCriterion("FEE_ST_DATE <=", value, "feeStDate");
            return (Criteria) this;
        }

        public Criteria andFeeStDateIn(List<Date> values) {
            addCriterion("FEE_ST_DATE in", values, "feeStDate");
            return (Criteria) this;
        }

        public Criteria andFeeStDateNotIn(List<Date> values) {
            addCriterion("FEE_ST_DATE not in", values, "feeStDate");
            return (Criteria) this;
        }

        public Criteria andFeeStDateBetween(Date value1, Date value2) {
            addCriterion("FEE_ST_DATE between", value1, value2, "feeStDate");
            return (Criteria) this;
        }

        public Criteria andFeeStDateNotBetween(Date value1, Date value2) {
            addCriterion("FEE_ST_DATE not between", value1, value2, "feeStDate");
            return (Criteria) this;
        }

        public Criteria andFeeEndDateIsNull() {
            addCriterion("FEE_END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andFeeEndDateIsNotNull() {
            addCriterion("FEE_END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andFeeEndDateEqualTo(Date value) {
            addCriterion("FEE_END_DATE =", value, "feeEndDate");
            return (Criteria) this;
        }

        public Criteria andFeeEndDateNotEqualTo(Date value) {
            addCriterion("FEE_END_DATE <>", value, "feeEndDate");
            return (Criteria) this;
        }

        public Criteria andFeeEndDateGreaterThan(Date value) {
            addCriterion("FEE_END_DATE >", value, "feeEndDate");
            return (Criteria) this;
        }

        public Criteria andFeeEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("FEE_END_DATE >=", value, "feeEndDate");
            return (Criteria) this;
        }

        public Criteria andFeeEndDateLessThan(Date value) {
            addCriterion("FEE_END_DATE <", value, "feeEndDate");
            return (Criteria) this;
        }

        public Criteria andFeeEndDateLessThanOrEqualTo(Date value) {
            addCriterion("FEE_END_DATE <=", value, "feeEndDate");
            return (Criteria) this;
        }

        public Criteria andFeeEndDateIn(List<Date> values) {
            addCriterion("FEE_END_DATE in", values, "feeEndDate");
            return (Criteria) this;
        }

        public Criteria andFeeEndDateNotIn(List<Date> values) {
            addCriterion("FEE_END_DATE not in", values, "feeEndDate");
            return (Criteria) this;
        }

        public Criteria andFeeEndDateBetween(Date value1, Date value2) {
            addCriterion("FEE_END_DATE between", value1, value2, "feeEndDate");
            return (Criteria) this;
        }

        public Criteria andFeeEndDateNotBetween(Date value1, Date value2) {
            addCriterion("FEE_END_DATE not between", value1, value2, "feeEndDate");
            return (Criteria) this;
        }

        public Criteria andField1IsNull() {
            addCriterion("FIELD1 is null");
            return (Criteria) this;
        }

        public Criteria andField1IsNotNull() {
            addCriterion("FIELD1 is not null");
            return (Criteria) this;
        }

        public Criteria andField1EqualTo(String value) {
            addCriterion("FIELD1 =", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotEqualTo(String value) {
            addCriterion("FIELD1 <>", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1GreaterThan(String value) {
            addCriterion("FIELD1 >", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1GreaterThanOrEqualTo(String value) {
            addCriterion("FIELD1 >=", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1LessThan(String value) {
            addCriterion("FIELD1 <", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1LessThanOrEqualTo(String value) {
            addCriterion("FIELD1 <=", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1Like(String value) {
            addCriterion("FIELD1 like", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotLike(String value) {
            addCriterion("FIELD1 not like", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1In(List<String> values) {
            addCriterion("FIELD1 in", values, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotIn(List<String> values) {
            addCriterion("FIELD1 not in", values, "field1");
            return (Criteria) this;
        }

        public Criteria andField1Between(String value1, String value2) {
            addCriterion("FIELD1 between", value1, value2, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotBetween(String value1, String value2) {
            addCriterion("FIELD1 not between", value1, value2, "field1");
            return (Criteria) this;
        }

        public Criteria andIdLikeInsensitive(String value) {
            addCriterion("upper(ID) like", value.toUpperCase(), "id");
            return (Criteria) this;
        }

        public Criteria andMchntIdLikeInsensitive(String value) {
            addCriterion("upper(MCHNT_ID) like", value.toUpperCase(), "mchntId");
            return (Criteria) this;
        }

        public Criteria andProdIdLikeInsensitive(String value) {
            addCriterion("upper(PROD_ID) like", value.toUpperCase(), "prodId");
            return (Criteria) this;
        }

        public Criteria andSeqIdLikeInsensitive(String value) {
            addCriterion("upper(SEQ_ID) like", value.toUpperCase(), "seqId");
            return (Criteria) this;
        }

        public Criteria andFeeFlagLikeInsensitive(String value) {
            addCriterion("upper(FEE_FLAG) like", value.toUpperCase(), "feeFlag");
            return (Criteria) this;
        }

        public Criteria andFeeTypeLikeInsensitive(String value) {
            addCriterion("upper(FEE_TYPE) like", value.toUpperCase(), "feeType");
            return (Criteria) this;
        }

        public Criteria andPreSettDateLikeInsensitive(String value) {
            addCriterion("upper(PRE_SETT_DATE) like", value.toUpperCase(), "preSettDate");
            return (Criteria) this;
        }

        public Criteria andCycleLikeInsensitive(String value) {
            addCriterion("upper(CYCLE) like", value.toUpperCase(), "cycle");
            return (Criteria) this;
        }

        public Criteria andField1LikeInsensitive(String value) {
            addCriterion("upper(FIELD1) like", value.toUpperCase(), "field1");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 08 20:40:12 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MCH_FEE_DESC
     *
     * @mbggenerated Mon Jun 08 20:40:12 CST 2015
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}