package starstart.cgame.flows.mysqlgens.trade.entity;

import cn.msec.ojpa.api.annotations.Tab;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_TRANS_ERR_INF")
@AllArgsConstructor
@NoArgsConstructor
public class TradeErrInf extends TradeErrInfKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANS_ERR_INF.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String mchntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANS_ERR_INF.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANS_ERR_INF.RSP_MSG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String rspMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANS_ERR_INF.MCHNT_URL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String mchntUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANS_ERR_INF.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANS_ERR_INF.ERR_MSG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private String errMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANS_ERR_INF.CRT_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    private Date crtTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANS_ERR_INF.MCHNT_ID
     *
     * @return the value of T_TRANS_ERR_INF.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getMchntId() {
        return mchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANS_ERR_INF.MCHNT_ID
     *
     * @param mchntId the value for T_TRANS_ERR_INF.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setMchntId(String mchntId) {
        this.mchntId = mchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANS_ERR_INF.PROD_ID
     *
     * @return the value of T_TRANS_ERR_INF.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANS_ERR_INF.PROD_ID
     *
     * @param prodId the value for T_TRANS_ERR_INF.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setProdId(String prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANS_ERR_INF.RSP_MSG
     *
     * @return the value of T_TRANS_ERR_INF.RSP_MSG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getRspMsg() {
        return rspMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANS_ERR_INF.RSP_MSG
     *
     * @param rspMsg the value for T_TRANS_ERR_INF.RSP_MSG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setRspMsg(String rspMsg) {
        this.rspMsg = rspMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANS_ERR_INF.MCHNT_URL
     *
     * @return the value of T_TRANS_ERR_INF.MCHNT_URL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getMchntUrl() {
        return mchntUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANS_ERR_INF.MCHNT_URL
     *
     * @param mchntUrl the value for T_TRANS_ERR_INF.MCHNT_URL
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setMchntUrl(String mchntUrl) {
        this.mchntUrl = mchntUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANS_ERR_INF.STATUS
     *
     * @return the value of T_TRANS_ERR_INF.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANS_ERR_INF.STATUS
     *
     * @param status the value for T_TRANS_ERR_INF.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANS_ERR_INF.ERR_MSG
     *
     * @return the value of T_TRANS_ERR_INF.ERR_MSG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANS_ERR_INF.ERR_MSG
     *
     * @param errMsg the value for T_TRANS_ERR_INF.ERR_MSG
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANS_ERR_INF.CRT_TIME
     *
     * @return the value of T_TRANS_ERR_INF.CRT_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANS_ERR_INF.CRT_TIME
     *
     * @param crtTime the value for T_TRANS_ERR_INF.CRT_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRANS_ERR_INF
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TradeErrInf other = (TradeErrInf) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMchntId() == null ? other.getMchntId() == null : this.getMchntId().equals(other.getMchntId()))
            && (this.getProdId() == null ? other.getProdId() == null : this.getProdId().equals(other.getProdId()))
            && (this.getRspMsg() == null ? other.getRspMsg() == null : this.getRspMsg().equals(other.getRspMsg()))
            && (this.getMchntUrl() == null ? other.getMchntUrl() == null : this.getMchntUrl().equals(other.getMchntUrl()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getErrMsg() == null ? other.getErrMsg() == null : this.getErrMsg().equals(other.getErrMsg()))
            && (this.getCrtTime() == null ? other.getCrtTime() == null : this.getCrtTime().equals(other.getCrtTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRANS_ERR_INF
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMchntId() == null) ? 0 : getMchntId().hashCode());
        result = prime * result + ((getProdId() == null) ? 0 : getProdId().hashCode());
        result = prime * result + ((getRspMsg() == null) ? 0 : getRspMsg().hashCode());
        result = prime * result + ((getMchntUrl() == null) ? 0 : getMchntUrl().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getErrMsg() == null) ? 0 : getErrMsg().hashCode());
        result = prime * result + ((getCrtTime() == null) ? 0 : getCrtTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRANS_ERR_INF
     *
     * @mbggenerated Mon Jun 08 20:40:13 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mchntId=").append(mchntId);
        sb.append(", prodId=").append(prodId);
        sb.append(", rspMsg=").append(rspMsg);
        sb.append(", mchntUrl=").append(mchntUrl);
        sb.append(", status=").append(status);
        sb.append(", errMsg=").append(errMsg);
        sb.append(", crtTime=").append(crtTime);
        sb.append("]");
        return sb.toString();
    }
}