package onight.tfg.ordbgens.tlt.mapper;

import java.util.List;
import onight.tfg.ordbgens.tlt.entity.TLTIssueStatusParams;
import onight.tfg.ordbgens.tlt.entity.TLTIssueStatusParamsExample;
import onight.tfg.ordbgens.tlt.entity.TLTIssueStatusParamsKey;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TLTIssueStatusParamsMapper extends StaticTableDaoSupport<TLTIssueStatusParams, TLTIssueStatusParamsExample, TLTIssueStatusParamsKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_STATUS_PARAMS
     *
     * @mbggenerated Sun Apr 10 12:52:14 CST 2016
     */
    @SelectProvider(type=TLTIssueStatusParamsSqlProvider.class, method="countByExample")
    int countByExample(TLTIssueStatusParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_STATUS_PARAMS
     *
     * @mbggenerated Sun Apr 10 12:52:14 CST 2016
     */
    @DeleteProvider(type=TLTIssueStatusParamsSqlProvider.class, method="deleteByExample")
    int deleteByExample(TLTIssueStatusParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_STATUS_PARAMS
     *
     * @mbggenerated Sun Apr 10 12:52:14 CST 2016
     */
    @Delete({
        "delete from TLT_ISSUE_STATUS_PARAMS",
        "where GEN_ID = #{genId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(TLTIssueStatusParamsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_STATUS_PARAMS
     *
     * @mbggenerated Sun Apr 10 12:52:14 CST 2016
     */
    @Insert({
        "insert into TLT_ISSUE_STATUS_PARAMS (GEN_ID, LTYPE, ",
        "GS_ECODE, GS_NAME, ",
        "TIMESEC_OFFSET, GS_ORDER, ",
        "NEXT_ORDERS, STATE)",
        "values (#{genId,jdbcType=BIGINT}, #{ltype,jdbcType=VARCHAR}, ",
        "#{gsEcode,jdbcType=VARCHAR}, #{gsName,jdbcType=VARCHAR}, ",
        "#{timesecOffset,jdbcType=INTEGER}, #{gsOrder,jdbcType=VARCHAR}, ",
        "#{nextOrders,jdbcType=VARCHAR}, #{state,jdbcType=VARCHAR})"
    })
    int insert(TLTIssueStatusParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_STATUS_PARAMS
     *
     * @mbggenerated Sun Apr 10 12:52:14 CST 2016
     */
    @InsertProvider(type=TLTIssueStatusParamsSqlProvider.class, method="insertSelective")
    int insertSelective(TLTIssueStatusParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_STATUS_PARAMS
     *
     * @mbggenerated Sun Apr 10 12:52:14 CST 2016
     */
    @SelectProvider(type=TLTIssueStatusParamsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="GEN_ID", property="genId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LTYPE", property="ltype", jdbcType=JdbcType.VARCHAR),
        @Result(column="GS_ECODE", property="gsEcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="GS_NAME", property="gsName", jdbcType=JdbcType.VARCHAR),
        @Result(column="TIMESEC_OFFSET", property="timesecOffset", jdbcType=JdbcType.INTEGER),
        @Result(column="GS_ORDER", property="gsOrder", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEXT_ORDERS", property="nextOrders", jdbcType=JdbcType.VARCHAR),
        @Result(column="STATE", property="state", jdbcType=JdbcType.VARCHAR)
    })
    List<TLTIssueStatusParams> selectByExample(TLTIssueStatusParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_STATUS_PARAMS
     *
     * @mbggenerated Sun Apr 10 12:52:14 CST 2016
     */
    @Select({
        "select",
        "GEN_ID, LTYPE, GS_ECODE, GS_NAME, TIMESEC_OFFSET, GS_ORDER, NEXT_ORDERS, STATE",
        "from TLT_ISSUE_STATUS_PARAMS",
        "where GEN_ID = #{genId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="GEN_ID", property="genId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="LTYPE", property="ltype", jdbcType=JdbcType.VARCHAR),
        @Result(column="GS_ECODE", property="gsEcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="GS_NAME", property="gsName", jdbcType=JdbcType.VARCHAR),
        @Result(column="TIMESEC_OFFSET", property="timesecOffset", jdbcType=JdbcType.INTEGER),
        @Result(column="GS_ORDER", property="gsOrder", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEXT_ORDERS", property="nextOrders", jdbcType=JdbcType.VARCHAR),
        @Result(column="STATE", property="state", jdbcType=JdbcType.VARCHAR)
    })
    TLTIssueStatusParams selectByPrimaryKey(TLTIssueStatusParamsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_STATUS_PARAMS
     *
     * @mbggenerated Sun Apr 10 12:52:14 CST 2016
     */
    @UpdateProvider(type=TLTIssueStatusParamsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TLTIssueStatusParams record, @Param("example") TLTIssueStatusParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_STATUS_PARAMS
     *
     * @mbggenerated Sun Apr 10 12:52:14 CST 2016
     */
    @UpdateProvider(type=TLTIssueStatusParamsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TLTIssueStatusParams record, @Param("example") TLTIssueStatusParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_STATUS_PARAMS
     *
     * @mbggenerated Sun Apr 10 12:52:14 CST 2016
     */
    @UpdateProvider(type=TLTIssueStatusParamsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TLTIssueStatusParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_STATUS_PARAMS
     *
     * @mbggenerated Sun Apr 10 12:52:14 CST 2016
     */
    @Update({
        "update TLT_ISSUE_STATUS_PARAMS",
        "set LTYPE = #{ltype,jdbcType=VARCHAR},",
          "GS_ECODE = #{gsEcode,jdbcType=VARCHAR},",
          "GS_NAME = #{gsName,jdbcType=VARCHAR},",
          "TIMESEC_OFFSET = #{timesecOffset,jdbcType=INTEGER},",
          "GS_ORDER = #{gsOrder,jdbcType=VARCHAR},",
          "NEXT_ORDERS = #{nextOrders,jdbcType=VARCHAR},",
          "STATE = #{state,jdbcType=VARCHAR}",
        "where GEN_ID = #{genId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TLTIssueStatusParams record);
}