package starstart.cgame.flows.mysqlgens.sett.entity;

import cn.msec.ojpa.api.annotations.Tab;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_SETT_RE_TASK")
@AllArgsConstructor
@NoArgsConstructor
public class SettReTask extends SettReTaskKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_RE_TASK.SETT_DATE
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    private String settDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_RE_TASK.IS_DB_BACKUP
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    private String isDbBackup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_RE_TASK.STATUS
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_RE_TASK.REASON
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_RE_TASK.OPER_ID
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_RE_TASK.CREATE_DATE
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_RE_TASK.UPDATE_DATE
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_RE_TASK.TASK_TYPE
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    private String taskType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_RE_TASK.SETT_DATE
     *
     * @return the value of T_SETT_RE_TASK.SETT_DATE
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public String getSettDate() {
        return settDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_RE_TASK.SETT_DATE
     *
     * @param settDate the value for T_SETT_RE_TASK.SETT_DATE
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public void setSettDate(String settDate) {
        this.settDate = settDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_RE_TASK.IS_DB_BACKUP
     *
     * @return the value of T_SETT_RE_TASK.IS_DB_BACKUP
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public String getIsDbBackup() {
        return isDbBackup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_RE_TASK.IS_DB_BACKUP
     *
     * @param isDbBackup the value for T_SETT_RE_TASK.IS_DB_BACKUP
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public void setIsDbBackup(String isDbBackup) {
        this.isDbBackup = isDbBackup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_RE_TASK.STATUS
     *
     * @return the value of T_SETT_RE_TASK.STATUS
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_RE_TASK.STATUS
     *
     * @param status the value for T_SETT_RE_TASK.STATUS
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_RE_TASK.REASON
     *
     * @return the value of T_SETT_RE_TASK.REASON
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_RE_TASK.REASON
     *
     * @param reason the value for T_SETT_RE_TASK.REASON
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_RE_TASK.OPER_ID
     *
     * @return the value of T_SETT_RE_TASK.OPER_ID
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_RE_TASK.OPER_ID
     *
     * @param operId the value for T_SETT_RE_TASK.OPER_ID
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public void setOperId(String operId) {
        this.operId = operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_RE_TASK.CREATE_DATE
     *
     * @return the value of T_SETT_RE_TASK.CREATE_DATE
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_RE_TASK.CREATE_DATE
     *
     * @param createDate the value for T_SETT_RE_TASK.CREATE_DATE
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_RE_TASK.UPDATE_DATE
     *
     * @return the value of T_SETT_RE_TASK.UPDATE_DATE
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_RE_TASK.UPDATE_DATE
     *
     * @param updateDate the value for T_SETT_RE_TASK.UPDATE_DATE
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_RE_TASK.TASK_TYPE
     *
     * @return the value of T_SETT_RE_TASK.TASK_TYPE
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_RE_TASK.TASK_TYPE
     *
     * @param taskType the value for T_SETT_RE_TASK.TASK_TYPE
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_RE_TASK
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SettReTask other = (SettReTask) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSettDate() == null ? other.getSettDate() == null : this.getSettDate().equals(other.getSettDate()))
            && (this.getIsDbBackup() == null ? other.getIsDbBackup() == null : this.getIsDbBackup().equals(other.getIsDbBackup()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getReason() == null ? other.getReason() == null : this.getReason().equals(other.getReason()))
            && (this.getOperId() == null ? other.getOperId() == null : this.getOperId().equals(other.getOperId()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getTaskType() == null ? other.getTaskType() == null : this.getTaskType().equals(other.getTaskType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_RE_TASK
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSettDate() == null) ? 0 : getSettDate().hashCode());
        result = prime * result + ((getIsDbBackup() == null) ? 0 : getIsDbBackup().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getReason() == null) ? 0 : getReason().hashCode());
        result = prime * result + ((getOperId() == null) ? 0 : getOperId().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getTaskType() == null) ? 0 : getTaskType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_RE_TASK
     *
     * @mbggenerated Thu Jun 18 09:10:26 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", settDate=").append(settDate);
        sb.append(", isDbBackup=").append(isDbBackup);
        sb.append(", status=").append(status);
        sb.append(", reason=").append(reason);
        sb.append(", operId=").append(operId);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", taskType=").append(taskType);
        sb.append("]");
        return sb.toString();
    }
}