package starstart.cgame.flows.mysqlgens.sett.entity;

import cn.msec.ojpa.api.annotations.Tab;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_SETT_TASK_RUN")
@AllArgsConstructor
@NoArgsConstructor
public class SettTaskRun extends SettTaskRunKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.TASK_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.TASK_DEF_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String taskDefId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.VERSION
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.CRT_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.UPD_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private Date updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.FIELD
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.DSC
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String dsc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.ROOT_RUNID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String rootRunid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.NEXT_RUNID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String nextRunid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.REF_ID1
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String refId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.REF_ID2
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String refId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_TASK_RUN.SETTLE_DT
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String settleDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.TASK_TYPE
     *
     * @return the value of T_SETT_TASK_RUN.TASK_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.TASK_TYPE
     *
     * @param taskType the value for T_SETT_TASK_RUN.TASK_TYPE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.TASK_DEF_ID
     *
     * @return the value of T_SETT_TASK_RUN.TASK_DEF_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getTaskDefId() {
        return taskDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.TASK_DEF_ID
     *
     * @param taskDefId the value for T_SETT_TASK_RUN.TASK_DEF_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setTaskDefId(String taskDefId) {
        this.taskDefId = taskDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.VERSION
     *
     * @return the value of T_SETT_TASK_RUN.VERSION
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.VERSION
     *
     * @param version the value for T_SETT_TASK_RUN.VERSION
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.STATUS
     *
     * @return the value of T_SETT_TASK_RUN.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.STATUS
     *
     * @param status the value for T_SETT_TASK_RUN.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.CRT_TIME
     *
     * @return the value of T_SETT_TASK_RUN.CRT_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.CRT_TIME
     *
     * @param crtTime the value for T_SETT_TASK_RUN.CRT_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.UPD_TIME
     *
     * @return the value of T_SETT_TASK_RUN.UPD_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.UPD_TIME
     *
     * @param updTime the value for T_SETT_TASK_RUN.UPD_TIME
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.FIELD
     *
     * @return the value of T_SETT_TASK_RUN.FIELD
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.FIELD
     *
     * @param field the value for T_SETT_TASK_RUN.FIELD
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setField(String field) {
        this.field = field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.DSC
     *
     * @return the value of T_SETT_TASK_RUN.DSC
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getDsc() {
        return dsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.DSC
     *
     * @param dsc the value for T_SETT_TASK_RUN.DSC
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setDsc(String dsc) {
        this.dsc = dsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.ROOT_RUNID
     *
     * @return the value of T_SETT_TASK_RUN.ROOT_RUNID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getRootRunid() {
        return rootRunid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.ROOT_RUNID
     *
     * @param rootRunid the value for T_SETT_TASK_RUN.ROOT_RUNID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setRootRunid(String rootRunid) {
        this.rootRunid = rootRunid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.NEXT_RUNID
     *
     * @return the value of T_SETT_TASK_RUN.NEXT_RUNID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getNextRunid() {
        return nextRunid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.NEXT_RUNID
     *
     * @param nextRunid the value for T_SETT_TASK_RUN.NEXT_RUNID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setNextRunid(String nextRunid) {
        this.nextRunid = nextRunid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.REF_ID1
     *
     * @return the value of T_SETT_TASK_RUN.REF_ID1
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getRefId1() {
        return refId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.REF_ID1
     *
     * @param refId1 the value for T_SETT_TASK_RUN.REF_ID1
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setRefId1(String refId1) {
        this.refId1 = refId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.REF_ID2
     *
     * @return the value of T_SETT_TASK_RUN.REF_ID2
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getRefId2() {
        return refId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.REF_ID2
     *
     * @param refId2 the value for T_SETT_TASK_RUN.REF_ID2
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setRefId2(String refId2) {
        this.refId2 = refId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_TASK_RUN.SETTLE_DT
     *
     * @return the value of T_SETT_TASK_RUN.SETTLE_DT
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getSettleDt() {
        return settleDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_TASK_RUN.SETTLE_DT
     *
     * @param settleDt the value for T_SETT_TASK_RUN.SETTLE_DT
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setSettleDt(String settleDt) {
        this.settleDt = settleDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_RUN
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SettTaskRun other = (SettTaskRun) that;
        return (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
            && (this.getTaskType() == null ? other.getTaskType() == null : this.getTaskType().equals(other.getTaskType()))
            && (this.getTaskDefId() == null ? other.getTaskDefId() == null : this.getTaskDefId().equals(other.getTaskDefId()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCrtTime() == null ? other.getCrtTime() == null : this.getCrtTime().equals(other.getCrtTime()))
            && (this.getUpdTime() == null ? other.getUpdTime() == null : this.getUpdTime().equals(other.getUpdTime()))
            && (this.getField() == null ? other.getField() == null : this.getField().equals(other.getField()))
            && (this.getDsc() == null ? other.getDsc() == null : this.getDsc().equals(other.getDsc()))
            && (this.getRootRunid() == null ? other.getRootRunid() == null : this.getRootRunid().equals(other.getRootRunid()))
            && (this.getNextRunid() == null ? other.getNextRunid() == null : this.getNextRunid().equals(other.getNextRunid()))
            && (this.getRefId1() == null ? other.getRefId1() == null : this.getRefId1().equals(other.getRefId1()))
            && (this.getRefId2() == null ? other.getRefId2() == null : this.getRefId2().equals(other.getRefId2()))
            && (this.getSettleDt() == null ? other.getSettleDt() == null : this.getSettleDt().equals(other.getSettleDt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_RUN
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getTaskType() == null) ? 0 : getTaskType().hashCode());
        result = prime * result + ((getTaskDefId() == null) ? 0 : getTaskDefId().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCrtTime() == null) ? 0 : getCrtTime().hashCode());
        result = prime * result + ((getUpdTime() == null) ? 0 : getUpdTime().hashCode());
        result = prime * result + ((getField() == null) ? 0 : getField().hashCode());
        result = prime * result + ((getDsc() == null) ? 0 : getDsc().hashCode());
        result = prime * result + ((getRootRunid() == null) ? 0 : getRootRunid().hashCode());
        result = prime * result + ((getNextRunid() == null) ? 0 : getNextRunid().hashCode());
        result = prime * result + ((getRefId1() == null) ? 0 : getRefId1().hashCode());
        result = prime * result + ((getRefId2() == null) ? 0 : getRefId2().hashCode());
        result = prime * result + ((getSettleDt() == null) ? 0 : getSettleDt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_RUN
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", taskType=").append(taskType);
        sb.append(", taskDefId=").append(taskDefId);
        sb.append(", version=").append(version);
        sb.append(", status=").append(status);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", updTime=").append(updTime);
        sb.append(", field=").append(field);
        sb.append(", dsc=").append(dsc);
        sb.append(", rootRunid=").append(rootRunid);
        sb.append(", nextRunid=").append(nextRunid);
        sb.append(", refId1=").append(refId1);
        sb.append(", refId2=").append(refId2);
        sb.append(", settleDt=").append(settleDt);
        sb.append("]");
        return sb.toString();
    }
}