package starstart.cgame.flows.mysqlgens.sett.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class SettTaskDefExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public SettTaskDefExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaskDefIdIsNull() {
            addCriterion("TASK_DEF_ID is null");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdIsNotNull() {
            addCriterion("TASK_DEF_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdEqualTo(String value) {
            addCriterion("TASK_DEF_ID =", value, "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdNotEqualTo(String value) {
            addCriterion("TASK_DEF_ID <>", value, "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdGreaterThan(String value) {
            addCriterion("TASK_DEF_ID >", value, "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdGreaterThanOrEqualTo(String value) {
            addCriterion("TASK_DEF_ID >=", value, "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdLessThan(String value) {
            addCriterion("TASK_DEF_ID <", value, "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdLessThanOrEqualTo(String value) {
            addCriterion("TASK_DEF_ID <=", value, "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdLike(String value) {
            addCriterion("TASK_DEF_ID like", value, "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdNotLike(String value) {
            addCriterion("TASK_DEF_ID not like", value, "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdIn(List<String> values) {
            addCriterion("TASK_DEF_ID in", values, "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdNotIn(List<String> values) {
            addCriterion("TASK_DEF_ID not in", values, "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdBetween(String value1, String value2) {
            addCriterion("TASK_DEF_ID between", value1, value2, "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdNotBetween(String value1, String value2) {
            addCriterion("TASK_DEF_ID not between", value1, value2, "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIsNull() {
            addCriterion("TASK_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIsNotNull() {
            addCriterion("TASK_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTaskTypeEqualTo(String value) {
            addCriterion("TASK_TYPE =", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotEqualTo(String value) {
            addCriterion("TASK_TYPE <>", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeGreaterThan(String value) {
            addCriterion("TASK_TYPE >", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TASK_TYPE >=", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLessThan(String value) {
            addCriterion("TASK_TYPE <", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLessThanOrEqualTo(String value) {
            addCriterion("TASK_TYPE <=", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLike(String value) {
            addCriterion("TASK_TYPE like", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotLike(String value) {
            addCriterion("TASK_TYPE not like", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIn(List<String> values) {
            addCriterion("TASK_TYPE in", values, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotIn(List<String> values) {
            addCriterion("TASK_TYPE not in", values, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeBetween(String value1, String value2) {
            addCriterion("TASK_TYPE between", value1, value2, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotBetween(String value1, String value2) {
            addCriterion("TASK_TYPE not between", value1, value2, "taskType");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("VERSION like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("VERSION not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNull() {
            addCriterion("CRT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNotNull() {
            addCriterion("CRT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeEqualTo(Date value) {
            addCriterion("CRT_TIME =", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotEqualTo(Date value) {
            addCriterion("CRT_TIME <>", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThan(Date value) {
            addCriterion("CRT_TIME >", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CRT_TIME >=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThan(Date value) {
            addCriterion("CRT_TIME <", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThanOrEqualTo(Date value) {
            addCriterion("CRT_TIME <=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIn(List<Date> values) {
            addCriterion("CRT_TIME in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotIn(List<Date> values) {
            addCriterion("CRT_TIME not in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeBetween(Date value1, Date value2) {
            addCriterion("CRT_TIME between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotBetween(Date value1, Date value2) {
            addCriterion("CRT_TIME not between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNull() {
            addCriterion("UPD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNotNull() {
            addCriterion("UPD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeEqualTo(Date value) {
            addCriterion("UPD_TIME =", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotEqualTo(Date value) {
            addCriterion("UPD_TIME <>", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThan(Date value) {
            addCriterion("UPD_TIME >", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_TIME >=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThan(Date value) {
            addCriterion("UPD_TIME <", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPD_TIME <=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIn(List<Date> values) {
            addCriterion("UPD_TIME in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotIn(List<Date> values) {
            addCriterion("UPD_TIME not in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeBetween(Date value1, Date value2) {
            addCriterion("UPD_TIME between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPD_TIME not between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andDscIsNull() {
            addCriterion("DSC is null");
            return (Criteria) this;
        }

        public Criteria andDscIsNotNull() {
            addCriterion("DSC is not null");
            return (Criteria) this;
        }

        public Criteria andDscEqualTo(String value) {
            addCriterion("DSC =", value, "dsc");
            return (Criteria) this;
        }

        public Criteria andDscNotEqualTo(String value) {
            addCriterion("DSC <>", value, "dsc");
            return (Criteria) this;
        }

        public Criteria andDscGreaterThan(String value) {
            addCriterion("DSC >", value, "dsc");
            return (Criteria) this;
        }

        public Criteria andDscGreaterThanOrEqualTo(String value) {
            addCriterion("DSC >=", value, "dsc");
            return (Criteria) this;
        }

        public Criteria andDscLessThan(String value) {
            addCriterion("DSC <", value, "dsc");
            return (Criteria) this;
        }

        public Criteria andDscLessThanOrEqualTo(String value) {
            addCriterion("DSC <=", value, "dsc");
            return (Criteria) this;
        }

        public Criteria andDscLike(String value) {
            addCriterion("DSC like", value, "dsc");
            return (Criteria) this;
        }

        public Criteria andDscNotLike(String value) {
            addCriterion("DSC not like", value, "dsc");
            return (Criteria) this;
        }

        public Criteria andDscIn(List<String> values) {
            addCriterion("DSC in", values, "dsc");
            return (Criteria) this;
        }

        public Criteria andDscNotIn(List<String> values) {
            addCriterion("DSC not in", values, "dsc");
            return (Criteria) this;
        }

        public Criteria andDscBetween(String value1, String value2) {
            addCriterion("DSC between", value1, value2, "dsc");
            return (Criteria) this;
        }

        public Criteria andDscNotBetween(String value1, String value2) {
            addCriterion("DSC not between", value1, value2, "dsc");
            return (Criteria) this;
        }

        public Criteria andRootDefidIsNull() {
            addCriterion("ROOT_DEFID is null");
            return (Criteria) this;
        }

        public Criteria andRootDefidIsNotNull() {
            addCriterion("ROOT_DEFID is not null");
            return (Criteria) this;
        }

        public Criteria andRootDefidEqualTo(String value) {
            addCriterion("ROOT_DEFID =", value, "rootDefid");
            return (Criteria) this;
        }

        public Criteria andRootDefidNotEqualTo(String value) {
            addCriterion("ROOT_DEFID <>", value, "rootDefid");
            return (Criteria) this;
        }

        public Criteria andRootDefidGreaterThan(String value) {
            addCriterion("ROOT_DEFID >", value, "rootDefid");
            return (Criteria) this;
        }

        public Criteria andRootDefidGreaterThanOrEqualTo(String value) {
            addCriterion("ROOT_DEFID >=", value, "rootDefid");
            return (Criteria) this;
        }

        public Criteria andRootDefidLessThan(String value) {
            addCriterion("ROOT_DEFID <", value, "rootDefid");
            return (Criteria) this;
        }

        public Criteria andRootDefidLessThanOrEqualTo(String value) {
            addCriterion("ROOT_DEFID <=", value, "rootDefid");
            return (Criteria) this;
        }

        public Criteria andRootDefidLike(String value) {
            addCriterion("ROOT_DEFID like", value, "rootDefid");
            return (Criteria) this;
        }

        public Criteria andRootDefidNotLike(String value) {
            addCriterion("ROOT_DEFID not like", value, "rootDefid");
            return (Criteria) this;
        }

        public Criteria andRootDefidIn(List<String> values) {
            addCriterion("ROOT_DEFID in", values, "rootDefid");
            return (Criteria) this;
        }

        public Criteria andRootDefidNotIn(List<String> values) {
            addCriterion("ROOT_DEFID not in", values, "rootDefid");
            return (Criteria) this;
        }

        public Criteria andRootDefidBetween(String value1, String value2) {
            addCriterion("ROOT_DEFID between", value1, value2, "rootDefid");
            return (Criteria) this;
        }

        public Criteria andRootDefidNotBetween(String value1, String value2) {
            addCriterion("ROOT_DEFID not between", value1, value2, "rootDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidIsNull() {
            addCriterion("NEXT_DEFID is null");
            return (Criteria) this;
        }

        public Criteria andNextDefidIsNotNull() {
            addCriterion("NEXT_DEFID is not null");
            return (Criteria) this;
        }

        public Criteria andNextDefidEqualTo(String value) {
            addCriterion("NEXT_DEFID =", value, "nextDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidNotEqualTo(String value) {
            addCriterion("NEXT_DEFID <>", value, "nextDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidGreaterThan(String value) {
            addCriterion("NEXT_DEFID >", value, "nextDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidGreaterThanOrEqualTo(String value) {
            addCriterion("NEXT_DEFID >=", value, "nextDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidLessThan(String value) {
            addCriterion("NEXT_DEFID <", value, "nextDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidLessThanOrEqualTo(String value) {
            addCriterion("NEXT_DEFID <=", value, "nextDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidLike(String value) {
            addCriterion("NEXT_DEFID like", value, "nextDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidNotLike(String value) {
            addCriterion("NEXT_DEFID not like", value, "nextDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidIn(List<String> values) {
            addCriterion("NEXT_DEFID in", values, "nextDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidNotIn(List<String> values) {
            addCriterion("NEXT_DEFID not in", values, "nextDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidBetween(String value1, String value2) {
            addCriterion("NEXT_DEFID between", value1, value2, "nextDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidNotBetween(String value1, String value2) {
            addCriterion("NEXT_DEFID not between", value1, value2, "nextDefid");
            return (Criteria) this;
        }

        public Criteria andParamId1IsNull() {
            addCriterion("PARAM_ID1 is null");
            return (Criteria) this;
        }

        public Criteria andParamId1IsNotNull() {
            addCriterion("PARAM_ID1 is not null");
            return (Criteria) this;
        }

        public Criteria andParamId1EqualTo(String value) {
            addCriterion("PARAM_ID1 =", value, "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId1NotEqualTo(String value) {
            addCriterion("PARAM_ID1 <>", value, "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId1GreaterThan(String value) {
            addCriterion("PARAM_ID1 >", value, "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId1GreaterThanOrEqualTo(String value) {
            addCriterion("PARAM_ID1 >=", value, "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId1LessThan(String value) {
            addCriterion("PARAM_ID1 <", value, "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId1LessThanOrEqualTo(String value) {
            addCriterion("PARAM_ID1 <=", value, "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId1Like(String value) {
            addCriterion("PARAM_ID1 like", value, "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId1NotLike(String value) {
            addCriterion("PARAM_ID1 not like", value, "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId1In(List<String> values) {
            addCriterion("PARAM_ID1 in", values, "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId1NotIn(List<String> values) {
            addCriterion("PARAM_ID1 not in", values, "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId1Between(String value1, String value2) {
            addCriterion("PARAM_ID1 between", value1, value2, "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId1NotBetween(String value1, String value2) {
            addCriterion("PARAM_ID1 not between", value1, value2, "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId2IsNull() {
            addCriterion("PARAM_ID2 is null");
            return (Criteria) this;
        }

        public Criteria andParamId2IsNotNull() {
            addCriterion("PARAM_ID2 is not null");
            return (Criteria) this;
        }

        public Criteria andParamId2EqualTo(String value) {
            addCriterion("PARAM_ID2 =", value, "paramId2");
            return (Criteria) this;
        }

        public Criteria andParamId2NotEqualTo(String value) {
            addCriterion("PARAM_ID2 <>", value, "paramId2");
            return (Criteria) this;
        }

        public Criteria andParamId2GreaterThan(String value) {
            addCriterion("PARAM_ID2 >", value, "paramId2");
            return (Criteria) this;
        }

        public Criteria andParamId2GreaterThanOrEqualTo(String value) {
            addCriterion("PARAM_ID2 >=", value, "paramId2");
            return (Criteria) this;
        }

        public Criteria andParamId2LessThan(String value) {
            addCriterion("PARAM_ID2 <", value, "paramId2");
            return (Criteria) this;
        }

        public Criteria andParamId2LessThanOrEqualTo(String value) {
            addCriterion("PARAM_ID2 <=", value, "paramId2");
            return (Criteria) this;
        }

        public Criteria andParamId2Like(String value) {
            addCriterion("PARAM_ID2 like", value, "paramId2");
            return (Criteria) this;
        }

        public Criteria andParamId2NotLike(String value) {
            addCriterion("PARAM_ID2 not like", value, "paramId2");
            return (Criteria) this;
        }

        public Criteria andParamId2In(List<String> values) {
            addCriterion("PARAM_ID2 in", values, "paramId2");
            return (Criteria) this;
        }

        public Criteria andParamId2NotIn(List<String> values) {
            addCriterion("PARAM_ID2 not in", values, "paramId2");
            return (Criteria) this;
        }

        public Criteria andParamId2Between(String value1, String value2) {
            addCriterion("PARAM_ID2 between", value1, value2, "paramId2");
            return (Criteria) this;
        }

        public Criteria andParamId2NotBetween(String value1, String value2) {
            addCriterion("PARAM_ID2 not between", value1, value2, "paramId2");
            return (Criteria) this;
        }

        public Criteria andTaskDefIdLikeInsensitive(String value) {
            addCriterion("upper(TASK_DEF_ID) like", value.toUpperCase(), "taskDefId");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLikeInsensitive(String value) {
            addCriterion("upper(TASK_TYPE) like", value.toUpperCase(), "taskType");
            return (Criteria) this;
        }

        public Criteria andVersionLikeInsensitive(String value) {
            addCriterion("upper(VERSION) like", value.toUpperCase(), "version");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(STATUS) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andDscLikeInsensitive(String value) {
            addCriterion("upper(DSC) like", value.toUpperCase(), "dsc");
            return (Criteria) this;
        }

        public Criteria andRootDefidLikeInsensitive(String value) {
            addCriterion("upper(ROOT_DEFID) like", value.toUpperCase(), "rootDefid");
            return (Criteria) this;
        }

        public Criteria andNextDefidLikeInsensitive(String value) {
            addCriterion("upper(NEXT_DEFID) like", value.toUpperCase(), "nextDefid");
            return (Criteria) this;
        }

        public Criteria andParamId1LikeInsensitive(String value) {
            addCriterion("upper(PARAM_ID1) like", value.toUpperCase(), "paramId1");
            return (Criteria) this;
        }

        public Criteria andParamId2LikeInsensitive(String value) {
            addCriterion("upper(PARAM_ID2) like", value.toUpperCase(), "paramId2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 08 20:40:16 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SETT_TASK_DEF
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}