package starstart.cgame.flows.mysqlgens.sett.entity;

import cn.msec.ojpa.api.annotations.Tab;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_SETT_USER_PROD_DETAILS")
@AllArgsConstructor
@NoArgsConstructor
public class SettUserProdDetails extends SettUserProdDetailsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String mchntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.USER_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.SETTLE_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String settleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.VALUE_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String valueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.DIG_ACCT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String digAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.TOTAMT_SY
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private BigDecimal totamtSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.YESTD_TOTAMT_SY
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private BigDecimal yestdTotamtSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SY
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private BigDecimal todayTotamtSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_FE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private BigDecimal todayTotamtFe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SG
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private BigDecimal todayTotamtSg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SH
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private BigDecimal todayTotamtSh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTCNT_SG
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private BigDecimal todayTotcntSg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTCNT_SH
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private BigDecimal todayTotcntSh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.DAYFE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private BigDecimal dayfe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.TODAY_FE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private BigDecimal todayFe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.RECORD_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String recordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.OUT_PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String outProdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.OUT_SUB_PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private String outSubProdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.NO_VALUE_FE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private BigDecimal noValueFe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_USER_PROD_DETAILS.SUBSTRACT_VALUE_FE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    private BigDecimal substractValueFe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.MCHNT_ID
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getMchntId() {
        return mchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.MCHNT_ID
     *
     * @param mchntId the value for T_SETT_USER_PROD_DETAILS.MCHNT_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setMchntId(String mchntId) {
        this.mchntId = mchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.USER_ID
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.USER_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.USER_ID
     *
     * @param userId the value for T_SETT_USER_PROD_DETAILS.USER_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.PROD_ID
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.PROD_ID
     *
     * @param prodId the value for T_SETT_USER_PROD_DETAILS.PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setProdId(String prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.SETTLE_DATE
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.SETTLE_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getSettleDate() {
        return settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.SETTLE_DATE
     *
     * @param settleDate the value for T_SETT_USER_PROD_DETAILS.SETTLE_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setSettleDate(String settleDate) {
        this.settleDate = settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.VALUE_DATE
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.VALUE_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getValueDate() {
        return valueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.VALUE_DATE
     *
     * @param valueDate the value for T_SETT_USER_PROD_DETAILS.VALUE_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setValueDate(String valueDate) {
        this.valueDate = valueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.DIG_ACCT_NO
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.DIG_ACCT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getDigAcctNo() {
        return digAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.DIG_ACCT_NO
     *
     * @param digAcctNo the value for T_SETT_USER_PROD_DETAILS.DIG_ACCT_NO
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setDigAcctNo(String digAcctNo) {
        this.digAcctNo = digAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.TOTAMT_SY
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.TOTAMT_SY
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public BigDecimal getTotamtSy() {
        return totamtSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.TOTAMT_SY
     *
     * @param totamtSy the value for T_SETT_USER_PROD_DETAILS.TOTAMT_SY
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setTotamtSy(BigDecimal totamtSy) {
        this.totamtSy = totamtSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.YESTD_TOTAMT_SY
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.YESTD_TOTAMT_SY
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public BigDecimal getYestdTotamtSy() {
        return yestdTotamtSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.YESTD_TOTAMT_SY
     *
     * @param yestdTotamtSy the value for T_SETT_USER_PROD_DETAILS.YESTD_TOTAMT_SY
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setYestdTotamtSy(BigDecimal yestdTotamtSy) {
        this.yestdTotamtSy = yestdTotamtSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SY
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SY
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public BigDecimal getTodayTotamtSy() {
        return todayTotamtSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SY
     *
     * @param todayTotamtSy the value for T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SY
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setTodayTotamtSy(BigDecimal todayTotamtSy) {
        this.todayTotamtSy = todayTotamtSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_FE
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_FE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public BigDecimal getTodayTotamtFe() {
        return todayTotamtFe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_FE
     *
     * @param todayTotamtFe the value for T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_FE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setTodayTotamtFe(BigDecimal todayTotamtFe) {
        this.todayTotamtFe = todayTotamtFe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SG
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SG
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public BigDecimal getTodayTotamtSg() {
        return todayTotamtSg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SG
     *
     * @param todayTotamtSg the value for T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SG
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setTodayTotamtSg(BigDecimal todayTotamtSg) {
        this.todayTotamtSg = todayTotamtSg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SH
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SH
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public BigDecimal getTodayTotamtSh() {
        return todayTotamtSh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SH
     *
     * @param todayTotamtSh the value for T_SETT_USER_PROD_DETAILS.TODAY_TOTAMT_SH
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setTodayTotamtSh(BigDecimal todayTotamtSh) {
        this.todayTotamtSh = todayTotamtSh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTCNT_SG
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.TODAY_TOTCNT_SG
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public BigDecimal getTodayTotcntSg() {
        return todayTotcntSg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTCNT_SG
     *
     * @param todayTotcntSg the value for T_SETT_USER_PROD_DETAILS.TODAY_TOTCNT_SG
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setTodayTotcntSg(BigDecimal todayTotcntSg) {
        this.todayTotcntSg = todayTotcntSg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTCNT_SH
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.TODAY_TOTCNT_SH
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public BigDecimal getTodayTotcntSh() {
        return todayTotcntSh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_TOTCNT_SH
     *
     * @param todayTotcntSh the value for T_SETT_USER_PROD_DETAILS.TODAY_TOTCNT_SH
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setTodayTotcntSh(BigDecimal todayTotcntSh) {
        this.todayTotcntSh = todayTotcntSh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.DAYFE
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.DAYFE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public BigDecimal getDayfe() {
        return dayfe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.DAYFE
     *
     * @param dayfe the value for T_SETT_USER_PROD_DETAILS.DAYFE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setDayfe(BigDecimal dayfe) {
        this.dayfe = dayfe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_FE
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.TODAY_FE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public BigDecimal getTodayFe() {
        return todayFe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.TODAY_FE
     *
     * @param todayFe the value for T_SETT_USER_PROD_DETAILS.TODAY_FE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setTodayFe(BigDecimal todayFe) {
        this.todayFe = todayFe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.RECORD_DATE
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.RECORD_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.RECORD_DATE
     *
     * @param recordDate the value for T_SETT_USER_PROD_DETAILS.RECORD_DATE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setRecordDate(String recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.STATUS
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.STATUS
     *
     * @param status the value for T_SETT_USER_PROD_DETAILS.STATUS
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.OUT_PROD_ID
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.OUT_PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getOutProdId() {
        return outProdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.OUT_PROD_ID
     *
     * @param outProdId the value for T_SETT_USER_PROD_DETAILS.OUT_PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setOutProdId(String outProdId) {
        this.outProdId = outProdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.OUT_SUB_PROD_ID
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.OUT_SUB_PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public String getOutSubProdId() {
        return outSubProdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.OUT_SUB_PROD_ID
     *
     * @param outSubProdId the value for T_SETT_USER_PROD_DETAILS.OUT_SUB_PROD_ID
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setOutSubProdId(String outSubProdId) {
        this.outSubProdId = outSubProdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.NO_VALUE_FE
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.NO_VALUE_FE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public BigDecimal getNoValueFe() {
        return noValueFe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.NO_VALUE_FE
     *
     * @param noValueFe the value for T_SETT_USER_PROD_DETAILS.NO_VALUE_FE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setNoValueFe(BigDecimal noValueFe) {
        this.noValueFe = noValueFe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_USER_PROD_DETAILS.SUBSTRACT_VALUE_FE
     *
     * @return the value of T_SETT_USER_PROD_DETAILS.SUBSTRACT_VALUE_FE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public BigDecimal getSubstractValueFe() {
        return substractValueFe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_USER_PROD_DETAILS.SUBSTRACT_VALUE_FE
     *
     * @param substractValueFe the value for T_SETT_USER_PROD_DETAILS.SUBSTRACT_VALUE_FE
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    public void setSubstractValueFe(BigDecimal substractValueFe) {
        this.substractValueFe = substractValueFe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_USER_PROD_DETAILS
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SettUserProdDetails other = (SettUserProdDetails) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMchntId() == null ? other.getMchntId() == null : this.getMchntId().equals(other.getMchntId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getProdId() == null ? other.getProdId() == null : this.getProdId().equals(other.getProdId()))
            && (this.getSettleDate() == null ? other.getSettleDate() == null : this.getSettleDate().equals(other.getSettleDate()))
            && (this.getValueDate() == null ? other.getValueDate() == null : this.getValueDate().equals(other.getValueDate()))
            && (this.getDigAcctNo() == null ? other.getDigAcctNo() == null : this.getDigAcctNo().equals(other.getDigAcctNo()))
            && (this.getTotamtSy() == null ? other.getTotamtSy() == null : this.getTotamtSy().equals(other.getTotamtSy()))
            && (this.getYestdTotamtSy() == null ? other.getYestdTotamtSy() == null : this.getYestdTotamtSy().equals(other.getYestdTotamtSy()))
            && (this.getTodayTotamtSy() == null ? other.getTodayTotamtSy() == null : this.getTodayTotamtSy().equals(other.getTodayTotamtSy()))
            && (this.getTodayTotamtFe() == null ? other.getTodayTotamtFe() == null : this.getTodayTotamtFe().equals(other.getTodayTotamtFe()))
            && (this.getTodayTotamtSg() == null ? other.getTodayTotamtSg() == null : this.getTodayTotamtSg().equals(other.getTodayTotamtSg()))
            && (this.getTodayTotamtSh() == null ? other.getTodayTotamtSh() == null : this.getTodayTotamtSh().equals(other.getTodayTotamtSh()))
            && (this.getTodayTotcntSg() == null ? other.getTodayTotcntSg() == null : this.getTodayTotcntSg().equals(other.getTodayTotcntSg()))
            && (this.getTodayTotcntSh() == null ? other.getTodayTotcntSh() == null : this.getTodayTotcntSh().equals(other.getTodayTotcntSh()))
            && (this.getDayfe() == null ? other.getDayfe() == null : this.getDayfe().equals(other.getDayfe()))
            && (this.getTodayFe() == null ? other.getTodayFe() == null : this.getTodayFe().equals(other.getTodayFe()))
            && (this.getRecordDate() == null ? other.getRecordDate() == null : this.getRecordDate().equals(other.getRecordDate()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getOutProdId() == null ? other.getOutProdId() == null : this.getOutProdId().equals(other.getOutProdId()))
            && (this.getOutSubProdId() == null ? other.getOutSubProdId() == null : this.getOutSubProdId().equals(other.getOutSubProdId()))
            && (this.getNoValueFe() == null ? other.getNoValueFe() == null : this.getNoValueFe().equals(other.getNoValueFe()))
            && (this.getSubstractValueFe() == null ? other.getSubstractValueFe() == null : this.getSubstractValueFe().equals(other.getSubstractValueFe()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_USER_PROD_DETAILS
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMchntId() == null) ? 0 : getMchntId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getProdId() == null) ? 0 : getProdId().hashCode());
        result = prime * result + ((getSettleDate() == null) ? 0 : getSettleDate().hashCode());
        result = prime * result + ((getValueDate() == null) ? 0 : getValueDate().hashCode());
        result = prime * result + ((getDigAcctNo() == null) ? 0 : getDigAcctNo().hashCode());
        result = prime * result + ((getTotamtSy() == null) ? 0 : getTotamtSy().hashCode());
        result = prime * result + ((getYestdTotamtSy() == null) ? 0 : getYestdTotamtSy().hashCode());
        result = prime * result + ((getTodayTotamtSy() == null) ? 0 : getTodayTotamtSy().hashCode());
        result = prime * result + ((getTodayTotamtFe() == null) ? 0 : getTodayTotamtFe().hashCode());
        result = prime * result + ((getTodayTotamtSg() == null) ? 0 : getTodayTotamtSg().hashCode());
        result = prime * result + ((getTodayTotamtSh() == null) ? 0 : getTodayTotamtSh().hashCode());
        result = prime * result + ((getTodayTotcntSg() == null) ? 0 : getTodayTotcntSg().hashCode());
        result = prime * result + ((getTodayTotcntSh() == null) ? 0 : getTodayTotcntSh().hashCode());
        result = prime * result + ((getDayfe() == null) ? 0 : getDayfe().hashCode());
        result = prime * result + ((getTodayFe() == null) ? 0 : getTodayFe().hashCode());
        result = prime * result + ((getRecordDate() == null) ? 0 : getRecordDate().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getOutProdId() == null) ? 0 : getOutProdId().hashCode());
        result = prime * result + ((getOutSubProdId() == null) ? 0 : getOutSubProdId().hashCode());
        result = prime * result + ((getNoValueFe() == null) ? 0 : getNoValueFe().hashCode());
        result = prime * result + ((getSubstractValueFe() == null) ? 0 : getSubstractValueFe().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_USER_PROD_DETAILS
     *
     * @mbggenerated Mon Jun 08 20:40:16 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mchntId=").append(mchntId);
        sb.append(", userId=").append(userId);
        sb.append(", prodId=").append(prodId);
        sb.append(", settleDate=").append(settleDate);
        sb.append(", valueDate=").append(valueDate);
        sb.append(", digAcctNo=").append(digAcctNo);
        sb.append(", totamtSy=").append(totamtSy);
        sb.append(", yestdTotamtSy=").append(yestdTotamtSy);
        sb.append(", todayTotamtSy=").append(todayTotamtSy);
        sb.append(", todayTotamtFe=").append(todayTotamtFe);
        sb.append(", todayTotamtSg=").append(todayTotamtSg);
        sb.append(", todayTotamtSh=").append(todayTotamtSh);
        sb.append(", todayTotcntSg=").append(todayTotcntSg);
        sb.append(", todayTotcntSh=").append(todayTotcntSh);
        sb.append(", dayfe=").append(dayfe);
        sb.append(", todayFe=").append(todayFe);
        sb.append(", recordDate=").append(recordDate);
        sb.append(", status=").append(status);
        sb.append(", outProdId=").append(outProdId);
        sb.append(", outSubProdId=").append(outSubProdId);
        sb.append(", noValueFe=").append(noValueFe);
        sb.append(", substractValueFe=").append(substractValueFe);
        sb.append("]");
        return sb.toString();
    }
}