package starstart.cgame.flows.mysqlgens.sett.entity;

import cn.msec.ojpa.api.annotations.Tab;

import java.math.BigDecimal;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import startstarts.cgame.mysql.CustomDateSerializer;

@Tab(name="T_SETT_PROD_DETAILS")
@AllArgsConstructor
@NoArgsConstructor
public class SettProdDetails extends SettProdDetailsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.PRD_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String prdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.CHANNLE_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String channleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.PROD_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.PRODUCT_TYPE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.SETT_DATE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String settDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.CUST_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.MCHNT_RECORD_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String mchntRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.PROD_RECORD_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String prodRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.TRANS_TYPE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String transType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.TRANS_AMT
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private BigDecimal transAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.FEE_AMT
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private BigDecimal feeAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.TRANS_REQ_DATE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private Date transReqDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.TRANS_RSP_DATE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private Date transRspDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.CERT_NO
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.CERT_TYPE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.VALUE_DATE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String valueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.STATUS
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.PROD_FEE_AMT
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private BigDecimal prodFeeAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.RET_MSG
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String retMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.CRT_TIME
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.UPD_TIME
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private Date updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.REC_STATUS
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String recStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SETT_PROD_DETAILS.FIELD1
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    private String field1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.PRD_ID
     *
     * @return the value of T_SETT_PROD_DETAILS.PRD_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getPrdId() {
        return prdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.PRD_ID
     *
     * @param prdId the value for T_SETT_PROD_DETAILS.PRD_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setPrdId(String prdId) {
        this.prdId = prdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.CHANNLE_ID
     *
     * @return the value of T_SETT_PROD_DETAILS.CHANNLE_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getChannleId() {
        return channleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.CHANNLE_ID
     *
     * @param channleId the value for T_SETT_PROD_DETAILS.CHANNLE_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setChannleId(String channleId) {
        this.channleId = channleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.PROD_ID
     *
     * @return the value of T_SETT_PROD_DETAILS.PROD_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.PROD_ID
     *
     * @param prodId the value for T_SETT_PROD_DETAILS.PROD_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setProdId(String prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.PRODUCT_TYPE
     *
     * @return the value of T_SETT_PROD_DETAILS.PRODUCT_TYPE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.PRODUCT_TYPE
     *
     * @param productType the value for T_SETT_PROD_DETAILS.PRODUCT_TYPE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.SETT_DATE
     *
     * @return the value of T_SETT_PROD_DETAILS.SETT_DATE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getSettDate() {
        return settDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.SETT_DATE
     *
     * @param settDate the value for T_SETT_PROD_DETAILS.SETT_DATE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setSettDate(String settDate) {
        this.settDate = settDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.CUST_ID
     *
     * @return the value of T_SETT_PROD_DETAILS.CUST_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.CUST_ID
     *
     * @param custId the value for T_SETT_PROD_DETAILS.CUST_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setCustId(String custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.MCHNT_RECORD_ID
     *
     * @return the value of T_SETT_PROD_DETAILS.MCHNT_RECORD_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getMchntRecordId() {
        return mchntRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.MCHNT_RECORD_ID
     *
     * @param mchntRecordId the value for T_SETT_PROD_DETAILS.MCHNT_RECORD_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setMchntRecordId(String mchntRecordId) {
        this.mchntRecordId = mchntRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.PROD_RECORD_ID
     *
     * @return the value of T_SETT_PROD_DETAILS.PROD_RECORD_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getProdRecordId() {
        return prodRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.PROD_RECORD_ID
     *
     * @param prodRecordId the value for T_SETT_PROD_DETAILS.PROD_RECORD_ID
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setProdRecordId(String prodRecordId) {
        this.prodRecordId = prodRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.TRANS_TYPE
     *
     * @return the value of T_SETT_PROD_DETAILS.TRANS_TYPE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getTransType() {
        return transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.TRANS_TYPE
     *
     * @param transType the value for T_SETT_PROD_DETAILS.TRANS_TYPE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setTransType(String transType) {
        this.transType = transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.TRANS_AMT
     *
     * @return the value of T_SETT_PROD_DETAILS.TRANS_AMT
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public BigDecimal getTransAmt() {
        return transAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.TRANS_AMT
     *
     * @param transAmt the value for T_SETT_PROD_DETAILS.TRANS_AMT
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setTransAmt(BigDecimal transAmt) {
        this.transAmt = transAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.FEE_AMT
     *
     * @return the value of T_SETT_PROD_DETAILS.FEE_AMT
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public BigDecimal getFeeAmt() {
        return feeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.FEE_AMT
     *
     * @param feeAmt the value for T_SETT_PROD_DETAILS.FEE_AMT
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setFeeAmt(BigDecimal feeAmt) {
        this.feeAmt = feeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.TRANS_REQ_DATE
     *
     * @return the value of T_SETT_PROD_DETAILS.TRANS_REQ_DATE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getTransReqDate() {
        return transReqDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.TRANS_REQ_DATE
     *
     * @param transReqDate the value for T_SETT_PROD_DETAILS.TRANS_REQ_DATE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setTransReqDate(Date transReqDate) {
        this.transReqDate = transReqDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.TRANS_RSP_DATE
     *
     * @return the value of T_SETT_PROD_DETAILS.TRANS_RSP_DATE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getTransRspDate() {
        return transRspDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.TRANS_RSP_DATE
     *
     * @param transRspDate the value for T_SETT_PROD_DETAILS.TRANS_RSP_DATE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setTransRspDate(Date transRspDate) {
        this.transRspDate = transRspDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.CERT_NO
     *
     * @return the value of T_SETT_PROD_DETAILS.CERT_NO
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.CERT_NO
     *
     * @param certNo the value for T_SETT_PROD_DETAILS.CERT_NO
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.CERT_TYPE
     *
     * @return the value of T_SETT_PROD_DETAILS.CERT_TYPE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.CERT_TYPE
     *
     * @param certType the value for T_SETT_PROD_DETAILS.CERT_TYPE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setCertType(String certType) {
        this.certType = certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.VALUE_DATE
     *
     * @return the value of T_SETT_PROD_DETAILS.VALUE_DATE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getValueDate() {
        return valueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.VALUE_DATE
     *
     * @param valueDate the value for T_SETT_PROD_DETAILS.VALUE_DATE
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setValueDate(String valueDate) {
        this.valueDate = valueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.STATUS
     *
     * @return the value of T_SETT_PROD_DETAILS.STATUS
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.STATUS
     *
     * @param status the value for T_SETT_PROD_DETAILS.STATUS
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.PROD_FEE_AMT
     *
     * @return the value of T_SETT_PROD_DETAILS.PROD_FEE_AMT
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public BigDecimal getProdFeeAmt() {
        return prodFeeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.PROD_FEE_AMT
     *
     * @param prodFeeAmt the value for T_SETT_PROD_DETAILS.PROD_FEE_AMT
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setProdFeeAmt(BigDecimal prodFeeAmt) {
        this.prodFeeAmt = prodFeeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.RET_MSG
     *
     * @return the value of T_SETT_PROD_DETAILS.RET_MSG
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getRetMsg() {
        return retMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.RET_MSG
     *
     * @param retMsg the value for T_SETT_PROD_DETAILS.RET_MSG
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setRetMsg(String retMsg) {
        this.retMsg = retMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.CRT_TIME
     *
     * @return the value of T_SETT_PROD_DETAILS.CRT_TIME
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.CRT_TIME
     *
     * @param crtTime the value for T_SETT_PROD_DETAILS.CRT_TIME
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.UPD_TIME
     *
     * @return the value of T_SETT_PROD_DETAILS.UPD_TIME
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.UPD_TIME
     *
     * @param updTime the value for T_SETT_PROD_DETAILS.UPD_TIME
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.REC_STATUS
     *
     * @return the value of T_SETT_PROD_DETAILS.REC_STATUS
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getRecStatus() {
        return recStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.REC_STATUS
     *
     * @param recStatus the value for T_SETT_PROD_DETAILS.REC_STATUS
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setRecStatus(String recStatus) {
        this.recStatus = recStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SETT_PROD_DETAILS.FIELD1
     *
     * @return the value of T_SETT_PROD_DETAILS.FIELD1
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SETT_PROD_DETAILS.FIELD1
     *
     * @param field1 the value for T_SETT_PROD_DETAILS.FIELD1
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    public void setField1(String field1) {
        this.field1 = field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_PROD_DETAILS
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SettProdDetails other = (SettProdDetails) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPrdId() == null ? other.getPrdId() == null : this.getPrdId().equals(other.getPrdId()))
            && (this.getChannleId() == null ? other.getChannleId() == null : this.getChannleId().equals(other.getChannleId()))
            && (this.getProdId() == null ? other.getProdId() == null : this.getProdId().equals(other.getProdId()))
            && (this.getProductType() == null ? other.getProductType() == null : this.getProductType().equals(other.getProductType()))
            && (this.getSettDate() == null ? other.getSettDate() == null : this.getSettDate().equals(other.getSettDate()))
            && (this.getCustId() == null ? other.getCustId() == null : this.getCustId().equals(other.getCustId()))
            && (this.getMchntRecordId() == null ? other.getMchntRecordId() == null : this.getMchntRecordId().equals(other.getMchntRecordId()))
            && (this.getProdRecordId() == null ? other.getProdRecordId() == null : this.getProdRecordId().equals(other.getProdRecordId()))
            && (this.getTransType() == null ? other.getTransType() == null : this.getTransType().equals(other.getTransType()))
            && (this.getTransAmt() == null ? other.getTransAmt() == null : this.getTransAmt().equals(other.getTransAmt()))
            && (this.getFeeAmt() == null ? other.getFeeAmt() == null : this.getFeeAmt().equals(other.getFeeAmt()))
            && (this.getTransReqDate() == null ? other.getTransReqDate() == null : this.getTransReqDate().equals(other.getTransReqDate()))
            && (this.getTransRspDate() == null ? other.getTransRspDate() == null : this.getTransRspDate().equals(other.getTransRspDate()))
            && (this.getCertNo() == null ? other.getCertNo() == null : this.getCertNo().equals(other.getCertNo()))
            && (this.getCertType() == null ? other.getCertType() == null : this.getCertType().equals(other.getCertType()))
            && (this.getValueDate() == null ? other.getValueDate() == null : this.getValueDate().equals(other.getValueDate()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getProdFeeAmt() == null ? other.getProdFeeAmt() == null : this.getProdFeeAmt().equals(other.getProdFeeAmt()))
            && (this.getRetMsg() == null ? other.getRetMsg() == null : this.getRetMsg().equals(other.getRetMsg()))
            && (this.getCrtTime() == null ? other.getCrtTime() == null : this.getCrtTime().equals(other.getCrtTime()))
            && (this.getUpdTime() == null ? other.getUpdTime() == null : this.getUpdTime().equals(other.getUpdTime()))
            && (this.getRecStatus() == null ? other.getRecStatus() == null : this.getRecStatus().equals(other.getRecStatus()))
            && (this.getField1() == null ? other.getField1() == null : this.getField1().equals(other.getField1()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_PROD_DETAILS
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPrdId() == null) ? 0 : getPrdId().hashCode());
        result = prime * result + ((getChannleId() == null) ? 0 : getChannleId().hashCode());
        result = prime * result + ((getProdId() == null) ? 0 : getProdId().hashCode());
        result = prime * result + ((getProductType() == null) ? 0 : getProductType().hashCode());
        result = prime * result + ((getSettDate() == null) ? 0 : getSettDate().hashCode());
        result = prime * result + ((getCustId() == null) ? 0 : getCustId().hashCode());
        result = prime * result + ((getMchntRecordId() == null) ? 0 : getMchntRecordId().hashCode());
        result = prime * result + ((getProdRecordId() == null) ? 0 : getProdRecordId().hashCode());
        result = prime * result + ((getTransType() == null) ? 0 : getTransType().hashCode());
        result = prime * result + ((getTransAmt() == null) ? 0 : getTransAmt().hashCode());
        result = prime * result + ((getFeeAmt() == null) ? 0 : getFeeAmt().hashCode());
        result = prime * result + ((getTransReqDate() == null) ? 0 : getTransReqDate().hashCode());
        result = prime * result + ((getTransRspDate() == null) ? 0 : getTransRspDate().hashCode());
        result = prime * result + ((getCertNo() == null) ? 0 : getCertNo().hashCode());
        result = prime * result + ((getCertType() == null) ? 0 : getCertType().hashCode());
        result = prime * result + ((getValueDate() == null) ? 0 : getValueDate().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getProdFeeAmt() == null) ? 0 : getProdFeeAmt().hashCode());
        result = prime * result + ((getRetMsg() == null) ? 0 : getRetMsg().hashCode());
        result = prime * result + ((getCrtTime() == null) ? 0 : getCrtTime().hashCode());
        result = prime * result + ((getUpdTime() == null) ? 0 : getUpdTime().hashCode());
        result = prime * result + ((getRecStatus() == null) ? 0 : getRecStatus().hashCode());
        result = prime * result + ((getField1() == null) ? 0 : getField1().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_PROD_DETAILS
     *
     * @mbggenerated Mon Jul 06 15:17:44 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", prdId=").append(prdId);
        sb.append(", channleId=").append(channleId);
        sb.append(", prodId=").append(prodId);
        sb.append(", productType=").append(productType);
        sb.append(", settDate=").append(settDate);
        sb.append(", custId=").append(custId);
        sb.append(", mchntRecordId=").append(mchntRecordId);
        sb.append(", prodRecordId=").append(prodRecordId);
        sb.append(", transType=").append(transType);
        sb.append(", transAmt=").append(transAmt);
        sb.append(", feeAmt=").append(feeAmt);
        sb.append(", transReqDate=").append(transReqDate);
        sb.append(", transRspDate=").append(transRspDate);
        sb.append(", certNo=").append(certNo);
        sb.append(", certType=").append(certType);
        sb.append(", valueDate=").append(valueDate);
        sb.append(", status=").append(status);
        sb.append(", prodFeeAmt=").append(prodFeeAmt);
        sb.append(", retMsg=").append(retMsg);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", updTime=").append(updTime);
        sb.append(", recStatus=").append(recStatus);
        sb.append(", field1=").append(field1);
        sb.append("]");
        return sb.toString();
    }
}