package starstart.cgame.flows.mysqlgens.sett.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class SettLandAcctDetailsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    public SettLandAcctDetailsExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoIsNull() {
            addCriterion("DIG_ACCT_NO is null");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoIsNotNull() {
            addCriterion("DIG_ACCT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoEqualTo(String value) {
            addCriterion("DIG_ACCT_NO =", value, "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoNotEqualTo(String value) {
            addCriterion("DIG_ACCT_NO <>", value, "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoGreaterThan(String value) {
            addCriterion("DIG_ACCT_NO >", value, "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoGreaterThanOrEqualTo(String value) {
            addCriterion("DIG_ACCT_NO >=", value, "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoLessThan(String value) {
            addCriterion("DIG_ACCT_NO <", value, "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoLessThanOrEqualTo(String value) {
            addCriterion("DIG_ACCT_NO <=", value, "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoLike(String value) {
            addCriterion("DIG_ACCT_NO like", value, "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoNotLike(String value) {
            addCriterion("DIG_ACCT_NO not like", value, "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoIn(List<String> values) {
            addCriterion("DIG_ACCT_NO in", values, "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoNotIn(List<String> values) {
            addCriterion("DIG_ACCT_NO not in", values, "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoBetween(String value1, String value2) {
            addCriterion("DIG_ACCT_NO between", value1, value2, "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoNotBetween(String value1, String value2) {
            addCriterion("DIG_ACCT_NO not between", value1, value2, "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andMchntIdIsNull() {
            addCriterion("MCHNT_ID is null");
            return (Criteria) this;
        }

        public Criteria andMchntIdIsNotNull() {
            addCriterion("MCHNT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMchntIdEqualTo(String value) {
            addCriterion("MCHNT_ID =", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdNotEqualTo(String value) {
            addCriterion("MCHNT_ID <>", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdGreaterThan(String value) {
            addCriterion("MCHNT_ID >", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdGreaterThanOrEqualTo(String value) {
            addCriterion("MCHNT_ID >=", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdLessThan(String value) {
            addCriterion("MCHNT_ID <", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdLessThanOrEqualTo(String value) {
            addCriterion("MCHNT_ID <=", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdLike(String value) {
            addCriterion("MCHNT_ID like", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdNotLike(String value) {
            addCriterion("MCHNT_ID not like", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdIn(List<String> values) {
            addCriterion("MCHNT_ID in", values, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdNotIn(List<String> values) {
            addCriterion("MCHNT_ID not in", values, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdBetween(String value1, String value2) {
            addCriterion("MCHNT_ID between", value1, value2, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdNotBetween(String value1, String value2) {
            addCriterion("MCHNT_ID not between", value1, value2, "mchntId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("CHANNEL_ID is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("CHANNEL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(String value) {
            addCriterion("CHANNEL_ID =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(String value) {
            addCriterion("CHANNEL_ID <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(String value) {
            addCriterion("CHANNEL_ID >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_ID >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(String value) {
            addCriterion("CHANNEL_ID <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_ID <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLike(String value) {
            addCriterion("CHANNEL_ID like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotLike(String value) {
            addCriterion("CHANNEL_ID not like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<String> values) {
            addCriterion("CHANNEL_ID in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<String> values) {
            addCriterion("CHANNEL_ID not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(String value1, String value2) {
            addCriterion("CHANNEL_ID between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_ID not between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNull() {
            addCriterion("PROD_ID is null");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNotNull() {
            addCriterion("PROD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProdIdEqualTo(String value) {
            addCriterion("PROD_ID =", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotEqualTo(String value) {
            addCriterion("PROD_ID <>", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThan(String value) {
            addCriterion("PROD_ID >", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThanOrEqualTo(String value) {
            addCriterion("PROD_ID >=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThan(String value) {
            addCriterion("PROD_ID <", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThanOrEqualTo(String value) {
            addCriterion("PROD_ID <=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLike(String value) {
            addCriterion("PROD_ID like", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotLike(String value) {
            addCriterion("PROD_ID not like", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdIn(List<String> values) {
            addCriterion("PROD_ID in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotIn(List<String> values) {
            addCriterion("PROD_ID not in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdBetween(String value1, String value2) {
            addCriterion("PROD_ID between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotBetween(String value1, String value2) {
            addCriterion("PROD_ID not between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andSettleDateIsNull() {
            addCriterion("SETTLE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSettleDateIsNotNull() {
            addCriterion("SETTLE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSettleDateEqualTo(String value) {
            addCriterion("SETTLE_DATE =", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotEqualTo(String value) {
            addCriterion("SETTLE_DATE <>", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateGreaterThan(String value) {
            addCriterion("SETTLE_DATE >", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateGreaterThanOrEqualTo(String value) {
            addCriterion("SETTLE_DATE >=", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateLessThan(String value) {
            addCriterion("SETTLE_DATE <", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateLessThanOrEqualTo(String value) {
            addCriterion("SETTLE_DATE <=", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateLike(String value) {
            addCriterion("SETTLE_DATE like", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotLike(String value) {
            addCriterion("SETTLE_DATE not like", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateIn(List<String> values) {
            addCriterion("SETTLE_DATE in", values, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotIn(List<String> values) {
            addCriterion("SETTLE_DATE not in", values, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateBetween(String value1, String value2) {
            addCriterion("SETTLE_DATE between", value1, value2, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotBetween(String value1, String value2) {
            addCriterion("SETTLE_DATE not between", value1, value2, "settleDate");
            return (Criteria) this;
        }

        public Criteria andValueDateIsNull() {
            addCriterion("VALUE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andValueDateIsNotNull() {
            addCriterion("VALUE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andValueDateEqualTo(String value) {
            addCriterion("VALUE_DATE =", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotEqualTo(String value) {
            addCriterion("VALUE_DATE <>", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateGreaterThan(String value) {
            addCriterion("VALUE_DATE >", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateGreaterThanOrEqualTo(String value) {
            addCriterion("VALUE_DATE >=", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateLessThan(String value) {
            addCriterion("VALUE_DATE <", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateLessThanOrEqualTo(String value) {
            addCriterion("VALUE_DATE <=", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateLike(String value) {
            addCriterion("VALUE_DATE like", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotLike(String value) {
            addCriterion("VALUE_DATE not like", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateIn(List<String> values) {
            addCriterion("VALUE_DATE in", values, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotIn(List<String> values) {
            addCriterion("VALUE_DATE not in", values, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateBetween(String value1, String value2) {
            addCriterion("VALUE_DATE between", value1, value2, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotBetween(String value1, String value2) {
            addCriterion("VALUE_DATE not between", value1, value2, "valueDate");
            return (Criteria) this;
        }

        public Criteria andYestdTotSyIsNull() {
            addCriterion("YESTD_TOT_SY is null");
            return (Criteria) this;
        }

        public Criteria andYestdTotSyIsNotNull() {
            addCriterion("YESTD_TOT_SY is not null");
            return (Criteria) this;
        }

        public Criteria andYestdTotSyEqualTo(BigDecimal value) {
            addCriterion("YESTD_TOT_SY =", value, "yestdTotSy");
            return (Criteria) this;
        }

        public Criteria andYestdTotSyNotEqualTo(BigDecimal value) {
            addCriterion("YESTD_TOT_SY <>", value, "yestdTotSy");
            return (Criteria) this;
        }

        public Criteria andYestdTotSyGreaterThan(BigDecimal value) {
            addCriterion("YESTD_TOT_SY >", value, "yestdTotSy");
            return (Criteria) this;
        }

        public Criteria andYestdTotSyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("YESTD_TOT_SY >=", value, "yestdTotSy");
            return (Criteria) this;
        }

        public Criteria andYestdTotSyLessThan(BigDecimal value) {
            addCriterion("YESTD_TOT_SY <", value, "yestdTotSy");
            return (Criteria) this;
        }

        public Criteria andYestdTotSyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("YESTD_TOT_SY <=", value, "yestdTotSy");
            return (Criteria) this;
        }

        public Criteria andYestdTotSyIn(List<BigDecimal> values) {
            addCriterion("YESTD_TOT_SY in", values, "yestdTotSy");
            return (Criteria) this;
        }

        public Criteria andYestdTotSyNotIn(List<BigDecimal> values) {
            addCriterion("YESTD_TOT_SY not in", values, "yestdTotSy");
            return (Criteria) this;
        }

        public Criteria andYestdTotSyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YESTD_TOT_SY between", value1, value2, "yestdTotSy");
            return (Criteria) this;
        }

        public Criteria andYestdTotSyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YESTD_TOT_SY not between", value1, value2, "yestdTotSy");
            return (Criteria) this;
        }

        public Criteria andTodayTotSyIsNull() {
            addCriterion("TODAY_TOT_SY is null");
            return (Criteria) this;
        }

        public Criteria andTodayTotSyIsNotNull() {
            addCriterion("TODAY_TOT_SY is not null");
            return (Criteria) this;
        }

        public Criteria andTodayTotSyEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_SY =", value, "todayTotSy");
            return (Criteria) this;
        }

        public Criteria andTodayTotSyNotEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_SY <>", value, "todayTotSy");
            return (Criteria) this;
        }

        public Criteria andTodayTotSyGreaterThan(BigDecimal value) {
            addCriterion("TODAY_TOT_SY >", value, "todayTotSy");
            return (Criteria) this;
        }

        public Criteria andTodayTotSyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_SY >=", value, "todayTotSy");
            return (Criteria) this;
        }

        public Criteria andTodayTotSyLessThan(BigDecimal value) {
            addCriterion("TODAY_TOT_SY <", value, "todayTotSy");
            return (Criteria) this;
        }

        public Criteria andTodayTotSyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_SY <=", value, "todayTotSy");
            return (Criteria) this;
        }

        public Criteria andTodayTotSyIn(List<BigDecimal> values) {
            addCriterion("TODAY_TOT_SY in", values, "todayTotSy");
            return (Criteria) this;
        }

        public Criteria andTodayTotSyNotIn(List<BigDecimal> values) {
            addCriterion("TODAY_TOT_SY not in", values, "todayTotSy");
            return (Criteria) this;
        }

        public Criteria andTodayTotSyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TODAY_TOT_SY between", value1, value2, "todayTotSy");
            return (Criteria) this;
        }

        public Criteria andTodayTotSyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TODAY_TOT_SY not between", value1, value2, "todayTotSy");
            return (Criteria) this;
        }

        public Criteria andTodayTotFeIsNull() {
            addCriterion("TODAY_TOT_FE is null");
            return (Criteria) this;
        }

        public Criteria andTodayTotFeIsNotNull() {
            addCriterion("TODAY_TOT_FE is not null");
            return (Criteria) this;
        }

        public Criteria andTodayTotFeEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_FE =", value, "todayTotFe");
            return (Criteria) this;
        }

        public Criteria andTodayTotFeNotEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_FE <>", value, "todayTotFe");
            return (Criteria) this;
        }

        public Criteria andTodayTotFeGreaterThan(BigDecimal value) {
            addCriterion("TODAY_TOT_FE >", value, "todayTotFe");
            return (Criteria) this;
        }

        public Criteria andTodayTotFeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_FE >=", value, "todayTotFe");
            return (Criteria) this;
        }

        public Criteria andTodayTotFeLessThan(BigDecimal value) {
            addCriterion("TODAY_TOT_FE <", value, "todayTotFe");
            return (Criteria) this;
        }

        public Criteria andTodayTotFeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_FE <=", value, "todayTotFe");
            return (Criteria) this;
        }

        public Criteria andTodayTotFeIn(List<BigDecimal> values) {
            addCriterion("TODAY_TOT_FE in", values, "todayTotFe");
            return (Criteria) this;
        }

        public Criteria andTodayTotFeNotIn(List<BigDecimal> values) {
            addCriterion("TODAY_TOT_FE not in", values, "todayTotFe");
            return (Criteria) this;
        }

        public Criteria andTodayTotFeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TODAY_TOT_FE between", value1, value2, "todayTotFe");
            return (Criteria) this;
        }

        public Criteria andTodayTotFeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TODAY_TOT_FE not between", value1, value2, "todayTotFe");
            return (Criteria) this;
        }

        public Criteria andTodayTotSgIsNull() {
            addCriterion("TODAY_TOT_SG is null");
            return (Criteria) this;
        }

        public Criteria andTodayTotSgIsNotNull() {
            addCriterion("TODAY_TOT_SG is not null");
            return (Criteria) this;
        }

        public Criteria andTodayTotSgEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_SG =", value, "todayTotSg");
            return (Criteria) this;
        }

        public Criteria andTodayTotSgNotEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_SG <>", value, "todayTotSg");
            return (Criteria) this;
        }

        public Criteria andTodayTotSgGreaterThan(BigDecimal value) {
            addCriterion("TODAY_TOT_SG >", value, "todayTotSg");
            return (Criteria) this;
        }

        public Criteria andTodayTotSgGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_SG >=", value, "todayTotSg");
            return (Criteria) this;
        }

        public Criteria andTodayTotSgLessThan(BigDecimal value) {
            addCriterion("TODAY_TOT_SG <", value, "todayTotSg");
            return (Criteria) this;
        }

        public Criteria andTodayTotSgLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_SG <=", value, "todayTotSg");
            return (Criteria) this;
        }

        public Criteria andTodayTotSgIn(List<BigDecimal> values) {
            addCriterion("TODAY_TOT_SG in", values, "todayTotSg");
            return (Criteria) this;
        }

        public Criteria andTodayTotSgNotIn(List<BigDecimal> values) {
            addCriterion("TODAY_TOT_SG not in", values, "todayTotSg");
            return (Criteria) this;
        }

        public Criteria andTodayTotSgBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TODAY_TOT_SG between", value1, value2, "todayTotSg");
            return (Criteria) this;
        }

        public Criteria andTodayTotSgNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TODAY_TOT_SG not between", value1, value2, "todayTotSg");
            return (Criteria) this;
        }

        public Criteria andTodayTotShIsNull() {
            addCriterion("TODAY_TOT_SH is null");
            return (Criteria) this;
        }

        public Criteria andTodayTotShIsNotNull() {
            addCriterion("TODAY_TOT_SH is not null");
            return (Criteria) this;
        }

        public Criteria andTodayTotShEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_SH =", value, "todayTotSh");
            return (Criteria) this;
        }

        public Criteria andTodayTotShNotEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_SH <>", value, "todayTotSh");
            return (Criteria) this;
        }

        public Criteria andTodayTotShGreaterThan(BigDecimal value) {
            addCriterion("TODAY_TOT_SH >", value, "todayTotSh");
            return (Criteria) this;
        }

        public Criteria andTodayTotShGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_SH >=", value, "todayTotSh");
            return (Criteria) this;
        }

        public Criteria andTodayTotShLessThan(BigDecimal value) {
            addCriterion("TODAY_TOT_SH <", value, "todayTotSh");
            return (Criteria) this;
        }

        public Criteria andTodayTotShLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TODAY_TOT_SH <=", value, "todayTotSh");
            return (Criteria) this;
        }

        public Criteria andTodayTotShIn(List<BigDecimal> values) {
            addCriterion("TODAY_TOT_SH in", values, "todayTotSh");
            return (Criteria) this;
        }

        public Criteria andTodayTotShNotIn(List<BigDecimal> values) {
            addCriterion("TODAY_TOT_SH not in", values, "todayTotSh");
            return (Criteria) this;
        }

        public Criteria andTodayTotShBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TODAY_TOT_SH between", value1, value2, "todayTotSh");
            return (Criteria) this;
        }

        public Criteria andTodayTotShNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TODAY_TOT_SH not between", value1, value2, "todayTotSh");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOutProdIdIsNull() {
            addCriterion("OUT_PROD_ID is null");
            return (Criteria) this;
        }

        public Criteria andOutProdIdIsNotNull() {
            addCriterion("OUT_PROD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOutProdIdEqualTo(String value) {
            addCriterion("OUT_PROD_ID =", value, "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutProdIdNotEqualTo(String value) {
            addCriterion("OUT_PROD_ID <>", value, "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutProdIdGreaterThan(String value) {
            addCriterion("OUT_PROD_ID >", value, "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutProdIdGreaterThanOrEqualTo(String value) {
            addCriterion("OUT_PROD_ID >=", value, "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutProdIdLessThan(String value) {
            addCriterion("OUT_PROD_ID <", value, "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutProdIdLessThanOrEqualTo(String value) {
            addCriterion("OUT_PROD_ID <=", value, "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutProdIdLike(String value) {
            addCriterion("OUT_PROD_ID like", value, "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutProdIdNotLike(String value) {
            addCriterion("OUT_PROD_ID not like", value, "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutProdIdIn(List<String> values) {
            addCriterion("OUT_PROD_ID in", values, "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutProdIdNotIn(List<String> values) {
            addCriterion("OUT_PROD_ID not in", values, "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutProdIdBetween(String value1, String value2) {
            addCriterion("OUT_PROD_ID between", value1, value2, "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutProdIdNotBetween(String value1, String value2) {
            addCriterion("OUT_PROD_ID not between", value1, value2, "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdIsNull() {
            addCriterion("OUT_SUB_PROD_ID is null");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdIsNotNull() {
            addCriterion("OUT_SUB_PROD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdEqualTo(String value) {
            addCriterion("OUT_SUB_PROD_ID =", value, "outSubProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdNotEqualTo(String value) {
            addCriterion("OUT_SUB_PROD_ID <>", value, "outSubProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdGreaterThan(String value) {
            addCriterion("OUT_SUB_PROD_ID >", value, "outSubProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdGreaterThanOrEqualTo(String value) {
            addCriterion("OUT_SUB_PROD_ID >=", value, "outSubProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdLessThan(String value) {
            addCriterion("OUT_SUB_PROD_ID <", value, "outSubProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdLessThanOrEqualTo(String value) {
            addCriterion("OUT_SUB_PROD_ID <=", value, "outSubProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdLike(String value) {
            addCriterion("OUT_SUB_PROD_ID like", value, "outSubProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdNotLike(String value) {
            addCriterion("OUT_SUB_PROD_ID not like", value, "outSubProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdIn(List<String> values) {
            addCriterion("OUT_SUB_PROD_ID in", values, "outSubProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdNotIn(List<String> values) {
            addCriterion("OUT_SUB_PROD_ID not in", values, "outSubProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdBetween(String value1, String value2) {
            addCriterion("OUT_SUB_PROD_ID between", value1, value2, "outSubProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdNotBetween(String value1, String value2) {
            addCriterion("OUT_SUB_PROD_ID not between", value1, value2, "outSubProdId");
            return (Criteria) this;
        }

        public Criteria andIdLikeInsensitive(String value) {
            addCriterion("upper(ID) like", value.toUpperCase(), "id");
            return (Criteria) this;
        }

        public Criteria andDigAcctNoLikeInsensitive(String value) {
            addCriterion("upper(DIG_ACCT_NO) like", value.toUpperCase(), "digAcctNo");
            return (Criteria) this;
        }

        public Criteria andMchntIdLikeInsensitive(String value) {
            addCriterion("upper(MCHNT_ID) like", value.toUpperCase(), "mchntId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLikeInsensitive(String value) {
            addCriterion("upper(CHANNEL_ID) like", value.toUpperCase(), "channelId");
            return (Criteria) this;
        }

        public Criteria andProdIdLikeInsensitive(String value) {
            addCriterion("upper(PROD_ID) like", value.toUpperCase(), "prodId");
            return (Criteria) this;
        }

        public Criteria andSettleDateLikeInsensitive(String value) {
            addCriterion("upper(SETTLE_DATE) like", value.toUpperCase(), "settleDate");
            return (Criteria) this;
        }

        public Criteria andValueDateLikeInsensitive(String value) {
            addCriterion("upper(VALUE_DATE) like", value.toUpperCase(), "valueDate");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(STATUS) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andOutProdIdLikeInsensitive(String value) {
            addCriterion("upper(OUT_PROD_ID) like", value.toUpperCase(), "outProdId");
            return (Criteria) this;
        }

        public Criteria andOutSubProdIdLikeInsensitive(String value) {
            addCriterion("upper(OUT_SUB_PROD_ID) like", value.toUpperCase(), "outSubProdId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 29 16:32:44 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SETT_LAND_ACCT_DETAILS
     *
     * @mbggenerated Wed Jul 29 16:32:44 CST 2015
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}