package onight.tfg.ordbgens.tlt.mapper;

import java.util.List;
import onight.tfg.ordbgens.tlt.entity.TLTCoreBet;
import onight.tfg.ordbgens.tlt.entity.TLTCoreBetExample;
import onight.tfg.ordbgens.tlt.entity.TLTCoreBetKey;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TLTCoreBetMapper extends StaticTableDaoSupport<TLTCoreBet, TLTCoreBetExample, TLTCoreBetKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 07 13:37:31 CST 2016
     */
    @SelectProvider(type=TLTCoreBetSqlProvider.class, method="countByExample")
    int countByExample(TLTCoreBetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 07 13:37:31 CST 2016
     */
    @DeleteProvider(type=TLTCoreBetSqlProvider.class, method="deleteByExample")
    int deleteByExample(TLTCoreBetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 07 13:37:31 CST 2016
     */
    @Delete({
        "delete from TLT_CORE_BET",
        "where TICK_NO = #{tickNo,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TLTCoreBetKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 07 13:37:31 CST 2016
     */
    @Insert({
        "insert into TLT_CORE_BET (TICK_NO, LTYPE, ",
        "LNAME, PLAY_TYPE, ",
        "MERCHANTID, SERIAL_NUM, ",
        "BET_AMOUNTS, BET_COUNTS, ",
        "BET_MULTI, ISSUE_NO, ",
        "BET_DATETIME, BET_CONTENT, ",
        "BET_IP, BET_MONEY_UNIT, ",
        "BONUS_MONEY_MODE, BONUS_RATE_MODE, ",
        "VERSION, PRINTTIME, ",
        "BET_STATUS, NOTIFYSTATUS, ",
        "REGION, FAILREASON, ",
        "MERCHANTUSERID, USER_ID, ",
        "AUTOBET_NO, IS_AUTO, ",
        "AUTO_REF_TICKNO)",
        "values (#{tickNo,jdbcType=VARCHAR}, #{ltype,jdbcType=VARCHAR}, ",
        "#{lname,jdbcType=VARCHAR}, #{playType,jdbcType=VARCHAR}, ",
        "#{merchantid,jdbcType=VARCHAR}, #{serialNum,jdbcType=VARCHAR}, ",
        "#{betAmounts,jdbcType=DECIMAL}, #{betCounts,jdbcType=DECIMAL}, ",
        "#{betMulti,jdbcType=DECIMAL}, #{issueNo,jdbcType=VARCHAR}, ",
        "#{betDatetime,jdbcType=TIMESTAMP}, #{betContent,jdbcType=VARCHAR}, ",
        "#{betIp,jdbcType=VARCHAR}, #{betMoneyUnit,jdbcType=INTEGER}, ",
        "#{bonusMoneyMode,jdbcType=DECIMAL}, #{bonusRateMode,jdbcType=DECIMAL}, ",
        "#{version,jdbcType=VARCHAR}, #{printtime,jdbcType=DECIMAL}, ",
        "#{betStatus,jdbcType=DECIMAL}, #{notifystatus,jdbcType=DECIMAL}, ",
        "#{region,jdbcType=VARCHAR}, #{failreason,jdbcType=VARCHAR}, ",
        "#{merchantuserid,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
        "#{autobetNo,jdbcType=VARCHAR}, #{isAuto,jdbcType=VARCHAR}, ",
        "#{autoRefTickno,jdbcType=VARCHAR})"
    })
    int insert(TLTCoreBet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 07 13:37:31 CST 2016
     */
    @InsertProvider(type=TLTCoreBetSqlProvider.class, method="insertSelective")
    int insertSelective(TLTCoreBet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 07 13:37:31 CST 2016
     */
    @SelectProvider(type=TLTCoreBetSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="TICK_NO", property="tickNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="LTYPE", property="ltype", jdbcType=JdbcType.VARCHAR),
        @Result(column="LNAME", property="lname", jdbcType=JdbcType.VARCHAR),
        @Result(column="PLAY_TYPE", property="playType", jdbcType=JdbcType.VARCHAR),
        @Result(column="MERCHANTID", property="merchantid", jdbcType=JdbcType.VARCHAR),
        @Result(column="SERIAL_NUM", property="serialNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="BET_AMOUNTS", property="betAmounts", jdbcType=JdbcType.DECIMAL),
        @Result(column="BET_COUNTS", property="betCounts", jdbcType=JdbcType.DECIMAL),
        @Result(column="BET_MULTI", property="betMulti", jdbcType=JdbcType.DECIMAL),
        @Result(column="ISSUE_NO", property="issueNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="BET_DATETIME", property="betDatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="BET_CONTENT", property="betContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="BET_IP", property="betIp", jdbcType=JdbcType.VARCHAR),
        @Result(column="BET_MONEY_UNIT", property="betMoneyUnit", jdbcType=JdbcType.INTEGER),
        @Result(column="BONUS_MONEY_MODE", property="bonusMoneyMode", jdbcType=JdbcType.DECIMAL),
        @Result(column="BONUS_RATE_MODE", property="bonusRateMode", jdbcType=JdbcType.DECIMAL),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRINTTIME", property="printtime", jdbcType=JdbcType.DECIMAL),
        @Result(column="BET_STATUS", property="betStatus", jdbcType=JdbcType.DECIMAL),
        @Result(column="NOTIFYSTATUS", property="notifystatus", jdbcType=JdbcType.DECIMAL),
        @Result(column="REGION", property="region", jdbcType=JdbcType.VARCHAR),
        @Result(column="FAILREASON", property="failreason", jdbcType=JdbcType.VARCHAR),
        @Result(column="MERCHANTUSERID", property="merchantuserid", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="AUTOBET_NO", property="autobetNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="IS_AUTO", property="isAuto", jdbcType=JdbcType.VARCHAR),
        @Result(column="AUTO_REF_TICKNO", property="autoRefTickno", jdbcType=JdbcType.VARCHAR)
    })
    List<TLTCoreBet> selectByExample(TLTCoreBetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 07 13:37:31 CST 2016
     */
    @Select({
        "select",
        "TICK_NO, LTYPE, LNAME, PLAY_TYPE, MERCHANTID, SERIAL_NUM, BET_AMOUNTS, BET_COUNTS, ",
        "BET_MULTI, ISSUE_NO, BET_DATETIME, BET_CONTENT, BET_IP, BET_MONEY_UNIT, BONUS_MONEY_MODE, ",
        "BONUS_RATE_MODE, VERSION, PRINTTIME, BET_STATUS, NOTIFYSTATUS, REGION, FAILREASON, ",
        "MERCHANTUSERID, USER_ID, AUTOBET_NO, IS_AUTO, AUTO_REF_TICKNO",
        "from TLT_CORE_BET",
        "where TICK_NO = #{tickNo,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="TICK_NO", property="tickNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="LTYPE", property="ltype", jdbcType=JdbcType.VARCHAR),
        @Result(column="LNAME", property="lname", jdbcType=JdbcType.VARCHAR),
        @Result(column="PLAY_TYPE", property="playType", jdbcType=JdbcType.VARCHAR),
        @Result(column="MERCHANTID", property="merchantid", jdbcType=JdbcType.VARCHAR),
        @Result(column="SERIAL_NUM", property="serialNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="BET_AMOUNTS", property="betAmounts", jdbcType=JdbcType.DECIMAL),
        @Result(column="BET_COUNTS", property="betCounts", jdbcType=JdbcType.DECIMAL),
        @Result(column="BET_MULTI", property="betMulti", jdbcType=JdbcType.DECIMAL),
        @Result(column="ISSUE_NO", property="issueNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="BET_DATETIME", property="betDatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="BET_CONTENT", property="betContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="BET_IP", property="betIp", jdbcType=JdbcType.VARCHAR),
        @Result(column="BET_MONEY_UNIT", property="betMoneyUnit", jdbcType=JdbcType.INTEGER),
        @Result(column="BONUS_MONEY_MODE", property="bonusMoneyMode", jdbcType=JdbcType.DECIMAL),
        @Result(column="BONUS_RATE_MODE", property="bonusRateMode", jdbcType=JdbcType.DECIMAL),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRINTTIME", property="printtime", jdbcType=JdbcType.DECIMAL),
        @Result(column="BET_STATUS", property="betStatus", jdbcType=JdbcType.DECIMAL),
        @Result(column="NOTIFYSTATUS", property="notifystatus", jdbcType=JdbcType.DECIMAL),
        @Result(column="REGION", property="region", jdbcType=JdbcType.VARCHAR),
        @Result(column="FAILREASON", property="failreason", jdbcType=JdbcType.VARCHAR),
        @Result(column="MERCHANTUSERID", property="merchantuserid", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="AUTOBET_NO", property="autobetNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="IS_AUTO", property="isAuto", jdbcType=JdbcType.VARCHAR),
        @Result(column="AUTO_REF_TICKNO", property="autoRefTickno", jdbcType=JdbcType.VARCHAR)
    })
    TLTCoreBet selectByPrimaryKey(TLTCoreBetKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 07 13:37:31 CST 2016
     */
    @UpdateProvider(type=TLTCoreBetSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TLTCoreBet record, @Param("example") TLTCoreBetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 07 13:37:31 CST 2016
     */
    @UpdateProvider(type=TLTCoreBetSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TLTCoreBet record, @Param("example") TLTCoreBetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 07 13:37:31 CST 2016
     */
    @UpdateProvider(type=TLTCoreBetSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TLTCoreBet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_CORE_BET
     *
     * @mbggenerated Thu Apr 07 13:37:31 CST 2016
     */
    @Update({
        "update TLT_CORE_BET",
        "set LTYPE = #{ltype,jdbcType=VARCHAR},",
          "LNAME = #{lname,jdbcType=VARCHAR},",
          "PLAY_TYPE = #{playType,jdbcType=VARCHAR},",
          "MERCHANTID = #{merchantid,jdbcType=VARCHAR},",
          "SERIAL_NUM = #{serialNum,jdbcType=VARCHAR},",
          "BET_AMOUNTS = #{betAmounts,jdbcType=DECIMAL},",
          "BET_COUNTS = #{betCounts,jdbcType=DECIMAL},",
          "BET_MULTI = #{betMulti,jdbcType=DECIMAL},",
          "ISSUE_NO = #{issueNo,jdbcType=VARCHAR},",
          "BET_DATETIME = #{betDatetime,jdbcType=TIMESTAMP},",
          "BET_CONTENT = #{betContent,jdbcType=VARCHAR},",
          "BET_IP = #{betIp,jdbcType=VARCHAR},",
          "BET_MONEY_UNIT = #{betMoneyUnit,jdbcType=INTEGER},",
          "BONUS_MONEY_MODE = #{bonusMoneyMode,jdbcType=DECIMAL},",
          "BONUS_RATE_MODE = #{bonusRateMode,jdbcType=DECIMAL},",
          "VERSION = #{version,jdbcType=VARCHAR},",
          "PRINTTIME = #{printtime,jdbcType=DECIMAL},",
          "BET_STATUS = #{betStatus,jdbcType=DECIMAL},",
          "NOTIFYSTATUS = #{notifystatus,jdbcType=DECIMAL},",
          "REGION = #{region,jdbcType=VARCHAR},",
          "FAILREASON = #{failreason,jdbcType=VARCHAR},",
          "MERCHANTUSERID = #{merchantuserid,jdbcType=VARCHAR},",
          "USER_ID = #{userId,jdbcType=VARCHAR},",
          "AUTOBET_NO = #{autobetNo,jdbcType=VARCHAR},",
          "IS_AUTO = #{isAuto,jdbcType=VARCHAR},",
          "AUTO_REF_TICKNO = #{autoRefTickno,jdbcType=VARCHAR}",
        "where TICK_NO = #{tickNo,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TLTCoreBet record);
}