package onight.tfg.ordbgens.tlt.mapper;

import java.util.List;
import onight.tfg.ordbgens.tlt.entity.TLTLimitedFeature;
import onight.tfg.ordbgens.tlt.entity.TLTLimitedFeatureExample;
import onight.tfg.ordbgens.tlt.entity.TLTLimitedFeatureKey;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TLTLimitedFeatureMapper extends StaticTableDaoSupport<TLTLimitedFeature, TLTLimitedFeatureExample, TLTLimitedFeatureKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LIMITED_FEATURE
     *
     * @mbggenerated Sat Apr 16 13:41:10 CST 2016
     */
    @SelectProvider(type=TLTLimitedFeatureSqlProvider.class, method="countByExample")
    int countByExample(TLTLimitedFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LIMITED_FEATURE
     *
     * @mbggenerated Sat Apr 16 13:41:10 CST 2016
     */
    @DeleteProvider(type=TLTLimitedFeatureSqlProvider.class, method="deleteByExample")
    int deleteByExample(TLTLimitedFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LIMITED_FEATURE
     *
     * @mbggenerated Sat Apr 16 13:41:10 CST 2016
     */
    @Delete({
        "delete from TLT_LIMITED_FEATURE",
        "where CASKEY = #{caskey,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TLTLimitedFeatureKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LIMITED_FEATURE
     *
     * @mbggenerated Sat Apr 16 13:41:10 CST 2016
     */
    @Insert({
        "insert into TLT_LIMITED_FEATURE (CASKEY, ISSUE_NO, ",
        "PLAY_TYPE, WAGERDATA, ",
        "CREATEDATE, REGION, ",
        "LTYPE, BONUS_LIMIT, ",
        "BETS_BOARDS_LIMIT, BETS_AMOUNT_LIMIT, ",
        "MERCHATID, USER_ID, ",
        "LIMIT_TYPE, START_DATE, ",
        "EXTRAFIELD1, EXTRAFIELD2, ",
        "EXTRAFIELD3, EXTRAFIELD4, ",
        "EXTRAFIELD5)",
        "values (#{caskey,jdbcType=VARCHAR}, #{issueNo,jdbcType=VARCHAR}, ",
        "#{playType,jdbcType=VARCHAR}, #{wagerdata,jdbcType=VARCHAR}, ",
        "#{createdate,jdbcType=DECIMAL}, #{region,jdbcType=VARCHAR}, ",
        "#{ltype,jdbcType=VARCHAR}, #{bonusLimit,jdbcType=DECIMAL}, ",
        "#{betsBoardsLimit,jdbcType=DECIMAL}, #{betsAmountLimit,jdbcType=DECIMAL}, ",
        "#{merchatid,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
        "#{limitType,jdbcType=VARCHAR}, #{startDate,jdbcType=TIMESTAMP}, ",
        "#{extrafield1,jdbcType=VARCHAR}, #{extrafield2,jdbcType=VARCHAR}, ",
        "#{extrafield3,jdbcType=INTEGER}, #{extrafield4,jdbcType=DECIMAL}, ",
        "#{extrafield5,jdbcType=DECIMAL})"
    })
    int insert(TLTLimitedFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LIMITED_FEATURE
     *
     * @mbggenerated Sat Apr 16 13:41:10 CST 2016
     */
    @InsertProvider(type=TLTLimitedFeatureSqlProvider.class, method="insertSelective")
    int insertSelective(TLTLimitedFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LIMITED_FEATURE
     *
     * @mbggenerated Sat Apr 16 13:41:10 CST 2016
     */
    @SelectProvider(type=TLTLimitedFeatureSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="CASKEY", property="caskey", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ISSUE_NO", property="issueNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="PLAY_TYPE", property="playType", jdbcType=JdbcType.VARCHAR),
        @Result(column="WAGERDATA", property="wagerdata", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATEDATE", property="createdate", jdbcType=JdbcType.DECIMAL),
        @Result(column="REGION", property="region", jdbcType=JdbcType.VARCHAR),
        @Result(column="LTYPE", property="ltype", jdbcType=JdbcType.VARCHAR),
        @Result(column="BONUS_LIMIT", property="bonusLimit", jdbcType=JdbcType.DECIMAL),
        @Result(column="BETS_BOARDS_LIMIT", property="betsBoardsLimit", jdbcType=JdbcType.DECIMAL),
        @Result(column="BETS_AMOUNT_LIMIT", property="betsAmountLimit", jdbcType=JdbcType.DECIMAL),
        @Result(column="MERCHATID", property="merchatid", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="LIMIT_TYPE", property="limitType", jdbcType=JdbcType.VARCHAR),
        @Result(column="START_DATE", property="startDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="EXTRAFIELD1", property="extrafield1", jdbcType=JdbcType.VARCHAR),
        @Result(column="EXTRAFIELD2", property="extrafield2", jdbcType=JdbcType.VARCHAR),
        @Result(column="EXTRAFIELD3", property="extrafield3", jdbcType=JdbcType.INTEGER),
        @Result(column="EXTRAFIELD4", property="extrafield4", jdbcType=JdbcType.DECIMAL),
        @Result(column="EXTRAFIELD5", property="extrafield5", jdbcType=JdbcType.DECIMAL)
    })
    List<TLTLimitedFeature> selectByExample(TLTLimitedFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LIMITED_FEATURE
     *
     * @mbggenerated Sat Apr 16 13:41:10 CST 2016
     */
    @Select({
        "select",
        "CASKEY, ISSUE_NO, PLAY_TYPE, WAGERDATA, CREATEDATE, REGION, LTYPE, BONUS_LIMIT, ",
        "BETS_BOARDS_LIMIT, BETS_AMOUNT_LIMIT, MERCHATID, USER_ID, LIMIT_TYPE, START_DATE, ",
        "EXTRAFIELD1, EXTRAFIELD2, EXTRAFIELD3, EXTRAFIELD4, EXTRAFIELD5",
        "from TLT_LIMITED_FEATURE",
        "where CASKEY = #{caskey,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="CASKEY", property="caskey", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ISSUE_NO", property="issueNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="PLAY_TYPE", property="playType", jdbcType=JdbcType.VARCHAR),
        @Result(column="WAGERDATA", property="wagerdata", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATEDATE", property="createdate", jdbcType=JdbcType.DECIMAL),
        @Result(column="REGION", property="region", jdbcType=JdbcType.VARCHAR),
        @Result(column="LTYPE", property="ltype", jdbcType=JdbcType.VARCHAR),
        @Result(column="BONUS_LIMIT", property="bonusLimit", jdbcType=JdbcType.DECIMAL),
        @Result(column="BETS_BOARDS_LIMIT", property="betsBoardsLimit", jdbcType=JdbcType.DECIMAL),
        @Result(column="BETS_AMOUNT_LIMIT", property="betsAmountLimit", jdbcType=JdbcType.DECIMAL),
        @Result(column="MERCHATID", property="merchatid", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="LIMIT_TYPE", property="limitType", jdbcType=JdbcType.VARCHAR),
        @Result(column="START_DATE", property="startDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="EXTRAFIELD1", property="extrafield1", jdbcType=JdbcType.VARCHAR),
        @Result(column="EXTRAFIELD2", property="extrafield2", jdbcType=JdbcType.VARCHAR),
        @Result(column="EXTRAFIELD3", property="extrafield3", jdbcType=JdbcType.INTEGER),
        @Result(column="EXTRAFIELD4", property="extrafield4", jdbcType=JdbcType.DECIMAL),
        @Result(column="EXTRAFIELD5", property="extrafield5", jdbcType=JdbcType.DECIMAL)
    })
    TLTLimitedFeature selectByPrimaryKey(TLTLimitedFeatureKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LIMITED_FEATURE
     *
     * @mbggenerated Sat Apr 16 13:41:10 CST 2016
     */
    @UpdateProvider(type=TLTLimitedFeatureSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TLTLimitedFeature record, @Param("example") TLTLimitedFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LIMITED_FEATURE
     *
     * @mbggenerated Sat Apr 16 13:41:10 CST 2016
     */
    @UpdateProvider(type=TLTLimitedFeatureSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TLTLimitedFeature record, @Param("example") TLTLimitedFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LIMITED_FEATURE
     *
     * @mbggenerated Sat Apr 16 13:41:10 CST 2016
     */
    @UpdateProvider(type=TLTLimitedFeatureSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TLTLimitedFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LIMITED_FEATURE
     *
     * @mbggenerated Sat Apr 16 13:41:10 CST 2016
     */
    @Update({
        "update TLT_LIMITED_FEATURE",
        "set ISSUE_NO = #{issueNo,jdbcType=VARCHAR},",
          "PLAY_TYPE = #{playType,jdbcType=VARCHAR},",
          "WAGERDATA = #{wagerdata,jdbcType=VARCHAR},",
          "CREATEDATE = #{createdate,jdbcType=DECIMAL},",
          "REGION = #{region,jdbcType=VARCHAR},",
          "LTYPE = #{ltype,jdbcType=VARCHAR},",
          "BONUS_LIMIT = #{bonusLimit,jdbcType=DECIMAL},",
          "BETS_BOARDS_LIMIT = #{betsBoardsLimit,jdbcType=DECIMAL},",
          "BETS_AMOUNT_LIMIT = #{betsAmountLimit,jdbcType=DECIMAL},",
          "MERCHATID = #{merchatid,jdbcType=VARCHAR},",
          "USER_ID = #{userId,jdbcType=VARCHAR},",
          "LIMIT_TYPE = #{limitType,jdbcType=VARCHAR},",
          "START_DATE = #{startDate,jdbcType=TIMESTAMP},",
          "EXTRAFIELD1 = #{extrafield1,jdbcType=VARCHAR},",
          "EXTRAFIELD2 = #{extrafield2,jdbcType=VARCHAR},",
          "EXTRAFIELD3 = #{extrafield3,jdbcType=INTEGER},",
          "EXTRAFIELD4 = #{extrafield4,jdbcType=DECIMAL},",
          "EXTRAFIELD5 = #{extrafield5,jdbcType=DECIMAL}",
        "where CASKEY = #{caskey,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TLTLimitedFeature record);
}